### PR TITLE
Update schema compare to 1.7.0

### PR DESCRIPTION
**Pull request by kisantia**
build with new vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=84130&view=artifacts&type=publishedArtifacts

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
To confirm - you want this released immediately correct?

**Review by alanrenmsft — APPROVED** [review]

**Comment by kisantia** [comment]
yup this has a fix for something a couple customers have complained about and it doesn't depend on any changes in core

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
I'll publish it now

**Comment by alanrenmsft** [comment]
published to both insider and stable gallery feeds, please validate. @kisantia

**Comment by kisantia** [comment]
validated both. Thanks @alanrenmsft!

**Pull request merged**
