### PR TITLE
Update PowerShell extension to v2019.5.0

### PR DESCRIPTION
**Pull request by rjmholt**
Updates the version of the PowerShell extension in ADS to 2019.5.0.
**Note**: This is an automated PR.

### CODE REVIEW

**Comment by kburtram** [comment]
@alanrenmsft do you have time to push this extension update today?  Or should I do it?

**Comment by alanrenmsft** [comment]
@kburtram  working on it now

**Comment by alanrenmsft** [comment]
@rjmholt I had to update the file names in your branch to the file namei get from the vscode marketplace

**Comment by alanrenmsft** [comment]
@rjmholt  this is now alive in ADS marketplace

**Pull request merged**
