### PR TITLE
fix loading icon not animated issue

### LINKED ISSUE #15395: Loading Spinner Isn't Animated
(on Mac)
Example: clicking "Refresh" on the Databases page in the server dashboard. Loading spinner is static and doesn't have any animation:

image

In April (and before), we saw the spinner animate:
image

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #15395 

the issue only happens for packaged builds, dev environment works fine. At build time, when bundling the css files, the build process will convert the SVG files to inline SVGs(data url), I compared the generated data urls and noticed the elements that controls the animation: keyframes is missing in the insider/rc1 builds, see screenshot below, the 1st line is from previous stable release, and the 2nd line is latest insider/rc1.

image

I will further investigate the bundling process, for now I am using the generated base64 string for the SVGs to workaround the issue.

I have queued a build to verify my changes: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104071&view=results

### CODE REVIEW

**Review by abist — APPROVED** [review]

**Comment by alanrenmsft** [comment]
I am checking the other places that are using animated svgs now

**Review by Charles-Gagnon — APPROVED** [review]
@lucyzhang929 This seems like it's related to the viewbox issue you found as well. Do you recall seeing anything about animations being stripped out in your research?

@alanrenmsft I don't know if this is a good long-term solution, would you agree? I tracked down the viewbox issue with that being stripped out to https://github.com/microsoft/azuredatastudio/blob/main/build/lib/optimize.ts so I'm going to guess the same thing is happening here. 

Anyways as a quick fix this is fine, but we should try to find a better way to fix this. Looking at how VS has their loading icons would be a good start I think.

**Comment by chlafreniere** [comment]
@Charles-Gagnon @alanrenmsft is there a way for us to detect if similar viewbox-related issues exist (but we just haven't found them yet)? Any well-crafted search queries that we should be using for detection?

**Comment by Charles-Gagnon** [comment]
The easiest way would be if we could somehow modify the cssnano stuff to output the files it changes and get the full list that way. I can look into doing that a little later today.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon , yeah, as i mentioned in the PR description this is not a long term solution doing this because May release is really close, I will further investigate the build process and figure out why, I did look into the build/lib/standalone.ts that is doing the replacement of svg files, but that one seems to be fine, there must be something else later one changes the content.

I found a few more places using the same loading svg and replaced those with base64 encoded svgs.

**Comment by alanrenmsft** [comment]
oh man, the history is messed up again.

**Comment by lucyzhang929** [comment]
It might also be caused by the new svgo package version: https://github.com/svg/svgo/issues/888

**Comment by alanrenmsft** [comment]
tested with packaged version, it still doesn't work even with base64 string of the svg, it has been modified during the bundling process, I will close the PR and investigate.

**Pull request closed without merging**
