### PR TITLE
ok button fix

### PR DESCRIPTION
**Pull request by aaomidi**
Issue #9079 

I'm not sure if I like this change because it changes stuff under the vscode path.

### CODE REVIEW

**Comment by anthonydresser** [comment]
Whats the reason for readding this? other than to maintain the same feature? I think vscode's point here is valid; allowing the extensions to configure this creates an inconsistent experience for the user.

**Comment by aaomidi** [comment]
Well the current experience is pretty terrible. The behavior is not well thought out, try out the azure subscription filter without this and you might notice.

If we don't want it then that's fine too.

**Comment by anthonydresser** [comment]
If it creates an accessibility issue to not have this, then we should just make it always there, rather than modifying the apis to make it optional.

**Comment by kburtram** [comment]
I'm fine with making the OK button there always.  Is there any scenarios were that wouldn't make sense for us?

**Comment by aaomidi** [comment]
It seems its there by default now...

**Comment by aaomidi** [comment]
I'm going to close this as it seems the ok button is back.

**Pull request closed without merging**
