### PR TITLE
snap package

### PR DESCRIPTION
**Pull request by mikeroyal**
Includes a wrapper script and snapcraft.yaml  to build snap. I'm still running tests and will make some updates along the way.

### CODE REVIEW

**Comment by kburtram** [comment]
@mikeroyal thanks for opening this PR.  Based on Microsoft policy all contributors are required to sign a [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/azuredatastudio?pullRequest=5589) before we can merge.  Please see the previous bot comment for additional context.  Thanks!

**Comment by alanrenmsft** [comment]
@mikeroyal it has been a while, do you still want to merge the PR?

**Comment by mikeroyal** [comment]
hi @alanrenmsft, I'm interested I just never heard back from everyone after the previous comment. Also, I would need to make some updates for the snap to work probably for the latest Ubuntu 20.04 LTS. Right now the Ubuntu 20.04.1 is scheduled for August 13th, which is when Ubuntu 18.04 LTS users will be prompted to upgrade to the 20.04 LTS release.

**Comment by kburtram** [comment]
Thanks for this proposed contribution!  We don't have plans to add a Ubuntu snap package in the near future, so cleaning up older PRs.  We may reactivate in the future if we plan to introduce this deployment option.

**Pull request closed without merging**
