### PR TITLE
Added August langpacks to stable gallery

### PR DESCRIPTION
**Pull request by smartguest**
This PR will add the August langpacks to the stable branch

Branch to get the langpacks from: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114847&view=results

### CODE REVIEW

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
Please update the other properties - same as https://github.com/microsoft/azuredatastudio/pull/16725

**Comment by smartguest** [comment]
Whoops, sorry about not changing the version or dates, I missed them when using pattern searches.

**Comment by smartguest** [comment]
@Charles-Gagnon Fields have been fixed, its good to merge in.

**Comment by smartguest** [comment]
@v-srinisa @chayaverma7 Can you please merge this PR into the extensions/rc branch? It will add the localization for this month's release of ADS.

**Comment by v-srinisa** [comment]
Gallery updated

**Pull request merged**
