### PR TITLE
Update to extensions gallery json with upcoming language pack update

### PR DESCRIPTION
**Pull request by smartguest**

### CODE REVIEW

**Review by kburtram — COMMENTED** [review]
The paths for the BLOBs (at least https://sqlopsextensions.blob.core.windows.net/extensions/langpacks/1.26.0/ads-language-pack-de-1.26.0.vsix) didn't resolve to a file on the BLOB storage.  We should have the VSIX files staged prior to updating the gallery file.

**Comment by smartguest** [comment]
I uploaded the Vsix files to the BLOB storage, I'm not sure if there are any further steps that I needed to do before that, but the BLOB paths should work now.  @kburtram

**Comment by Charles-Gagnon** [comment]
Where did you get these VSIXs from? We should only be uploading VSIXs that come from an official product build pipeline (and per our new release process, from a release branch specifically for stable extension updates)

**Comment by smartguest** [comment]
They were generated by me @Charles-Gagnon but I'll remove those from the SQL blob storage right now, the update extension gallery process readme document is very vague and does not at all mention how to do this.

**Comment by Charles-Gagnon** [comment]
Thanks. Do we have the process for building and updating these langpack extensions documented anywhere? That would be great to have so that we don't have to rely on people already knowing what to do to update these. 

Alan Ren is working on updating the extension release process docs - I'll work with him to make sure that it's clear where the VSIX's come from.

**Comment by smartguest** [comment]
@Charles-Gagnon The language pack has been merged in and the vsix files have been uploaded to the blob storage. On the insiders build, attempting to access any language pack results in an XHR error, I'm wondering if the gallery files need to be updated to fix this error, the vsix packages work on their own.

**Comment by Charles-Gagnon** [comment]
Yeah, so this broke with your latest changes because you modified the langpack paths. The galleries are pointing to resource URLs such as https://raw.githubusercontent.com/microsoft/azuredatastudio/main/i18n/language-pack-es/languagepack.png which no longer exist.

So we have a couple ways to fix this : 

1. Just update the current gallery files with the new paths (leave them pointing at the 1.9.0 versions)
2. Finish this PR and publish the updated galleries with the new 1.26.0 versions

#2 would be best if those are ready to go, but I still am wondering where you got those VSIXs from since AFAIK none of our pipelines generate the langpack VSIXs

**Comment by Charles-Gagnon** [comment]
In case you didn't see my other PR I pushed a fix for the galleries to fix the broken links while we discuss the new version of the extensions.

**Comment by smartguest** [comment]
@Charles-Gagnon They were generated locally using VSCE package directly and were approved to be merged in. Also the gallery files are ready to go (fixed the conflicts).

**Pull request merged**
