### PR TITLE
Revert "Add CodeQL Analysis workflow"

### PR DESCRIPTION
**Pull request by aaomidi**
Reverts microsoft/azuredatastudio#10195

### CODE REVIEW

**Comment by aaomidi** [comment]
Accidentally had this merged to master.

**Comment by kburtram** [comment]
@aaomidi do we want to revert this?  It looks like the PR was good to go, according to contributor.  The check appears to be passing in recent PRs.

**Comment by aaomidi** [comment]
This merged to master, and since it was a third party PR i couldn't change the branch it was merging to @kburtram

**Comment by kburtram** [comment]
Closing stale PRs

**Pull request closed without merging**
