### PR TITLE
Change project build failure notification to be modal

### PR DESCRIPTION
**Pull request by kisantia**
This PR addresses https://github.com/microsoft/azuredatastudio/issues/22163. This changes the build error notification to be modal so that users using a screen reader will not miss it.
buildErrorModal

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Yeah, I just tested it with NVDA and it gets announced as `Error: <Error Text Here>`. So if this isn't happening for voiceover that seems like a bug with voiceover instead.

**Comment by kisantia** [comment]
So if I start voiceover and then left click somewhere inside ADS and then build, then the error gets announced:
buildErrorFocusInside

But if I start voiceover and go straight to right-clicking on the project node and select build, then the error doesn't get announced:
buildErrorFocusOutside

If someone was actually using voiceover to use ADS, I would expect the focus to be in ADS so they wouldn't be running into the error not getting announced like in the second case. I'll ask about this in the issue

**Review by alanrenmsft — APPROVED** [review]

**Comment by Benjin** [comment]
+1 to Charles' comments; I don't think a modal is the right way to handle this from a usability perspective.  Let's see what the accessibility team says.

**Comment by kisantia** [comment]
closing this PR since this looks like a bug for macOS Ventura, as discussed on the issue. Voiceover is announcing the error as expected on macOS Monterey 12.6.3

**Pull request closed without merging**
