### PR TITLE
Update to arc extension resources

### PR DESCRIPTION
**Pull request by smartguest**
Loc resources PR complementary to #16150

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
When just doing simple string updates like this feel free to just go ahead and merge the PR in once the checks pass - I don't think you should need to wait for signoffs in these scenarios.

**Review by abist — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Also, is there a way to have this done automatically when the sources are updated? It's going to be a bit of a pain to constantly have to have someone running the command to regenerate these XLF's every time a string changes.

**Comment by smartguest** [comment]
@Charles-Gagnon We either need to have a bot that runs this command every so often or maybe include the XLF generation as part of the watch process. Thanks for letting me know I can check these in if they're small enough.

**Comment by smartguest** [comment]
@Charles-Gagnon Additionally from my experiments: the xlf creation task is not compatible with watch, as that one does not produce a build. It has an error when it tries to run on out due to invalid files in it, therefore it can be added only as part of compile, which is required to be run once anyway.

**Comment by Charles-Gagnon** [comment]
A couple options to look in to is 

1. Running the task as part of the CI pipeline - and if there were any changed files then it would fail that step and tell the submitter the steps to regenerate the files themselves
2. Having a separate daily pipeline running that will run the task and open a PR with the changes automatically

I like 2 slightly more to avoid increasing extra work required by devs, and it shouldn't be too hard to set something like that up. You can look at the ads-merger bot (https://github.com/microsoft/ads-merger/blob/master/merger/src/merger.ts#L269) for an idea of how to do something like that, let me know if you have questions

**Pull request merged**
