### PR TITLE
Update Azure resource explorer section title

### PR DESCRIPTION
**Pull request by kburtram**
Fixes https://github.com/Microsoft/azuredatastudio/issues/4236.  

image

### CODE REVIEW

**Comment by anthonydresser** [comment]
I believe @yualan has ideas for the naming stuff.

**Comment by kburtram** [comment]
@yualan @anthonydresser sure, with tweaking the naming, but let's get these fit & finish issues workout as soon as possible so we can start evaluating the planned March experience.  I also don't think we should have the viewlet name showing as `Data Explorer`.  I'd prefer `Object Explorer` to that, but there could be an even better name.  The metapoint is let's not wait too long on getting these minor fixes into the product so we can remove the old Server and Azure viewlets.

**Comment by yualan** [comment]
Agreed, will work on closing this ASAP

**Comment by kburtram** [comment]
Merging now since `Azure` is an improvement.  Subsequent UI string changes can be done separately.

**Pull request merged**
