### PR TITLE
fix unstable tests

### PR DESCRIPTION
**Pull request by alanrenmsft**
1. fix the 'editor is not connected' error, the root cause is we were switching database context of the underlying connection, the fix is to use a new dedicated connection to the desired database. (leaving it as unstable due to new errors were discovered, @kisantia made changes in SQL Tools Service to fix the new issue). 
2. remove the unstable tag for the test cases that are passing consistently.

see the test runs
Screen Shot 2020-01-02 at 3 54 12 PM

### CODE REVIEW

**Comment by alanrenmsft** [comment]
I'll add a new commit tomorrow to bump up the STS version and test run results.

**Comment by udeeshagautam** [comment]
> I'll add a new commit tomorrow to bump up the STS version and test run results.

Thanks Alan! Hopefully after that dacpac test will be out of unstable too.

**Comment by alanrenmsft** [comment]
scheduled four test runs with the updated STS. lets see.

**Comment by alanrenmsft** [comment]
all four test builds passed, I will merge the PR now.

Screen Shot 2020-01-03 at 2 27 36 PM

**Pull request merged**
