### PR TITLE
Refresh compiled extensions.js

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR is to fix an error that is appearing in the Hygiene check in PR builds.

### CODE REVIEW

**Comment by lewis-sanchez** [comment]
Waiting on checks to pass, but I believe this will fix the hygiene error.

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
You shouldn't delete this, it's needed since we don't compile the build folder in the pipelines to save build time. Just running yarn compile from the build folder should regenerate this with the latest changes, which should be enough...

**Review by Charles-Gagnon — APPROVED** [review]
Looks good, assuming the checks pass now.

**Comment by Charles-Gagnon** [comment]
Merging now since hygiene checks have passed...

**Pull request merged**
