### PR TITLE
fix/correct_error_ru_localization

### PR DESCRIPTION
**Pull request by mochaloff**
This PR fixes #

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@khoiph1 How should we handle fixes like this? Is this something that your translation team can review for accuracy? And then is merging it in to our repo enough or does something else need to be done to ensure things are updated on your side as well?

**Comment by Charles-Gagnon** [comment]
Can you work with @khoiph1 to get this updated then?

**Comment by smartguest** [comment]
@Charles-Gagnon Will do, let him know of the requested changes.

**Comment by mochaloff** [comment]
> Can you work with @khoiph1 to get this updated then?

no problem

**Comment by Charles-Gagnon** [comment]
@mochaloff We've sent this off to our localization team to review, if they give the OK then I'll get this merged in. Thank you for your contribution!

**Pull request merged**
