### PR TITLE
fix insight details dialog issue (#11309)

### PR DESCRIPTION
**Pull request by alanrenmsft**
fixes issue #11284 

port the fix to release branch. original PR: https://github.com/microsoft/azuredatastudio/pull/11309

### CODE REVIEW

**Comment by kburtram** [comment]
@alanrenmsft should we be worried about the CI build failures for this PR?

**Comment by udeeshagautam** [comment]
Can you please re run the checks?

**Comment by udeeshagautam** [comment]
Can you please re run the checks?

**Comment by alanrenmsft** [comment]
@kburtram @udeeshagautam  I am still waiting for this PR to be merged: https://github.com/microsoft/azuredatastudio/pull/11304, could you please merge it? after that i will rerun the tests for this PR.

**Pull request merged**
