### PR TITLE
open viewlet on showPreview

### LINKED ISSUE #10469: Opening the TSG book is not focusing the booksviewlet with the book
- Azure Data Studio Version:

Steps to Reproduce:

1. Launch command pallet and run the command "SQL Server 2019 Guide"

Expected outcome:
Open the Books viewlet with the TSG book focused and also opening the readme file of the book.

Actual outcome:
Just opens the read me file bit doesn't focus the books viewlet with book.

### PR DESCRIPTION
**Pull request by MaddyDev**
This PR fixes #10469

### CODE REVIEW

**Comment by corivera** [comment]
Have you verified that the book viewlet isn't capturing focus away from the servers viewlet with this change? There was a bug in the book code before where we were always stealing away focus from the servers viewlet if a folder was opened in the explorer viewlet.

**Comment by Charles-Gagnon** [comment]
To double check - and this still keeps the behavior that when you open ADS it won't always go to the Books viewlet? This was an issue that we fixed that when the books were loaded upon ADS starting they'd cause focus to switch to the viewlet and let's make sure we're not regressing back to that.

**Comment by Charles-Gagnon** [comment]
And Cory beat me by a couple seconds 😛

**Comment by MaddyDev** [comment]
> Have you verified that the book viewlet isn't capturing focus away from the servers viewlet with this change? There was a bug in the book code before where we were always stealing away focus from the servers viewlet if a books folder was opened in the explorer viewlet.

Yes I did! And it works, showPreview is only set when user triggers the openBook.

**Pull request merged**
