### PR TITLE
Upgrading nested dependency 'follow-redirects' to latest version 1.14.7

### PR DESCRIPTION
**Pull request by aasimkhan30**

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]

**Review by alanrenmsft — CHANGES_REQUESTED** [review]
you are updating the yarn.lock directly without modifying the package.json file, I don't think this is the right thing to do. if this is an indirect dependency, we should also update the package.json files.

**Comment by alanrenmsft** [comment]
please refer to this commit if you don't know how to do it: https://github.com/microsoft/azuredatastudio/commit/fc0d175f39d6bfc493fd5a200623a351588b5d7e

**Comment by Charles-Gagnon** [comment]
Updating yarn.lock directly isn't necessarily bad - dependabot does it all the time. Using the resolutions field is fine too but I personally don't see a huge reason to prefer one over the other.

**Comment by alanrenmsft** [comment]
to be more specific: 
image

**Comment by alanrenmsft** [comment]
@Charles-Gagnon I see, that sounds reasonable to me.

@aasimkhan30 I'd also take the chance to see whether the packages that introduced this dependency is actually being used.

**Comment by aasimkhan30** [comment]
@alanrenmsft and @Charles-Gagnon  since axios uses 
image
I just had to delete follow-redirects from yarn.lock and run yarn install. It automatically downloaded the latest version after that.

**Review by alanrenmsft — APPROVED** [review]

**Comment by aasimkhan30** [comment]
> @Charles-Gagnon I see, that sounds reasonable to me.
> 
> @aasimkhan30 I'd also take the chance to see whether the packages that introduced this dependency is actually being used.

@alanrenmsft we use axios almost everywhere to make rest calls.

**Pull request merged**
