### PR TITLE
Fixed Import Wizard

### PR DESCRIPTION
**Pull request by abist**
Fixed null ref that caused Import Wizard to fail

Fixes https://github.com/Microsoft/azuredatastudio/issues/2537

### CODE REVIEW

**Comment by kburtram** [comment]
@abist could you sync with @yualan regarding the similar issue with Profiler?  I'm not sure the problem, but he said it was related though I don't think your fix will address it.

**Comment by abist** [comment]
@kburtram I can successfully open Profiler using `Alt + P'. @yualan is that expected behavior?

**Comment by abist** [comment]
@kburtram Synced up with Alan offline. The issue with Profiler is different (Mac only), and will have a different fix. I'm going to go ahead and merge this and work on the other bug.

**Comment by yualan** [comment]
Thanks for investigating!

**Comment by DTronD** [comment]
For those who end up here as I did (via #2282 and #2537) after receiving the "command 'flatFileImport.start' not found" error when trying to launch the SQL Server Import extension via CTRL-I.....
This error appears if you try to launch prior to making ANY connection to a SQL Server.  E.g. immediately after launching ADS.  The error does NOT appear if you first open a new query/file with a connection and THEN hit CTRL-I.  After you have successfully launched the import wizard, any subsequent attempt to launch it (via CTRL-I) from an unconnected query/file will get the proper warning dialog telling you that your first need a connection.

**Pull request merged**
