### PR TITLE
Updating Import extension to 1.2.0 

### PR DESCRIPTION
**Pull request by aasimkhan30**
This PR fixes #

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
Does this required an updated azdata engine version?

Do you want this published now?

**Comment by aasimkhan30** [comment]
@Charles-Gagnon  I have checked the extension with the latest release (1.25.1) and it works. Do I need to do some additional checks?

**Comment by Charles-Gagnon** [comment]
I was more asking whether there's any changes in the extension that would require a newer version of core ADS in order to run properly. i.e. did you make any core changes in 1.25.1+ that are needed or can it run fine in 1.25 as well?

**Comment by aasimkhan30** [comment]
@Charles-Gagnon, nope, everything is contained in the extension. I do not require any new core changes.

**Comment by Charles-Gagnon** [comment]
Gallery files updated

**Pull request merged**
