### PR TITLE
Removing filter from table component set Data

### PR DESCRIPTION
**Pull request by aasimkhan30**
Issue: #19620

This PR remove the filter from table component as it is not needed anymore. The treeGrid component used by execution plan already has this filter.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
Please add description of why you're making this change (what was broken and why it isn't needed anymore) for historical context.

**Comment by alanrenmsft** [comment]
@aasimkhan30 you also need to call this in execution plan, right?

**Review by alanrenmsft — APPROVED** [review]
@aasimkhan30 explained to me during the meeting, this change is no longer needed by him.

**Comment by aasimkhan30** [comment]
@Charles-Gagnon , updated the description and linked the error.

**Review by smartguest — APPROVED** [review]
Edit Data is working again. Good to go!

**Pull request merged**
