### PR TITLE
Update Kusto to 0.5.4 for GA

### PR DESCRIPTION
**Pull request by JustinMDotNet**
Kusto extension 0.5.4 was built here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=102717&view=results

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@JustinMDotNet There's already a 0.5.4 uploaded from yesterday. If you need one that's different than that you need to bump up the version and use that instead. If that one is fine that's ok - I'm just making sure.

**Comment by JustinMDotNet** [comment]
> @JustinMDotNet There's already a 0.5.4 uploaded from yesterday. If you need one that's different than that you need to bump up the version and use that instead. If that one is fine that's ok - I'm just making sure.

That shouldn't be an issue. That may have happened because I originally generated the 0.5.4 build manually.

**Comment by alanrenmsft** [comment]
@JustinMDotNet 0.5.4 is there because I uploaded it, you create a PR to update the insider feed yesterday.

**Comment by alanrenmsft** [comment]
@JustinMDotNet just curious, what is going GA?

**Comment by alanrenmsft** [comment]
@JustinMDotNet gallery updated.

**Pull request merged**
