### PR TITLE
fix charting issue

### LINKED ISSUE #9071: legend position for chart is not working
Screen Shot 2020-02-06 at 12 02 21 PM

### PR DESCRIPTION
**Pull request by alanrenmsft**
debugged into the chart.js module and found out we need to set the chart.options instead of chart.config.options. it was changed by this PR: https://github.com/microsoft/azuredatastudio/pull/8217

The current typings reference doesn't have the options property exposed so I am upgrading both the package and the typing to the latest release.

Screen Shot 2020-02-07 at 2 56 08 PM

This PR fixes #9071

### CODE REVIEW

**Comment by chlafreniere** [comment]
Are there any side effects of upgrading the version of chart.js?

**Comment by anthonydresser** [comment]
#8319 didn't change any functional code, it only moved files around.

**Comment by alanrenmsft** [comment]
this is the PR that changed the graphInsights.ts: https://github.com/microsoft/azuredatastudio/pull/8217

**Comment by alanrenmsft** [comment]
> Are there any side effects of upgrading the version of chart.js?

to minimize the impact, i have upgraded only the typing definition to the latest release for the version we are using, and it has the property definition we need here.

**Pull request merged**
