### PR TITLE
Added option for separate tab

### PR DESCRIPTION
**Pull request by smartguest**
This PR adds in the requested separate tab feature similar to that of SSMS

This requires moving the functionality of the queryResultsEditor and the queryResultsView into the queryEditor itself to facilitate the layout generation more easily. 

Due to the nature of how editors are created in ADS along with the layout function call, its currently only possible to change the editor layout after a restart of ADS (noted on the setting).

This PR also adds the setting to automatically switch to the results tab after a query has been run (similar to SSMS) and this does not require a restart.

Screenshots posted below:
Default view (no query plan):
QueryDefaultScreen1

Default view (with query plan):
QueryDefaultScreen2

Separate tab view (no query plan):
QueryNewTabScreen1

Separate tab view (with query plan):
QueryNewTabScreen2

Settings page:
QuerySettingsScreen

This fixes: #4784

### CODE REVIEW

**Comment by smartguest** [comment]
@alanrenmsft Perhaps I should, although functionally it is complete.

**Comment by smartguest** [comment]
I need to fix the failing tests first before turning this into an actual PR

**Comment by kburtram** [comment]
@smartguest should we close out this older PR since I think it will still need a bit of work to get merged?  We can reopen later if we pick this back up.

**Comment by kburtram** [comment]
Closing older PR without recent activity.  Please reopen if working on this area again.

**Pull request closed without merging**
