### PR TITLE
check for jupyter-book versions and install 6.4

### LINKED ISSUE #11158: Get 'Error: no such option: --content-folder' when create book(Preview)
- Azure Data Studio Version:
1.19.0
Steps to Reproduce:

1. Create Book(Preview)
2. When Running 'Create a new book' Cell, after input the book name and content folder I will get such error.
error

### PR DESCRIPTION
**Pull request by MaddyDev**
jupyter-book released new version 7.1 which is not yet supported by us. Made changes on the create book to install the older version 0.6.4 that's currently supported by us.

I tested the below two scenarios with my changes:
1. Install the latest version of jupyter-book and tried running the book, it uninstalls the 7.1 and installs 6.4.
2. Uninstalled jupyter-book and tried running the book, it installs 6.4 and continues. 

My only current concern is, if the users have the latest version installed for their personal use and us uninstalling it. Should I add a prompt to user, that asks users permission to continue to uninstall the version they have? 

Update: Added a note:
MicrosoftTeams-image (1)

This PR fixes #11158

### CODE REVIEW

**Comment by chlafreniere** [comment]
We should make this explicit in the actual notebook (i.e. a markdown cell should make this clear that we will install the version that we support). Can you work with @yualan on the wording?

**Comment by corivera** [comment]
Why do we not support the latest version? If anything, we should try to support that instead of adding extra version checks. We definitely shouldn't uninstall a python package without prompting for it. The packages could be used by other applications that require a minimum version higher than what we support.

**Comment by MaddyDev** [comment]
> Why do we not support the latest version? If anything, we should try to support that instead of adding extra version checks. We definitely shouldn't uninstall a python package without prompting for it. The jupyter-book package could be used by other applications that require a minimum version higher than what we support.

I agree. We'll definitely work on this for next release. Given the code freeze time for this release, I don't want to have a broken experience for create-book for new users.

**Comment by chlafreniere** [comment]
@corivera In jupyter-book 0.7.0+ the folder structure is different; it was recently released within the past month or two, and we haven't added support for that... Yet.

Given that we ship Jupyter Books all using the older version, there's work to ensure that we support both the old + new versions of the format.

**Comment by corivera** [comment]
Makes sense.

**Comment by yualan** [comment]
Jupyters Books in Azure Data Studio only support jupyter-book versions <= 0.6.4 To create a Jupyter Book, we will be uninstalling versions newer than 0.6.4 and replacing with 0.6.4

**Pull request merged**
