### PR TITLE
switch back to the original azure tree with account/subscription structure

### PR DESCRIPTION
**Pull request by alanrenmsft**
image

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
What's the purpose of this? Is this going to allow expanding the azure nodes in the Connection Dialog down to the object level (tables/views/etc)?

**Comment by alanrenmsft** [comment]
@Charles-Gagnon , not really, if you try the current azure view, it is no longer doing in place expansion anymore, @abist might have more context here, I remembered that was a decision we made a while ago. it will show the connectable resources and then you can connect and view it in OE

**Comment by abist** [comment]
@alanrenmsft I'm not sure what the task here is, I never worked in this area, however, I remember Karl bringing this up one time in shiproom, so maybe he can clarify.

**Comment by Charles-Gagnon** [comment]
What do you mean "in place expansion"?

And I'm still not understanding what exactly this PR is changing - what's the experience going to look like now?

**Pull request closed without merging**
