### PR TITLE
Changed the default value

### PR DESCRIPTION
**Pull request by najmieh**
This PR fixes #59952

### CODE REVIEW

**Comment by najmieh** [comment]
The [documents](https://github.com/microsoft/vscode-docs/blob/50927f044eee843a5cba9c939bfa0122028299dc/docs/getstarted/settings.md) for this may need a change as well

**Comment by Charles-Gagnon** [comment]
@najmieh Could you provide some context here? The issue you linked appears to be something in VS Code - this repo is for Azure Data Studio which, while a fork of VS Code, is a separate product and typically changes here don't flow back to VS Code. Did you mean to make the change in their repo instead?

**Comment by najmieh** [comment]
I only could find within this file, The relevant default value for this 	"workbench.tips.enabled": false

I make the necessary changes in other file. Please tell me how to do that.

**Comment by Charles-Gagnon** [comment]
The VS Code file is here : https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/watermark/browser/watermark.ts#L213

I'm going to close this since I don't currently see us taking this change without more context, if you think this belongs in this repo please add a description of the change and why you're making it in the description of the PR so we can accurately review it.

**Comment by najmieh** [comment]
Ok, thank you for the feedback.

**Pull request closed without merging**
