### PR TITLE
SQL Migration Targets Page

### PR DESCRIPTION
**Pull request by cssuh**
Finished the Migration Targets page - Assessment page is still a work in progress
Screen Shot 2021-01-20 at 2 40 58 AM

Screen Shot 2021-01-20 at 2 41 07 AM

### CODE REVIEW

**Comment by aasimkhan30** [comment]
@cssuh  can just create a separate PR for the targets page to be merged?

**Comment by kburtram** [comment]
@cssuh agree with @aasimkhan30.  Let's please create focused PRs on each page/functionality so we can review and merge quickly.  Thanks!

**Comment by cssuh** [comment]
sure I will do that

**Comment by cssuh** [comment]
This has been split into #14415 and #14421

**Pull request closed without merging**
