### PR TITLE
Adding aria role to hyperlink cell in slickgrid

### PR DESCRIPTION
**Pull request by aasimkhan30**
Issue: #20632

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
What does it mean when they said it was previously announced as a "group"? Shouldn't it have been announced as a link?

**Comment by aasimkhan30** [comment]
> What does it mean when they said it was previously announced as a "group"? Shouldn't it have been announced as a link?
For some reason, screen readers were reading those cells as group

**Comment by aasimkhan30** [comment]
The focus was not on the link but on the cell div and that's why it was reading it as a group.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
So how does this fix it then? Does the cell see the role for the hyperlink and use that then?

**Review by Charles-Gagnon — APPROVED** [review]
Does that mean it'll

**Pull request merged**
