### PR TITLE
Bumped kusto extension version to 0.5.1

### PR DESCRIPTION
**Pull request by JustinMDotNet**
This PR fixes #

### CODE REVIEW

**Comment by alanrenmsft** [comment]
where is the new vsix file?

**Comment by alanrenmsft** [comment]
looks like you the version 0.5.1 of kusto doesn't exist now.
image

please read the instructions here: https://github.com/microsoft/azuredatastudio-docs/blob/main/Guides/UpdateExtensionGallery.md#guide-for-extension-authors

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@Charles-Gagnon are you going to merge and publish?

**Comment by Charles-Gagnon** [comment]
Yup, doing that now

**Comment by Charles-Gagnon** [comment]
@JustinMDotNet Gallery updated!

**Pull request merged**
