### PR TITLE
Oct release extension gallery update

### PR DESCRIPTION
**Pull request by abist**
Updating 
- [x] Import
- [x] ML
- [x] Schema Compare
- [x] Kusto - will be updated by @gupta1 
- [x] SQL Assessment
- [x] Database Projects
- [x] Azure Arc
- [x] azdata

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Review by llali — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
FYI - I'll be updating the arc and azdata extensions as well. So if you could hold off merging this in and just use it as a single "release update PR" that we merge in once we release that'd be best I think

**Comment by abist** [comment]
@Charles-Gagnon That's the plan, and that's why I added you to the review

**Comment by alanrenmsft** [comment]
renamed the PR to make it more clear :)

**Review by aasimkhan30 — APPROVED** [review]

**Review by kburtram — APPROVED** [review]

**Review by udeeshagautam — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@abist FYI the datavirt update isn't needed - I had already updated it on the 1st when we pulled in the Prose fix

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by abist** [comment]
Ready to be merged @Charles-Gagnon @alanrenmsft @kburtram

**Comment by alanrenmsft** [comment]
go ahead! thanks

**Comment by abist** [comment]
@alanrenmsft I can't that's why I tagged lol

**Pull request merged**
