### PR TITLE
Increased the chartjs version to latest 2.9.4

### PR DESCRIPTION
**Pull request by rajeshka**
This PR fixes #

### CODE REVIEW

**Comment by alanrenmsft** [comment]
I am not sure what do you mean by testing? if you just want to test the changes you can run them locally, do you actually want to merge this PR?

**Comment by rajeshka** [comment]
> I am not sure what do you mean by testing? if you just want to test the changes you can run them locally, do you actually want to merge this PR?

I wanted to see what are the implications of updating to new version. Also I have a build done to do some testing. Merging this would depend on our collective decision.

**Comment by Charles-Gagnon** [comment]
You can just queue builds against specific branches directly (using the ad-hoc definitions) - no need to open PRs if you're just wanting to run your own local testing.

**Comment by Charles-Gagnon** [comment]
And at the very least if you're just wanting early feedback then I'd suggest using the draft PR functionality for that - opening a PR (and assigning reviewers) implies you want to actually merge this into main which sounds like it isn't the case.

**Review by kburtram — APPROVED** [review]
Seems fine to bump the minor version of this package assuming all the testing passed validation.  Though please wait for @alanrenmsft to sign-off prior to merging.

BTW, did you locate any changes between version 2.6.0 and 2.9.4 that help enable any of the Kusto render functionality you're planning to add?  If so it would be useful to note those features in the PR to provide context on why we want to bump this dependency specifically (since you're not also going through and updating all our other "out of date" dependencies).

**Comment by rajeshka** [comment]
> Seems fine to bump the minor version of this package assuming all the testing passed validation. Though please wait for @alanrenmsft to sign-off prior to merging.
> 
> BTW, did you locate any changes between version 2.6.0 and 2.9.4 that help enable any of the Kusto render functionality you're planning to add? If so it would be useful to note those features in the PR to provide context on why we want to bump this dependency specifically (since you're not also going through and updating all our other "out of date" dependencies).

I wanted to make sure that the minor version bump did not cause any regressions. I can work on updating all the other "out of date" dependencies in a separate PR. 

There were so many changes between 2.6.0 and 2.9.4 I found it prudent to version bump this so as to baseline this for our visualization config development.  

I'll sync with @alanrenmsft  and merge this if everything looks good.

**Comment by kburtram** [comment]
@rajeshka thanks!  sounds reasonable to me.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
I grabbed the build you scheduled and I don't see anything obviously wrong.

**Comment by alanrenmsft** [comment]
image

this is the only warning I saw related to chartjs.

**Pull request merged**
