### PR TITLE
Change server group look

### PR DESCRIPTION
**Pull request by abist**
Fixes https://github.com/microsoft/azuredatastudio/issues/12959

Changes the new server group look based on the review. This is just for server group and fixing the accessibility issue. The changing of colors in the dialog will be done separately in another PR.

Screen Shot 2020-12-01 at 3 40 07 PM

Changes -
- [x] Decreased height of server group row to match the server rows
- [x] Truncate width from sides for server group to show highlight/selection
- [x] Remove custom collapse/expand icons for groups and use default ones like the server ones.

Follow up:
Do we want to show an expand arrow for empty groups? Current behavior doesn't show any expand arrow for an empty group, however vscode shows one for empty folders. 

Screen Shot 2020-12-01 at 3 40 39 PM

### CODE REVIEW

**Comment by alanrenmsft** [comment]
please link the accessibility issue here and also, I don't see a screenshot shows the focus rectangle, please add one.

**Comment by alanrenmsft** [comment]
@abist can you try give 2px of vertical  padding?

**Comment by abist** [comment]
Screen Shot 2020-12-01 at 4 23 57 PM

Change with padding-top 2px

**Comment by abist** [comment]
With padding -

Screen Shot 2020-12-01 at 4 27 11 PM

Screen Shot 2020-12-01 at 4 27 50 PM

**Review by Charles-Gagnon — APPROVED** [review]
I agree that having the arrows show all the time would be my preference

**Comment by alanrenmsft** [comment]
@abist you are still working on this to align with the mockup, right?
image

**Comment by abist** [comment]
@alanrenmsft Yeah, that's why I haven't merged yet

**Comment by abist** [comment]
Updated look -

Screen Shot 2020-12-07 at 12 23 21 PM
Screen Shot 2020-12-07 at 12 23 30 PM
Screen Shot 2020-12-07 at 12 23 42 PM

**Comment by alanrenmsft** [comment]
@abist definitely better now. I noticed that the expand/collapse icon is no longer vertically center aligned, could you please fix that?

**Comment by abist** [comment]
@alanrenmsft after arrow alignment

Screen Shot 2020-12-08 at 12 26 09 PM

**Comment by alanrenmsft** [comment]
I applied the changes locally to try it out, it seems we are not handling the text overflow properly.

image

**Comment by alanrenmsft** [comment]
also, @Charles-Gagnon started the work of using the new async tree, looks like it is using a different renderer, do you mind taking a look at it too? you need to enable the feature flag. it should be a minor change. if not you can ignore it.
image

**Comment by alanrenmsft** [comment]
also, as we just discussed, please make sure the right edge aligns with connection nodes
image

**Comment by abist** [comment]
Latest change -

Screen Shot 2020-12-08 at 2 42 46 PM

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
