### PR TITLE
Update MacOS icon

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
This fixes the spacing issue that made the icon appear lower in the task bar than other icons.

(Stable icon not updated for comparison)

image

### CODE REVIEW

**Comment by alanrenmsft** [comment]
why do we need to update the distro id here?

**Comment by Charles-Gagnon** [comment]
The non-insiders icons all come from the distro repo and are merged in during the build step

**Review by kburtram — APPROVED** [review]
Neither icon really looks "better" to me, so I guess this is fine either way then.

**Comment by Charles-Gagnon** [comment]
The insiders one is aligned with the rest of the docked icons along the top and bottom - that's the only change. The current icons all extend a bit above and below the other icons so look out of place.

**Pull request merged**
