### PR TITLE
Append stdErr log to error message when a streamed console command fails.

### PR DESCRIPTION
**Pull request by corivera**
Currently streamed commands only return the process exit code on error, which is rarely helpful for debugging. This change appends the accumulated stdErr log to the end of the message, similar to how we report console errors during jupyter server startup.

### CODE REVIEW

**Comment by aaomidi** [comment]
@chlafreniere That test failed again, should we move it to unstable?

**Comment by chlafreniere** [comment]
@aaomidi yes we should

**Comment by corivera** [comment]
Seems like the failure only happens on my branch. Looking into it.

**Comment by aaomidi** [comment]
Running a new test here: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=42935&view=logs&j=d46bdafb-39a9-561e-f56f-8f45577d0334

**Comment by chlafreniere** [comment]
Regardless, the test has been failing ~3% of the time recently, something like that. we'll need to investigate why data isn't getting propogated when expected through the extensibility APIs.

**Pull request merged**
