### PR TITLE
Name added for more info link in Assessment Dialog - accessibility

### LINKED ISSUE #15739: A11y_AzureDataStudioSQLMigration_MigratetoAzureSQL_MigrationAssessment_DevTool:There is no name defined for the more info link.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AZUREDATASTUDIOSQLMigration_June2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG4.1.2;#AINotInScope;#DevTool

### Environment Details:
Application Name: SQL Azure Data Studio
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure SQL Migration.
2. Connect to any sql server.
3. Tab till Azure SQL migration Tab and press enter.
4. Tab till Migrate to azure sql and press enter.
5. Add azure account and tab till next button and press enter.
6. Select SQL server on azure virtual machine radio button and tab till view/select button and press enter.
7. Tab till more info link.
8. Open Devtool using ctrl+shift+I and hover over to the link.

### Actual:
There is no name defined for the more info link.

### Expected:
There should be a name more info defined for the link.

### User Impact:
Screen Reader users will not be able to know the purpose of link.

### PR DESCRIPTION
**Pull request by goyal-anjali**
This PR fixes #15739

### CODE REVIEW

**Comment by goyal-anjali** [comment]
Before:
image

After:
image

**Comment by Charles-Gagnon** [comment]
Normally the aria name and the text displayed should be similar- this one appears to be `SQL Server Agent...`, is there a reason you're just using `More Info` as the aria label here?

**Comment by Charles-Gagnon** [comment]
Also FYI - for fixing multiple issues you have to put the closing tag before each issue, e.g.

```
fixes #15739
fixes #15739
```

**Comment by goyal-anjali** [comment]
> Normally the aria name and the text displayed should be similar- this one appears to be `SQL Server Agent...`, is there a reason you're just using `More Info` as the aria label here?

image
The bug description(#15739) expected a 'More Info' name defined for the screen reader users

**Comment by Charles-Gagnon** [comment]
The bugs generally are made to be generic, not necessarily to be followed to the letter. The idea here is that all links should have name attributes that tell a user using a screen reader what the link is so they know what they're clicking. And when there's text for a link you should almost always use that text as the aria-label as well, because we want both users reading the text and users using a screen reader to have the same impression of what clicking the link will do. 

Can you show a screenshot of what this link looks like in the UI now? You're not evening assigning a label here where you're creating it so I'm a little confused how it's getting the `SQL Server Agent...` text currently

**Review by brian-harris — APPROVED** [review]

**Comment by goyal-anjali** [comment]
@Charles-Gagnon If that's the case, then #15739  is unnecessary because the full name labels were already there. I assumed aria-label for 'More Info' was required which wasn't at all present in the code for this anchor element.

**Comment by Charles-Gagnon** [comment]
I agree that seems weird - which would imply to me that maybe this isn't the right link they're talking about. Could you please attach a screenshot of the entire page you're looking at?

**Comment by goyal-anjali** [comment]
> I agree that seems weird - which would imply to me that maybe this isn't the right link they're talking about. Could you please attach a screenshot of the entire page you're looking at?

image

**Comment by Charles-Gagnon** [comment]
Yeah there's something not right here. The issue itself says 

`There is no name defined for the more info link.` but that's not true if this is indeed the correct link as your screenshot clearly shows.

You're sure that this is the correct page based on their instructions? @aasimkhan30 @brian-harris can you confirm that this seems like the correct page?

If it does seem correct then I would suggest pinging them on the issue and getting clarification, attaching a screenshot showing the name field being populated. They've gotten things wrong before so it's possible this is another instance of that.

**Pull request merged**
