### PR TITLE
Adding azure resource provider for mysql flexible server

### PR DESCRIPTION
**Pull request by rishky-msft**
This PR fixes #
mysql_azure_flex_tab_final_new

### CODE REVIEW

**Comment by cheenamalhotra** [comment]
@rishky-msft 

I just created a MySQL Server and was hoping to login with user/password.. 
On Clicking "Connect" in context menu, I get this error:

image

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Is this something you're working with them on? I assume this is "intended" in that the MySQL provider will be added later, but this clearly shows a gap in our tree view. Ideally we shouldn't be showing the connect/manage option for nodes that the correct provider isn't installed for.

**Comment by Charles-Gagnon** [comment]
I made a separate issue to track that - it's currently broken for any of the nodes which don't have a provider built in (such as PG) 

https://github.com/microsoft/azuredatastudio/issues/20533

**Comment by alanrenmsft** [comment]
@Charles-Gagnon yes, I am working with mysql team and this PR is intended.

**Comment by alanrenmsft** [comment]
@cheenamalhotra @Charles-Gagnon I've fixed the similar issue for the browse feature in connection dialog and missed this one. I will copy the behavior for this scenario.

**Comment by alanrenmsft** [comment]
FYI, this is the PR I was referring to: https://github.com/microsoft/azuredatastudio/pull/19377

**Pull request merged**
