### PR TITLE
update the tslint rule to use tabs

### PR DESCRIPTION
**Pull request by alanrenmsft**
update the extension's tslint rule to match the ads rule and format the json file. missed this in my previous PR.

### CODE REVIEW

**Comment by aaomidi** [comment]
Why was the yarn.lock file changed?

**Comment by alanrenmsft** [comment]
> Why was the yarn.lock file changed?

do you happen to see this PR or you have sort of alert set up when yarn.lock is updated?

I converted this to use yarn over the weekend, I didn't actually spend time looking into the differences.

Do you see anything abnormal?

**Comment by aaomidi** [comment]
It's just I didn't notice anything that would trigger a yarn.lock change so I just wanted to make sure nothing broke :)

**Comment by alanrenmsft** [comment]
I think it is related to the way we have the version requirement written, if there are version update on npm side, the yarn.lock will change. just my guess.

**Pull request merged**
