### PR TITLE
extend the ListDatabasesRequest to allow more information to be returned

### PR DESCRIPTION
**Pull request by alanrenmsft**
in order to implement #10185, I need to make the following changes:
1. extend the ListDatabasesRequest related interfaces in azdata.d.ts in ADS repo
1. update the dataprotocol-client repo to handle the extended ListDatabaseRequest and response properly - depends on step NO.1
1. update SqlToolsService to implement extended ListDatabasesRequest handler
1. update ADS repo to implement the UI changes. depends on all steps above

this change is step 1.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
> Why not just use getDatabaseInfo? https://github.com/microsoft/azuredatastudio/blob/master/src/sql/azdata.d.ts#L1330

the getDatabaseInfo is database level, there needs to be 1(list databases)+x(x is the number of databases) separate queries.

**Comment by Charles-Gagnon** [comment]
Why is that necessary? You said this is for improving the database dashboard right? You can only view those one at a time so why do you need to fetch all database details at once?

And in general I'd rather see something like overloading getDatabaseInfo to take in multiple databases (or even just adding a new method) instead of modifying listDatabases - that seems a lot clearer and has less risk for breaking existing behavior.

**Comment by alanrenmsft** [comment]
this is to improve the databases widget in server dashboard, previously it is only get the list of database names, now I am extending it to return more information, in the meantime the backward compatibility is maintained without extra API calling.

**Comment by Charles-Gagnon** [comment]
Gotcha.

Do you have a screenshot of the mockup? 

In general that seems fine but I still think that it'd be better to either create  a new method or extending getDatabaseInfo. And regardless they should be returning the same format I think so we're consistent with our APIs. Having completely separate functions that are basically doing the same thing except for how many databases are being returned doesn't seem like the best behavior consistency wise.

**Comment by alanrenmsft** [comment]
Screen Shot 2020-04-28 at 10 21 31 AM

**Comment by alanrenmsft** [comment]
sigh, the databaseInfo interface is defined like this, not sure why is there a options object in it, it would more natural if the interface itself is the property container.
```
	export interface DatabaseInfo {
		options: {};
	}
```

**Comment by Charles-Gagnon** [comment]
I seem to recall this being something that came up a while back - @aaomidi wasn't this something you were playing with? I know we had issues with using a map since that didn't go across the JSONRPC boundary nicely but I'm not sure why we kept the options as its own property.

**Comment by alanrenmsft** [comment]
I have tested the changes I made, and didn't notice any issue. I guess I can go with it to reuse the interface, nothing wrong with it, just not perfect.

**Comment by aaomidi** [comment]
@Charles-Gagnon No that should work and we should fix that api point to actually have the information we expect.

**Comment by aaomidi** [comment]
@Charles-Gagnon Looking at the API when I see `[key: string]: string` That means i have no idea what the data returned from that API call would be until runtime.

Is this what we want to have or do we want to have the fields explictly written out.

image

I don't know what these potential keys are going to be in this situation.

**Comment by Charles-Gagnon** [comment]
The problem is this is meant to be generic across multiple server types so the options aren't going to be anything consistent.

**Comment by aaomidi** [comment]
I mean I'd be fine with that if we had specific ConnectionInfo types that extend/implement that interface :D

**Pull request merged**
