### PR TITLE
Cleanup the copy output (#8072)

### PR DESCRIPTION
**Pull request by kburtram**
* Cleanup the copy output

* Use helper functions and cleanup promise handling

This PR fixes #

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Is this fixing a bug? Or just general cleanup?

**Comment by Charles-Gagnon** [comment]
Oh this is the port for the hotfix. Got it.

**Comment by Charles-Gagnon** [comment]
@anthonydresser  Looks like the merge distro task is failing. Is that expected?

**Comment by anthonydresser** [comment]
Yes, this doesn't have the latest changes to the pipeline from master

**Pull request merged**
