### PR TITLE
Merge from vscode a9b7cb4ee1caac9a9ac1467848017b4cd9765d9e

### PR DESCRIPTION
**Pull request by anthonydresser**
https://github.com/microsoft/vscode/commit/a9b7cb4ee1caac9a9ac1467848017b4cd9765d9e (vscode/release/1.43) Merge pull request https://www.github.com/microsoft/vscode/issues/92468 from microsoft/aeschli/92318

### CODE REVIEW

**Comment by aaomidi** [comment]
The label Approved is required for using this command.

**Comment by kburtram** [comment]
@aaomidi do I need to re-add merge to trigger that again?

**Comment by aaomidi** [comment]
Yeah!

**Comment by aaomidi** [comment]
Merging PR based on approval from @kburtram

**Pull request merged**
