### PR TITLE
remove preview flag for import extension

### LINKED ISSUE #20498: Import extension is marked Preview in Extension Manager even though it is GA status
- Azure Data Studio Version: 1.39.0

Steps to Reproduce:

1. Open Import extension in Extension Manager

Expected: No Preview label

Actual: Preview label

image

### LINKED ISSUE #20998: import wizard will not active on macos M1
Issue Type: <b>Bug</b>

After installing the import wizard extension on the insiders for M1, it will not activate citing an incompatible platform

image

Extension version: 1.5.0
Azure Data Studio version: azuredatastudio-insiders 1.40.0-insider (d5cf088ba7b794859438fd2c1902249fd1e6a947, 2022-10-26T05:48:43.511Z)
OS version: Darwin arm64 22.1.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #20498
This PR fixes #20998 

I will remove the preview flag from extension's package.json in a separate PR.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@corivera @Charles-Gagnon 
image
any context on this error?

**Comment by Charles-Gagnon** [comment]
☹️ https://github.com/dotnet/interactive/pull/2403/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=

Was deleted. 

Mind updating it to https://raw.githubusercontent.com/dotnet/interactive/main/src/dotnet-interactive-vscode/images/icon.png for now?

**Comment by alanrenmsft** [comment]
thanks! will do. @Charles-Gagnon

**Comment by alanrenmsft** [comment]
well, looks like I have to fix the extension package first.

**Review by aasimkhan30 — APPROVED** [review]

**Comment by alanrenmsft** [comment]
currently, I can only produce the vsix locally, @aasimkhan30 has verified that it was working as expected.

**Pull request merged**
