### PR TITLE
Remove button styling on filter

### PR DESCRIPTION
**Pull request by abist**
Fixes https://github.com/Microsoft/azuredatastudio/issues/5358

### CODE REVIEW

**Comment by abist** [comment]
@anthonydresser Not sure what you mean there. I checked and the theming was working. Am I missing something?

**Comment by anthonydresser** [comment]
Previously you added button stylers in the headerfilter code 
https://github.com/Microsoft/azuredatastudio/commit/e870a309c0bdec9acfeb15cbbc6a3ffaa9478106#diff-f2838866a9f0bd6a2093b0469af7047fR212
presumably because there was something about them that wasn't natively theme aware. I'm not familiar with that ui so I can't tell you why, but those buttons generally need to have a styler attached.

**Comment by abist** [comment]
@anthonydresser Is there a reason we removed that? What's the alternative to it then? Also, does https://github.com/Microsoft/azuredatastudio/blob/master/src/sql/base/browser/ui/table/plugins/headerFilter.plugin.ts#L240 take care of it?

**Comment by anthonydresser** [comment]
**/base/** shouldn't access anything other than **/base/**. In order to attach the button stylers directly in the header filter you would need to import **/platform/** which would break that rule. styling the buttons as part of the header filter style function would fix it (assuming the attach button styler is called on the header filter) but the problem is that when you create header filter class the actual buttons haven't been created yet, causing an undefined access error.

**Comment by abist** [comment]
@anthonydresser I don't see those issues on dev. Do those issues show up when packaged?

**Comment by anthonydresser** [comment]
I'm assuming the bug references here is a null ref exception

**Comment by abist** [comment]
Updated fix here - https://github.com/Microsoft/azuredatastudio/pull/5380

**Pull request closed without merging**
