### PR TITLE
Set role to button for the wizard step links.

### PR DESCRIPTION
**Pull request by nahk-ivanov**
Fixes https://github.com/microsoft/azuredatastudio/issues/17670

Our extension is relying on the wizard dialog. During accessibility testing it was discovered that wizard step buttons are being reported as links by the screen reader (NVDA, JAWS). Claimed expected behavior by the tester is that they should be announced as buttons.

This change addresses the problem by adding `role` attribute to the said elements with the value of a `button`.

Elements in question are these circle buttons:

image

You can navigate to them using a Tab button, at which point they were announced as links, i.e. "One; **Link**; Visited; Select objects to convert". With this change it will be announced as "One; **Button**; Visited; Select objects to convert".

This will affect all wizard dialogs in ADS, but I assume we need this change everywhere to comply with accessibility requirements?

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
This seems reasonable, but it looks like this is still being announced as "visited" which doesn't make sense for a button...

If we're going to do this I would think we should be converting these into actual buttons - that's typically the much preferred approach.

**Comment by Charles-Gagnon** [comment]
Can you please also file an issue so we can track the history of accessibility fixes easier (stuff like this keeps coming up and it's good to easily be able to refer back to the issues when doing reviews down the line)

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon idk the story behind the "visited". I suppose it comes from a link, yeah, but they don't seem to have issue with that. Although I don't know if they assume that it should stop reading "visited" when it announces it as a button or not. I was under impression that "visited" represents the fact that step was already visited (i.e. is a blue circle instead of gray, to align with the visuals). If we were to change this to an `input` element with type `button`, then we would lose that announcement. We will gain enabled/disabled, though, I think. I'm not really sure what is preferred or expected. Currently this is what we have:

> Expected:
The NVDA should read the steps as Button as on click they are not redirected rather an action is performed .

I assume they may come back and say - now "visited" doesn't make sense for the button (although I think logically it does).

We do have an internal (ADO) bug tracking this for our product, I don't think I can link it here.

**Comment by nahk-ivanov** [comment]
This is an attempt to address #17670

**Comment by Charles-Gagnon** [comment]
It seems like the visited text is not referring to whether the step has been visited or not - it's announcing "visited" regardless. Given how links usually work it's probably something to do with the state of the link not being calculated correctly (since it doesn't actually link anywhere).

Could you follow up with the person who did the review and find out the appropriate course of action here? I would expect that getting rid of the visited text at least would be required to actually pass compliance.

(I'm actually surprised there hasn't been more issues here though. Like for example we don't even announce which one is selected so a user tabbing through these has no idea which page is currently displayed)

**Comment by Charles-Gagnon** [comment]
(and FYI you can ignore the component governance failure. That has nothing to do with your PR and we should have that cleared up within a day or so)

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon yeah, I need to dial in to accessibility office hours regardless, will ask what is the expected here and update the issue. As to the visited - it actually does not allow you to focus on the gray one, so reading "visited" on the active links kind of makes sense, as all blue steps are kind of visited. :) I agree that there is no way to make it read "current" anyhow, so maybe these should be some form of toggle buttons? Then blue/gray visual will become enabled/disabled and toggle will be the current one.

**Comment by Charles-Gagnon** [comment]
That's a great question to ask them, I don't really know how a wizard UI like this would normally be expected to behave. But yeah something along the lines of what you said seems better than what we have for sure.

I'll leave it up to you as to how much you want to work on this effort yourself - I don't have an issue if you just want to address the one specific problem brought up in your review (but let's just make sure we're addressing it correctly). @alanrenmsft and I can work out what to do about further improvements as part of committer work.

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon, okay, so here's what they've told me.

It is perfectly fine these being announced as links. If we were to design this from the ground up, they probably advice different UX to begin with, but given what we have - it is okay. They also suggested to look into additional ARIA attributes: `aria-current="step"` and `aria-disabled="true"`. I'll investigate how these impact NVDA announcements and apply, if I find them useful.

So let's hold off on this until I finish my research.

**Comment by Charles-Gagnon** [comment]
Thanks for checking that out! Loop me and @alanrenmsft in if you have any questions or want to go over anything.

**Review by alanrenmsft — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon @alanrenmsft 

Okay, done. I reverted the role change, as links are apparently okay and added two more attributes:
- `aria-current="step"` if the link is for the currently active step. This literally just announces "current step" at the end, when you focus on a link
- `aria-disabled="true"` makes it say "**unavailable**; link; two" when in NVDA "browse" mode and move to the grayed-out link.

I think this is the best we can do now that seems to be reasonable with the current design according to SMEs.

**Pull request merged**
