### PR TITLE
Notebook - text cell - minimum height fix

### PR DESCRIPTION
**Pull request by halerankin**
https://user-images.githubusercontent.com/12279161/106187691-cc736e80-615a-11eb-9d50-c4bdfb41ec64.mov

Sets minimum height to text cell element so whether empty or occupied with a single line of content, the container is the same height.

Attached MOV of UI in action.

This PR fixes #

### CODE REVIEW

**Comment by MaddyDev** [comment]
Fixes #12878

**Comment by chlafreniere** [comment]
Can we add padding that matches whatever padding <p> has by default when there isn't any content? Ideally the following screenshots would be indistinguishable:

image

image

**Comment by corivera** [comment]
@halerankin Since this affects the whole text cell, you might be able to remove the min-height I added to notebook-preview a while back. https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/notebook/browser/cellViews/media/markdown.css#L9

**Review by corivera — APPROVED** [review]

**Comment by halerankin** [comment]
Do I need more than 2 approvals to Squash and merge?

**Comment by corivera** [comment]
2 is generally fine, unless you're waiting on a review from a particular area owner.

**Review by MaddyDev — APPROVED** [review]

**Pull request merged**
