### PR TITLE
Update extension gallery to include add columns

### PR DESCRIPTION
**Pull request by sahalMoidu**
Use this extension to add columns to existing table using the context menu.

This PR fixes #

### CODE REVIEW

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
1. Please update the "TotalCount" metadata field at the bottom of the file
2. Add the extension to the [extensionsGallery-insider.json](https://github.com/microsoft/azuredatastudio/blob/release/extensions/extensionsGallery-insider.json) file as well
3. Extension titles should be sentence cased (e.g. `Add Columns` instead of `ADD COLUMNS`) - please update this in the package.json as well as these files
4. Update the `Microsoft.VisualStudio.Services.Links.Source` metadata field in your entry to point to your own repo

**Comment by sahalMoidu** [comment]
Hi @Charles-Gagnon 

I have updated as per your suggestions

In the extensionsGallery-insider.json  file my plugin id is 82 and on the extensionsGallery.json  its 81.  Should it match

**Comment by Charles-Gagnon** [comment]
Yes it should, both should be 82.

**Comment by Charles-Gagnon** [comment]
Please also update the package.json in your repo with the new display name and tag that as a new version.

**Comment by sahalMoidu** [comment]
@Charles-Gagnon updated as per your last comments

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by sahalMoidu** [comment]
@Charles-Gagnon Thank you

**Comment by sahalMoidu** [comment]
@Charles-Gagnon Is there a way to make Azure Data Studio install the extension without taking to the git hub release page.
will updating this 
{
	"assetType": "Microsoft.SQLOps.DownloadPage",
	"source": "https://github.com/sahalMoidu/ADS-add-columns/releases/tag/0.0.12"
}
to
{
	"assetType": "Microsoft.SQLOps.DownloadPage",
	"source": "https://github.com/sahalMoidu/ADS-add-columns/releases/download/0.0.12/ADS-add-columns-0.0.12.vsix"
}

help

**Comment by Charles-Gagnon** [comment]
Unfortunately our current policy is that 3rd party extensions are only installable through a separate download page where the user downloads the VSIX and installs it manually. At some point we want to have this experience be better for everyone but that's not currently the case.

**Pull request closed without merging**
