### PR TITLE
tasks widget updates

### PR DESCRIPTION
**Pull request by alanrenmsft**
1. fix the issue that all tabs will have the dashboard toolbar menu contribution. 
1. handle the scenario where multiple tasks widgets are provided in the tab
1. handle the scenario when the tab is only providing tasks widgets
1. remove the tasks widget code.

**contributed a schema compare task**
Screen Shot 2020-04-03 at 8 44 23 PM

**there are 2 tasks widgets in this tab**
Screen Shot 2020-04-03 at 8 43 41 PM

**normal tab**
Screen Shot 2020-04-02 at 10 52 43 AM

### CODE REVIEW

**Comment by kisantia** [comment]
Did the "learn more" action at the end of the toolbar get removed?
image

**Comment by alanrenmsft** [comment]
> Did the "learn more" action at the end of the toolbar get removed? It isn't in the first screenshot
> image

good catch, let me take a look

**Comment by alanrenmsft** [comment]
Screen Shot 2020-04-05 at 8 13 40 PM
@kisantia  now that your favorite menu item is back.

**Comment by alanrenmsft** [comment]
I've merged https://github.com/microsoft/azuredatastudio/pull/9863 into this branch now.

**Comment by alanrenmsft** [comment]
@kisantia any other comments?

**Pull request merged**
