### PR TITLE
Remove rollup

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
The rollup module isn't currently being used in the dev/OSS version of the product - so removing it since right now it just fails to compile.

@kburtram - Do you know anything about what this is doing? Any issues with removing this here? It seems to be for web mode only from looking at how it's used in the distro repo so there doesn't seem to be a reason to keep it in this repo that I can see.

### CODE REVIEW

**Comment by kburtram** [comment]
@Charles-Gagnon what's the issue you're trying to fix with this PR?

**Comment by Charles-Gagnon** [comment]
It's just that right now you can't compile the build directory locally. Not normally an issue for most folks but it's something I ran in to when I was debugging something with the build gulp tasks.

**Comment by kburtram** [comment]
@Charles-Gagnon if this isn't causing an immediate problem I'd rather wait until the webmode builds are working again before making changes here.  As part of that work we can move this file there is that makes sense.  At the moment I don't have context on the file, but I know there were module load issues around angular, etc.  I'd recommend keeping this open for the next couple weeks and we can revisit once I've had a chance to look at the builds.

**Comment by Charles-Gagnon** [comment]
*shrug* Both me and Alex hit this within the past couple of days. It's definitely annoying if you want to do anything with the build scripts.

Note that this doesn't affect the product builds at all. Those still merge in the distro repo which still contains this file and associated dependencies.

That being said - if it'd make you feel better we can also just add back in the missing package (rollup). I just didn't see the point in having this stuff for dev builds since all it's doing is add overhead.

**Comment by kburtram** [comment]
Yes, I think it makes sense to hold off updating web related artifacts until I have a chance to look at them.  If this isn't blocking then let's hold off updating web-related content.

**Review by alanrenmsft — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Alright, I'll open another PR for adding back in the dependency though since that's a much safer change to make

**Pull request closed without merging**
