### PR TITLE
Fix for issue 7233

### PR DESCRIPTION
**Pull request by alanrenmsft**
supply extension parameter

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
It's preferred to make the title a description of the change (for easy viewing of git history) and then just linking the item in the description

**Comment by Charles-Gagnon** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by kburtram** [comment]
@alanrenmsft please use more descriptive commit messages and ideally provide a link to the issue in the description.  I have to go to the issues and look up #7233 to determine what this commit is about.  Thanks.

**Comment by alanrenmsft** [comment]
@kburtram, sure. sorry about that.

**Pull request merged**
