### PR TITLE
Update extensionsGallery-insider.json for ML extension 0.8.0

### PR DESCRIPTION
**Pull request by llali**
ADO build link for ML extension 0.8.0: https://mssqltools.visualstudio.com/_apis/resources/Containers/2880981/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.8.0.vsix

### CODE REVIEW

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
@llali This appears to be from a canary build. We don't release from that pipeline - the only pipeline that we should be releasing stuff from is https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build?definitionId=290

Please provide a link to a build from that pipeline that contain the changes you want published

**Comment by llali** [comment]
> @llali This appears to be from a canary build. We don't release from that pipeline - the only pipeline that we should be releasing stuff from is https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build?definitionId=290
> 
> Please provide a link to a build from that pipeline that contain the changes you want published

Updated the link @Charles-Gagnon

**Review by Charles-Gagnon — APPROVED** [review]
In the future if you could provide a link to the actual build instead of a direct link to the package (or both) that would make it easier to verify that the correct pipeline is being used.

**Comment by Charles-Gagnon** [comment]
Gallery updated!

**Pull request merged**
