### PR TITLE
fixed Japanese Language Pack package url.

### LINKED ISSUE #13835: Japanese Language Pack is not available
- Azure Data Studio Version:1.25.1 

Steps to Reproduce:

1. Open the command palette.
2. Fill in the text box with "Configure Display Language."
3. Click "Install additional languages..."
4. Select "Japanese Language Pack for Azure Data Studio."
5. Error message is displayed.

The error message : "Unable to open 'Extension: Japanese Language Pack for Azure Data Studio': XHR failed."

### PR DESCRIPTION
**Pull request by smartguest**
Japanese Language Pack package.json url was wrong, url now corrected.
This PR fixes #13835

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@smartguest the changes have been published, please validate.

**Comment by smartguest** [comment]
@alanrenmsft Japanese Language Pack has successfully installed, however the ".azuredatastudio" folder must be deleted if the user installed the corrupted Japanese Language Pack as it will cause extensions to fail to load.

**Comment by alanrenmsft** [comment]
@smartguest do you mean the .azuredatastudio folder under the user's directory e.g. on windows: c:\users\alanren\.azuredatastudio?. that means all the extensions will be removed, we shouldn't and can't ask users to do that. It seems to be uninstalling the Japanese language pack itself should be good enough, could you please give it a try? also could you please double check the other language packs to make sure they all have correct path?

and please follow up with the user in the issue directly and close it when things are working for the user.

**Comment by smartguest** [comment]
At least you need to delete the Japanese Language pack Extension under that folder @alanrenmsft, If it was corrupted, I can't reproduce it as it now loads correctly, (the Japanese language pack files seemed to be still under the extensions folder when I tried to uninstall it but that's with the corrupted one) I'll ask the user to see if it works for him now

**Pull request merged**
