### PR TITLE
STS version bump

### PR DESCRIPTION
**Pull request by ssreerama**
This PR fixes :
image

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
You don't need to include this many commits, you're only bumping it 2 versions. Use the releases tab in the STS repo to figure out what commit the previous version was from.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

**Comment by ssreerama** [comment]
Haha, I felt hard to found which commit was at with last vbump and followed the date(june17 and so) :p

**Review by aasimkhan30 — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Where did you get that date from? The previous update happened earlier today : https://github.com/microsoft/azuredatastudio/pull/19943

**Comment by ssreerama** [comment]
I guess I saw some other old vbump PR! 

The Linux PR check is failing with some test failure but the same are passing in windows/Mac, Is this failure is expected because the STS model(deploymentoptions) is changed! can i go ahead and proceed with merge? or should i need to look into something else?

**Comment by Charles-Gagnon** [comment]
Generally it's best to make sure the runs are green before merging in. You should re-run any failing jobs to see if they pass the second time, if they continue to fail and you aren't able to determine the cause yourself then reach out to the team for assistance.

**Comment by Charles-Gagnon** [comment]
Given that two separate runs are failing with the same error though it would seem this vBump is causing something to break. Did you run the tests locally to see if you can repro them?

**Comment by ssreerama** [comment]
Yes, I ran this locally and it is passing all the time with my changes, since my change have the chnages where it is failing! 

It is failing just with the STS version update. I'm adding the fix in this PR, and then update in the next merging PR! back to back merges!

**Pull request merged**
