### PR TITLE
Adding group by schema button to OE

### PR DESCRIPTION
**Pull request by aasimkhan30**
When group by schema is enabled
image
When group by schema is disabled
image

### CODE REVIEW

**Review by erinstellato-ms — COMMENTED** [review]
I think the buttons are reversed.  For query plans, when the actual plan is NOT yet enabled, we have: 
image
Which has **no** X.

When actual plan is enabled, we have:
image
which **does** have the X.

**Comment by Charles-Gagnon** [comment]
This doesn't apply to any providers that don't implement this themselves, which could get confusing. Especially since not all providers have the concept of a schema. Do you have any longer term plans for how to address these kinds of gaps?

**Comment by erinstellato-ms** [comment]
> This doesn't apply to any providers that don't implement this themselves, which could get confusing. Especially since not all providers have the concept of a schema. Do you have any longer term plans for how to address these kinds of gaps?

We talked about this in detail and I met with design.  It's tricky.  We can include "mssql" or "SQL" in the text that appears when you hover over the icon.  The right-click menu option will only appear for SQL connections, and obviously when the button is used, it only applies to SQL connections. 

We determined that placing the icon at the Server level was less confusing than at the server or database level, because the configuration will apply to **all** SQL connections.  We decided to trade off having the option at the higher level with potential confusion for non-SQL providers.

The telemetry is implemented for both the button and right-click so we have two events to understand which one is used (or if both are used equally).

**Comment by alanrenmsft** [comment]
I personally prefer this feature to leverage the secondary actions (the ...  menu), in the pop out menu, we can have a `SQL Server` sub menu with `Toggle Group By Schema`, benefit of this approach:
1. scalable: all providers can contribute actions without 
2. easy to understand: since the actions are grouped, it is easy to figure out the target of an action.

It is not perfect but I am not going to block this PR if you guys already made the decision. Just couple comments:
1. The new button should be added at the end of list.
2. Fix the issues pointed out by @erinstellato-ms: update tooltip to add `(SQL Server)` and make sure the icon and text match.

**Review by Charles-Gagnon — APPROVED** [review]
While what Alan said is true, hiding it in the secondary menu isn't great either. So with the "SQL Server" tab I guess it's fine - although it'd be good to be thinking about these kinds of things in the future when designing features such as this.

**Review by alanrenmsft — APPROVED** [review]
Please address Erin's comments, otherwise it looks good to me.

**Comment by erinstellato-ms** [comment]
> 

We talked about the breadcrumb (...) menu option, and the challenge is that it's not very discoverable as it sits right now at the end of the CONNECTIONs line.  The breadcrumb is much more discoverable if it exists AFTER other icons.  

I'm not opposed to adding the breadcrumb after the existing three connection icons, and then having a pop out menu with SQL Server, and then the Enable Group By Schema option.  But I don't think that the setting/option should exist at the CONNECTIONS menu level.  I think it should exist at the SERVERS level.

(and this is why I invited you to the meeting yesterday where I forgot to invite Aasim...you probably thought I invited you by mistake, but we wanted your opinion then :)

**Comment by aasimkhan30** [comment]
@erinstellato-ms and @alanrenmsft, fixing the ordering of icon.

image

**Pull request merged**
