### PR TITLE
Add proposed interactive copilot API

### LINKED ISSUE #23588: API proposals error for Github Copilot extension
Insiders/main

I'm seeing this error on startup with the Github copilot extension installed : 

`Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, interactive, semanticSimilarity
product.json (WINS): inlineCompletionsAdditions, terminalDataWriteEvent`

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #23588

I used the copilot extension before and after adding this proposed API and didn't find anything that would negatively impact how the extension works. Adding the proposed API from this PR will remove the console warning message seen in the issue description.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
What features does this enable? Did you test them to make sure they work?

**Comment by Charles-Gagnon** [comment]
Also the error shows more differences than what we have here - do you know you aren't seeing an error for `semanticSimilarity`? And why `terminalDataWriteEvent` doesn't exist?

package.json : inlineCompletionsAdditions, interactive, semanticSimilarity 
product.json : inlineCompletionsAdditions, terminalDataWriteEvent

**Comment by lewis-sanchez** [comment]
I'm not seeing any of that. All I see is this info message:
image

**Comment by lewis-sanchez** [comment]
All of the updates/improvements that we get for the copilot extension happen through the VS Code merges.

**Comment by lewis-sanchez** [comment]
@Charles-Gagnon, I think the proposed interactive API is for the GitHub Copilot Chat extension: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat

Something that is demonstrated here: https://code.visualstudio.com/updates/v1_79#_github-copilot

**Review by Charles-Gagnon — APPROVED** [review]
I would highly suggest checking with the Copilot team to figure out if what you said is actually the case just to make sure we're not breaking anything by enabling this. Although I'm curious why this extension has that proposal instead of the chat extension, so that'd be another question to ask them.

**Review by kisantia — APPROVED** [review]
Before merging this, please verify that this won't expose any scenarios that aren't yet supported in ADS

**Review by kburtram — APPROVED** [review]

**Pull request merged**
