### PR TITLE
Update extensions for release 1.18

### PR DESCRIPTION
**Pull request by abist**
Updated agent from 0.47.0 to 0.48.0
Updated profiler from 0.11.0 to 0.12.0
Updated admin-pack from 0.0.2 to 0.1.0
Updated dacpac from 1.4.0 to 1.5.0
Updated schema-compare from 1.4.0 to 1.5.0
Updated cms from 0.8.0 to 0.9.0
Updated admin-tool-ext-win from 0.0.2 to 0.1.0
Updated query-history from 0.1.0 to 0.2.0

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Testing I assume?

**Comment by abist** [comment]
@Charles-Gagnon Wrote an automated notebook that does this, looks like it worked 😄

**Comment by Charles-Gagnon** [comment]
Cool! It looks like it might need some work though? Most of these weren't actually updated recently.

**Comment by abist** [comment]
@Charles-Gagnon It's user input. I tried to bump them all intentionally to see if they all work.

**Pull request closed without merging**
