### PR TITLE
Move vscode from dependencies to devDependencies

### PR DESCRIPTION
**Pull request by aaomidi**
Move vscode out of dependencies

### CODE REVIEW

**Comment by anthonydresser** [comment]
out can also add the entire out folder to the vscodeignore and also add the out folder to the vscode ignore of the big-data-cluster extension

**Comment by alanrenmsft** [comment]
@aaomidi , Don't you need to make changes to the extensions.ts to verify ?

**Comment by aaomidi** [comment]
@alanrenmsft I do, but this is something that has to be done anyway.

**Comment by alanrenmsft** [comment]
@aaomidi PR build passed, good to go

**Comment by aaomidi** [comment]
I'll schedule an insiders build.

**Pull request merged**
