### PR TITLE
Update PowerShell extension to v1.12.1

### PR DESCRIPTION
**Pull request by rjmholt**
Updates the version of the PowerShell extension in ADS to 1.12.1.
**Note**: This is an automated PR.

### CODE REVIEW

**Comment by rjmholt** [comment]
@TylerLeonhardt

**Comment by kburtram** [comment]
@alanrenmsft would you like to publish this or should I?

**Comment by alanrenmsft** [comment]
@kburtram , thanks for checking, I will do it.

**Comment by alanrenmsft** [comment]
@rjmholt please also update the gallery file for insiders build

**Comment by rjmholt** [comment]
https://github.com/Microsoft/azuredatastudio/pull/5257

**Comment by alanrenmsft** [comment]
the latest powershell extension is available for ADS now for both stable build and insiders build.
@rjmholt

**Comment by rjmholt** [comment]
Thanks @alanrenmsft !

**Pull request merged**
