### PR TITLE
Remove request promise for request-light (#10346)

### LINKED ISSUE #10367: Failing pipelines
Pipelines are failing.

### PR DESCRIPTION
**Pull request by anthonydresser**
* remove request promise for request-light

* make sure data is a string not a json

* add configure call

* remove unused reference

* more fixes

* Move configure calls

* clean up

* fix name

* move test deps as dev

Co-authored-by: chgagnon <chgagnon@microsoft.com>

fixes #10367

### CODE REVIEW

**Comment by kburtram** [comment]
@anthonydresser could you please ask @kenvanhyning to approve porting this to the release branch?

**Comment by anthonydresser** [comment]
fixes #10367

**Comment by anthonydresser** [comment]
@kburtram made a linked issue.

**Comment by anthonydresser** [comment]
Merging due to issue being approved

**Pull request merged**
