### PR TITLE
Update release notes link

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by anthonydresser** [comment]
Hmm, this is interesting. Are we not concerned about showing release notes for a version of ads that the user isn't using?

**Comment by Charles-Gagnon** [comment]
The release notes is just a page of all the compiled notes so there's not a huge need for them to link directly to the notes for a version.

https://docs.microsoft.com/en-us/sql/azure-data-studio/release-notes-azure-data-studio?view=sql-server-ver15

I think the annoyance of updating the link for every release would be more than the benefits would be from doing that.

**Comment by anthonydresser** [comment]
Vscode has the release notes link programically generated based on the version, so it updates every release automaticaly

**Comment by Charles-Gagnon** [comment]
Sure, that would be useful and we could do something similar. I just don't think it's really worth the effort at this point in time.

(I'm just updating this link here to avoid confusion between azdata the tool and azuredatastudio)

**Comment by Charles-Gagnon** [comment]
Going to merge this in - but if you have ideas about how to do that ourselves easily I'm open to further discussion.

**Pull request merged**
