### PR TITLE
Update dialogs to be closer to mockups

### PR DESCRIPTION
**Pull request by kisantia**
Small UI changes to make dialogs closer to mockups after discussion with UX:
- change to colorful icon
- change browse button to folder
- make card buttons square
- some string changes

Screen Shot 2020-10-13 at 6 43 31 PM
Screen Shot 2020-10-13 at 6 43 39 PM

### CODE REVIEW

**Comment by kisantia** [comment]
@dzsquared if there are any changes you would like for the sql database project type description, I can include it in this PR too

**Review by Benjin — APPROVED** [review]

**Comment by Benjin** [comment]
Can you include the reference mockups in the PR description?

**Comment by alanrenmsft** [comment]
it seems Amir changed the radio card group and caused the text to not vertically center aligned, that makes the cards look bad, especially for the Local File one. could you please take a look and see anything quick you can do to improve?

**Review by udeeshagautam — APPROVED** [review]
looks pretty good

**Comment by udeeshagautam** [comment]
> it seems Amir changed the radio card group and caused the text to not vertically center aligned, that makes the cards look bad, especially for the Local File one. could you please take a look and see anything quick you can do to improve?

thats a good obseration

**Comment by kisantia** [comment]
I updated the screenshots. @alanrenmsft the height for the text-container in the radioCardGroup wasn't being set correctly, so I added a function to calculate it based on the card height and icon height. Is there a better way to do this?

**Comment by alanrenmsft** [comment]
@kisantia it seems the same to me comparing to the first version. lol

**Comment by kisantia** [comment]
@alanrenmsft oops I must not have saved. It's updated now

**Comment by alanrenmsft** [comment]
looks good to me, please also check the resource deployment dialog and make sure it looks good too.

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
