### PR TITLE
Bbrady/welcome page focus contrast #10616

### LINKED ISSUE #10616: A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_ColorContrast: The focus on 4 links is below 3:1
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yWCAG2.1;#Benchmark;#DesktopApp;#MAS1.4.11;#SQL Azure Data Studio;#FTP;#ColorContrast;#Win32;#Acc123;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS1.4.11
Tool: Accessibility insights for desktop

**Repro Steps:**
1 .Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 .Launch Accessibility insights for desktop and select third tab contrast.

**Actual:**
When the tab focus in on " create a connection, run a query, create a notebook, deploy a server " the focus color contrast is at 2.227:1 which is below 3:1

**Same issue for the following page:**
1 .Resources- tab focus on show more and get started and documentation link.
2. Extend your data Studio-all controls in the section beside install button
3 .Videos Pop Up- on both links 

**Expected:**
The color contrast of the focus should be 3:1 or greater 

**User Impact:**
Low vision users will face difficulty in viewing the focus.

**Attachment link for Reference:**
10616A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_ColorContrast

### PR DESCRIPTION
**Pull request by v-bbrady**
This PR adjusts the color contrast for focus states on the welcome page to meet accessibility requirements.
New contrast ratio: 4.905:1

This PR fixes #10616

Before:
old

After: 
newFocus

### CODE REVIEW

**Comment by alanrenmsft** [comment]
please add screenshots for before and after, and what is the new contrast ratio now?

**Comment by alanrenmsft** [comment]
a general feedback, please add me as a reviewer for all the accessibility fixes so that i can get the notification.

**Comment by alanrenmsft** [comment]
@v-bbrady screenshots?

**Comment by v-bbrady** [comment]
> 
> 
> @v-bbrady - and you still haven't answered my question :
> 
> ```
>  why are you using buttonPrimaryBackgroundColor for a focus border? We should be using the same focus border throughout the app, is the focusBorder color not enough?
> ```
> 
> The reason I'm concerned is because using the "primary background color" for a button isn't intuitive - so someone might change the theme colors thinking it'll only impact the button background colors and then be surprised when it's affecting focus borders as well.
> 
> Not having a consistent border focus color across the entire app seems odd to me. At the very least we should have a new color that's specifically for borders around these buttons (and others which share the same color scheme)

@Charles-Gagnon Hey Charles, sorry I didnt answer the question. I didnt answer because I just went ahead and updated it to use the focusBorder color.

**Pull request merged**
