### PR TITLE
Remove old unused splash screen

### PR DESCRIPTION
**Pull request by abist**
Remove the old splash screen.

### CODE REVIEW

**Comment by abist** [comment]
@anthonydresser  `src\vs\workbench\contrib\welcome\page\browser\welcomePage.ts`

**Comment by anthonydresser** [comment]
Aren't these 2 separate things? splash is when you have no windows open. the Welcome page is a window that opens by default.

**Comment by abist** [comment]
We don't have a splash screen right now then.

**Comment by anthonydresser** [comment]
isn't this the splashscreen?
image

**Comment by abist** [comment]
I thought you meant the "image" that shows up. I'll test with the packaged build and make changes if necessary.

**Comment by abist** [comment]
App opens with the welcome page - 

Capture

@kburtram Can we get rid of these files?

**Comment by kburtram** [comment]
The splashscreen is the window that used to display on startup with the below image.  I don't anticipate that we'll add the splashscreen back in the future so it's fine to remove.  @anthonydresser I think the screen you're showing is called the watermark.

image

**Pull request merged**
