### PR TITLE
Sept2020 updates to extensions

### PR DESCRIPTION
**Pull request by dzsquared**
Updating marketplace for:
Query Editor Boost - release is ready and waiting, just never published to marketplace
First Responder Kit - release isn't packaged yet, just getting into marketplace of stable ahead of code freeze

### CODE REVIEW

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]

**Comment by Charles-Gagnon** [comment]
And FYI - the extension gallery can be updated at any time if needed. They don't necessarily need to be tied to code freeze/ADS release dates.

**Review by Charles-Gagnon — APPROVED** [review]
Looks good, but hold off on merging it in - we should do that only as part of the release on Tuesday.

And for the future let's try to do updates like this :

1. Insiders can and should generally be updated as soon as a new version is available for earlier testing
2. The stable gallery should mostly be updated as part of a release and done as part of the single "extension gallery update" PR that happens as part of every release.

**Comment by dzsquared** [comment]
@Charles-Gagnon gentle reminder about this PR.  These are 2 of my personal extensions and both of them have bugs in the current marketplace versions.

**Comment by Charles-Gagnon** [comment]
Merged and uploaded - sorry for forgetting about this!

**Pull request merged**
