### PR TITLE
add table designer menu to Azure view

### LINKED ISSUE #18298: Unable to use table designer when connecting via Azure tree
- Azure Data Studio Version: 
- Version: 1.35.0-insider (user setup)
Commit: 250532f39d2c460f25e646e701bb94d9860d7365
Date: 2022-02-10T06:27:53.725Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Ensure that Enable unreleased preview features is checked for Workbench: Enable Preview Features in Settings.
2. Within ADS, connect to an Azure subscription.
3. Once connected, expand the subscription, then SQL database, then your database, then Tables.
4. Once Tables is available, right-click, the option for New Table does not appear.
5. If you go to SQL Server, and expand that tree as well, down the table, the option does not appear there either.

image

Does this issue occur when all extensions are disabled?: Yes/No

### PR DESCRIPTION
**Pull request by alanrenmsft**
This PR fixes #18298 

image

image

### CODE REVIEW

**Review by caohai — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by abist** [comment]
@alanrenmsft Do we want to enable it for all kinds of servers right now? If yes, then looks good

**Comment by alanrenmsft** [comment]
@abist what do you mean by "all kinds of servers"? I am only enabling it for MSSQL provider.

**Comment by abist** [comment]
@alanrenmsft azure sql db + on prem vs on-prem only

**Comment by Charles-Gagnon** [comment]
And MI too (engine edition 11) 

https://github.com/microsoft/azuredatastudio/blob/8e1e9a95c30daa906b865b4e8fff45ecf2d8ce22/extensions/import/package.json#L55

**Pull request merged**
