### PR TITLE
Prevent paused DBs from breaking OE

### LINKED ISSUE #22211: Expanding Paused database leads to breaking OE connection
- Azure Data Studio Version: 1.42.0-rc1
- OS Version: Windows 11

Steps to Reproduce:

1. Create a connection to Azure SQL Server
2. Expand a paused database node.

Notice the error message contains entire stack-trace and OE connection is dropped.

OE_PausedDB

Expected:
1. Error message dialog should only show error message and not entire stack trace.
2. OE connection to Azure Server should not get dropped.

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #22211

This PR addresses a situation where expanding a paused DB would break OE. The fix now allows the proper error dialog to appear with an explanation for why the DB node wasn't able to be expanded.
image

### CODE REVIEW

**Comment by aasimkhan30** [comment]
@lewis-sanchez , do you know why onSessionDisconnected is getting called in the first place? This method is called by the providers. 
According to me, the right fix will be in sts to not call the onSessonDisconnected when errors happen.

Also, how is the check supposed to fix the issue? Can you please add a comment in the code as well?

**Comment by aasimkhan30** [comment]
@lewis-sanchez , do you know why onSessionDisconnected is getting called in the first place? This method is called by the providers. 
According to me, the right fix will be in sts to not call the onSessonDisconnected when errors happen.

Also, how is the check suppose to fix the issue? Can you please add a comment as well?

@cheenamalhotra , what do you think?

**Comment by aasimkhan30** [comment]
@lewis-sanchez , can you please take a look into these errors as well and see if they are getting fixed too

https://github.com/microsoft/azuredatastudio/issues/6300
https://github.com/microsoft/azuredatastudio/issues/21644

**Comment by aasimkhan30** [comment]
The error is occurring because the onSessionDisconnectedNotification is being triggered from STS.

https://github.com/microsoft/sqltoolsservice/blob/a47cccf85b3b16ad57b2234b85667a1fa7222af4/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/ObjectExplorerService.cs#L788

To resolve this issue, we need to investigate why we are sending that notification. In most cases, when encountering errors, we should respond with an expandNotification and set the errorMessage property in the response.

https://github.com/microsoft/sqltoolsservice/blob/a47cccf85b3b16ad57b2234b85667a1fa7222af4/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/Contracts/ExpandRequest.cs#L37

Including the stack trace in the error message is acceptable as it provides valuable information for debugging these errors.

**Comment by lewis-sanchez** [comment]
Changes to fix this issue were made in the SQL Tools Service repo here: https://github.com/microsoft/sqltoolsservice/pull/2083

**Pull request closed without merging**
