### PR TITLE
Update pgsql extension and readme

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by anthonydresser** [comment]
Is there a reason we aren't just downloading the vsix from whats defined in the "extension marketplace" and installing it as part of the setup script?

**Comment by Charles-Gagnon** [comment]
I was thinking that too. This is just a quick fix so our tests are using the latest since I don't have the time to work on that task at the moment.

**Comment by alanrenmsft** [comment]
> I was thinking that too. This is just a quick fix so our tests are using the latest since I don't have the time to work on that task at the moment.

let's create an issue to track this work item at least.

**Comment by Charles-Gagnon** [comment]
#9372

**Pull request merged**
