### PR TITLE
Fixes the azure auth for postgresql

### PR DESCRIPTION
**Pull request by aaomidi**
Attempts to fix the postgresql issue with authentication.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@aaomidi Anything blocking this going in?

**Comment by aaomidi** [comment]
@Charles-Gagnon I haven't confirmed this fixes their problem. I am waiting for a signoff from the postgre team.

**Comment by swjain23** [comment]
@aaomidi - Richard has verified that the PR solves the issue. Just for future reference, if we find a problem with Release, what is the process? do we comment on the release issue or send an email?

**Comment by aaomidi** [comment]
Opening an issue and linking to it in an email is great! I'll make a port request this for release now, please make sure to test the release RCs on https://github.com/microsoft/azuredatastudio/issues/10720

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/pull/10662

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/pull/10753

**Comment by swjain23** [comment]
Got it, thank you :). We will test it once it is merged to release branch.

**Comment by rich617** [comment]
I still think we need a connection property that returns true if authType is either AzureMFA or AzureMFAAndUser because that test is in a lot of places. If no one has time, maybe I'll give it a go.

**Pull request merged**
