### PR TITLE
Fix agent for release

### PR DESCRIPTION
**Pull request by abist**
This PR fixes https://github.com/microsoft/azuredatastudio/issues/13125

Charles has a fix in main here - https://github.com/microsoft/azuredatastudio/pull/13126, but it introduced some new issues. This is a more scoped and safer fix for release. I'll do the same in main.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
Are you not going to fix the logic for checkPreviousFilters? https://github.com/microsoft/azuredatastudio/blob/6ff1e3866bcad2a8a639fdaf6e6fe4aeab49b2b2/src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts#L562

**Comment by abist** [comment]
@Charles-Gagnon Actually that's fine there because we parse an item in `checkPreviousFilters` while it was a `string` in the other place.

**Comment by Charles-Gagnon** [comment]
Yeah, but we do also push an array of strings on https://github.com/microsoft/azuredatastudio/blob/6ff1e3866bcad2a8a639fdaf6e6fe4aeab49b2b2/src/sql/workbench/contrib/jobManagement/browser/jobsView.component.ts#L290, so `this.filterValueMap[column][0]` would be a string and thus would break.

(Although I think this was always broken, so maybe that logic was never hit or something)

This was the kind of stuff that was greatly confusing me working with this.

**Comment by abist** [comment]
@Charles-Gagnon You're right, there's some mismatch in the types because `filterValues` here is `any` and it works out. I've opened a task to type the Agent extension overall - https://github.com/microsoft/azuredatastudio/issues/13236

**Comment by Charles-Gagnon** [comment]
I wonder if the first element (index 0) was supposed to be the filter values, while the second (index 1) was supposed to be the filtered items themselves. That would at least match what I was seeing.

Now why we need to store this kind of information in this way I have no idea, but the bug there might just be that it's supposed to be ` this.filterValueMap[args.column.name][0] = [filterValues];`

**Pull request merged**
