### PR TITLE
Add async to change password dialog (merge after error handling)

### PR DESCRIPTION
**Pull request by smartguest**
This PR addresses #21756, #21757, and #21760 and is a follow up to the error handling PR #21627 

This is to be merged after the previous PR

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Is there any reason not to do this one first? It's a lot more targeted so seems simpler to just take of first so we can properly review the other one. Especially since this is addressing some seemingly important issues you discovered.

**Comment by smartguest** [comment]
@Charles-Gagnon This adds in numerous changes that requires having the error handler first (which is already part of that PR) so that one would have to be merged in first or that one closed, so that this one can go first.

**Comment by Charles-Gagnon** [comment]
Aren't these issues with the existing dialog though? I'm a bit confused on why these two PRs have to be so tightly integrated - it seems like the issues you linked above should be something that can be fixed with the existing code. Then if the error handling PR needs to make further changes to the place where this dialog is shown that's fine (and expected since it'll be called from the extension instead of core code)

Even if you take just a couple smaller fixes to the dialog itself or something that'd be good - the more concise the other PR is the better given the large amount of changes it has already.

**Comment by smartguest** [comment]
@Charles-Gagnon It turns out all of these issues are only introduced with the Error Handler, and not part of the current password dialog. With the connection explorer not having the dialog implemented. And the current query editor has the password change dialog working fine.

**Comment by Charles-Gagnon** [comment]
Ok, then let's mark this as a draft and do it as a follow up once the other PR is merged in.

**Comment by cheenamalhotra** [comment]
Seems like we're introducing regressions in main first and then fixing it - we should avoid pushing regressions in main. 
Can we target this PR on the branch from PR https://github.com/microsoft/azuredatastudio/pull/21627 so it can be easily reviewed standalone?

**Pull request closed without merging**
