### PR TITLE
Distribute the area properly

### LINKED ISSUE #7965: Results grids aren't sized proportionally
- Azure Data Studio Version: 1.13

Steps to Reproduce:

1. Open query window and type a query with two results sets
2. Execute query

Expected: results set grids height is split 50%\50% unless the grids are larger than minimum size

Actual: First grid gets disproportionate height

*Note: colored boxes should be same height*
image

### PR DESCRIPTION
**Pull request by aaomidi**
This PR fixes #7965

### CODE REVIEW

**Comment by anthonydresser** [comment]
I don't think this is the right solution. There is a setting to distribute the sizing. Give me some time to investigate.

**Comment by aaomidi** [comment]
Sizing.Distribute? I noticed it too but I dont think it was doing anything.

**Comment by aaomidi** [comment]
@kburtram I looked into the tabbing out thing and it seems weird, it doesn't actually distribute evenly rather it just switches which side gets the larger area.

**Comment by aaomidi** [comment]
-_- github doesn't handle merges correctly. i'll close this and reopen another one.

**Pull request closed without merging**
