### PR TITLE
Add Markdown Toolbar functionality to notebook smoke tests.

### PR DESCRIPTION
**Pull request by corivera**
I tried adding some WYSIWYG editor tests, but it looks like we can't set the editor div's inner HTML using the driver methods we have currently.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
For typing in the WYSIWYG editor did you look at adding more functionality to the driver, for example look at how they implemeted the "typeInEditor" https://github.com/microsoft/azuredatastudio/blob/main/src/vs/platform/driver/browser/baseDriver.ts#L106

**Comment by corivera** [comment]
@Charles-Gagnon I started trying to add something, but once I noticed I was changing actual product code I reverted it. Are we able to modify that driver code?

**Comment by Charles-Gagnon** [comment]
We modify product code all the time - no problems there. Just make sure to put in the SQL CARBON EDITs to help with VS Code merges.

**Comment by corivera** [comment]
Ok, I'll give that a try next Test Monday.

**Pull request merged**
