### PR TITLE
Update vscodeVersion

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by anthonydresser** [comment]
Theres another spot you should update...let me find it..

**Comment by anthonydresser** [comment]
nvm its already been updated.

**Comment by Charles-Gagnon** [comment]
@anthonydresser  Where is this other place? I'm not seeing it in the repo anywhere that I can find.

I'm also thinking this isn't worth porting to April release - you agree? It's a pretty small edge case that someone would actually need this updated to the latest (basically only a VS Code extension that was updated to require that engine version) so I think it's fine to just wait until next release.

**Comment by anthonydresser** [comment]
https://github.com/microsoft/azuredatastudio/blob/master/src/vs/platform/product/common/product.ts#L24 but this gets updated by vscode so we don't need to worry. If we don't plan on porting, does it make more sense to just bump it straight to 1.45?

**Comment by Charles-Gagnon** [comment]
We could do that - but I was planning on just adding this to the release process in the short term and then looking at making it so this wasn't hardcoded (pulling from the vscodeVersion defined there might be a valid option)

How feasible is it to add something to the merge bot such that when it merges in changes it also reads the package.json of vscode and updates the value in our product.json?

**Comment by anthonydresser** [comment]
We could but I think there are probably better ways to automate it than tying it to the merge process. I'll have a think.

**Pull request merged**
