### PR TITLE
Add WakaTime extension

### PR DESCRIPTION
**Pull request by alanhamlett**
Review request: @llali

### CODE REVIEW

**Comment by kburtram** [comment]
@alanhamlett thanks for submitting this extension.  The download link in the metadata doesn't seem to resolve for me https://github.com/wakatime/vscode-wakatime/releases/tag/1.2.3.  Could you please verify that the release has been published?

**Comment by alanhamlett** [comment]
Oh, since vsce doesn't create release tags that tag doesn't exist. Is the download link for humans or machines? If for humans it can be this:

https://github.com/wakatime/vscode-wakatime/#installation

**Comment by alanhamlett** [comment]
@kburtram, corrected the download url. Thanks for catching that!

**Comment by kburtram** [comment]
@alanhamlett sorry for the delay on this PR.  We're still working through the details on including extensions in the SQL Ops Studio marketplace that are also available in the VS Code marketplace.  There are a number of potential issues we need to sort out prior to supporting this scenario (none of which are directly related to this particular extension 😄).  I'll provide you updates as they become available.  Thanks for your patience.

**Comment by gandarez** [comment]
Hello, what's the update?

**Comment by eamodio** [comment]
@kburtram Is there any update on providing extensions to Azure Data Studio? I have the following request: https://github.com/eamodio/vscode-gitlens/issues/573 but I'm not sure how to proceed given this issue. Thanks!

**Comment by gandarez** [comment]
Any update?

**Comment by castrolol** [comment]
Any Update?

**Comment by Ashtonian** [comment]
14 months and counting

**Comment by gandarez** [comment]
No update?

**Comment by gbelmm** [comment]
No update?

**Comment by alanrenmsft** [comment]
@alanhamlett 
sorry for the delay. it has been a long time since the PR was created, please follow https://github.com/microsoft/azuredatastudio/blob/release/extensions/extensionsGallery-insider.json#L2442 as an example and create update your PR, you should update extensionsGallery-insider.json as well as extensionsGallery.json.

also, I have the following comments for the PR:
1. The download page is https://wakatime.com/vs-code, which has no link to download the vsix file (at least I couldn't spot it), please fix this.
2. The readme.md is for vscode, if would be great if you can create a md file for Azure Data Studio.

adding our PM @yualan to see whether he has any other comments here.

**Comment by alanrenmsft** [comment]
close the PR since I am not hearing back from the author. please reopen the PR if you are ready.

**Comment by alanhamlett** [comment]
There's no option to re-open this PR. We have an Azure Data Studio specific download page now:
https://wakatime.com/azure-data-studio

**Comment by gandarez** [comment]
@alanhamlett the wakatime extension was added by this [PR](https://github.com/microsoft/azuredatastudio/pull/11097).

**Comment by alanhamlett** [comment]
Oh, awesome! Thanks @gandarez. No need to re-open this PR then.

**Pull request closed without merging**
