### PR TITLE
fix WYSIWYG toolbar

### LINKED ISSUE #15881: Notebook text cell toolbar icons are misaligned
image

### PR DESCRIPTION
**Pull request by barbaravaldez**
Screen Shot 2021-06-24 at 1 52 15 PM

This PR fixes #15881

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
What was the root cause and how did you arrive at this fix? We should make sure this isn't going to affect anything else.

**Comment by barbaravaldez** [comment]
> What was the root cause and how did you arrive at this fix? We should make sure this isn't going to affect anything else.

The root cause was the merge. The action items from the markdown toolbar were applying the 15px padding from the taskbar action items https://github.com/microsoft/azuredatastudio/blob/main/src/sql/base/browser/ui/taskbar/media/taskbar.css#L51

**Review by corivera — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@alanrenmsft This is needed because of the change you made here : https://github.com/microsoft/azuredatastudio/pull/15826/files

We should make sure that change isn't breaking anything else

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
So it looks like originally the styles were set with these two rules in this file : 

```
.markdown-toolbar .carbon-taskbar a {
	display: flex;
	height: 20px;
	width: 20px;
}
```
```
.markdown-toolbar .carbon-taskbar li a.action-label {
	margin: 0;
	padding: 0;
}
```

But now because Alan's change added the more specific selectors these are being overwritten by that. 

So the correct fix here would be to just increase the specificity of those as well instead of adding a new rule. e.g. 

```
.markdown-toolbar .carbon-taskbar a.codicon.action-label {
	display: flex;
	height: 20px;
	width: 20px;
}
```

(you may need to add the .monaco-action-bar class as well, try it out like this first though)

I would also go through the rest of the rules in this file and make sure they're also made more specific to avoid these kind of issues in the future.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by barbaravaldez** [comment]
> .monaco-action-bar

I had to include ` .monaco-action-bar` for it to work

**Pull request merged**
