### PR TITLE
Updating azure-storage in build

### PR DESCRIPTION
**Pull request by aasimkhan30**

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by chlafreniere** [comment]
Maybe I don't quite understand, but why is only the yarn.lock being updated and no package.json?

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Can confirm, but for a lot of these you don't need to update a direct dependency yourself if the package has a version range specified. So in this case updating from `2.10.3` to `2.10.7` should be non-breaking so most packages will have their dependencies set up to allow this (like we do with the use of `^` everywhere). 

You see this all the time with dependabot updates - e.g. https://github.com/microsoft/azuredatastudio/pull/19931

**Comment by chlafreniere** [comment]
> @aasimkhan30 Can confirm, but for a lot of these you don't need to update a direct dependency yourself if the package has a version range specified. So in this case updating from `2.10.3` to `2.10.7` should be non-breaking so most packages will have their dependencies set up to allow this (like we do with the use of `^` everywhere).
> 
> You see this all the time with dependabot updates - e.g. #19931

Ah interesting. Thanks @Charles-Gagnon. I only ask because I see that https://github.com/microsoft/azuredatastudio/blob/main/build/package.json#L47 has ^2.1.0 listed. Curious if we could just change that to ^2.1.7 instead.

Anyway, no biggie. Just was curious more than anything 😄

**Comment by aasimkhan30** [comment]
Yes, you're right @Charles-Gagnon 
So, if a there is a direct or indirect dependency to a library with `^` in front of the version number, just deleting the yarn.lock version and running yarn gets the latest minor update from npm.

**Comment by chlafreniere** [comment]
> Yes, you're right @Charles-Gagnon So, if a there is a direct or indirect dependency to a library with `^` in front of the version number, just deleting the yarn.lock version and running yarn gets the latest minor update from npm.

Ah, gotcha. TIL! Thanks @aasimkhan30

**Pull request merged**
