### PR TITLE
Add folder icon to project

### LINKED ISSUE #11001: Add Icons to DB Project Pane
For users familiar with the files viewlet, the projects pane is missing the familiar actions icons.

Icons for "Add Item", "Add Folder", and "Collapse Folders" would aid the user in navigating the extension.

(collapse folders is a duplicate of #10979)

### PR DESCRIPTION
**Pull request by SakshiS-harma**
This PR fixes #11001 partially.

image

image

### CODE REVIEW

**Comment by anthonydresser** [comment]
Why not just use vscode's built in icons?

**Comment by Charles-Gagnon** [comment]
+1 for what @anthonydresser said - you can give it a [ThemeIcon](https://github.com/microsoft/azuredatastudio/blob/main/src/vs/vscode.d.ts#L800) and should be able to just use ThemeIcon.Folder directly.

**Comment by anthonydresser** [comment]
Yep, they also have way more than just folder and icon. You could probably replace a lot of these icons for the extension with the vscode ones (just an example, they also provide a refresh icon)

**Comment by Charles-Gagnon** [comment]
https://code.visualstudio.com/api/references/icons-in-labels#icon-listing

**Comment by SakshiS-harma** [comment]
@anthonydresser , @Charles-Gagnon we don't want to update anything on the VSside, just the projects viewlet.
Also after internal discussion, the ThemeIcon's folder seems to not match the "folder" concept used elsewhere. The one added in this PR comes from an icon repository used by all Azure teams and that better matches the rest of the project icons.

**Comment by Charles-Gagnon** [comment]
Alright. 

Realistically though we shouldn't be having every implementation have their own icons that they use though - especially for common ones like folders. That's kind of the point of codicons - so if their folder icon isn't desirable then I'd say we should probably look into updating that icon instead so we're consistent across the app.

**Comment by SakshiS-harma** [comment]
> Alright.
> 
> Realistically though we shouldn't be having every implementation have their own icons that they use though - especially for common ones like folders. That's kind of the point of codicons - so if their folder icon isn't desirable then I'd say we should probably look into updating that icon instead so we're consistent across the app.

That makes sense. It should be ok to create an issue for this right, since this is going to be a bigger scoped discussion?

**Pull request merged**
