### PR TITLE
Update smoke test repo

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
https://github.com/Microsoft/azuredatastudio-smoke-test-repo

Test build : https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=100253&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=f7e3bacc-79f9-5aef-ec63-f7078932cd4c

### CODE REVIEW

**Comment by alanrenmsft** [comment]
Did I miss something last week? could you please share some context ?

**Comment by Charles-Gagnon** [comment]
I've just been slowly moving over repos that our team uses that are currently in people's private accounts into the official MS org. We can't/shouldn't be using private repos like this.

**Review by kburtram — APPROVED** [review]
Looks good to me.  But I think the CI builds are failing.

**Comment by Charles-Gagnon** [comment]
That was just the Notebook integration tests that Lucy and Vasu are working on fixing right now, all the others passed.

**Pull request merged**
