### PR TITLE
Bumping sqltoolsservice

### PR DESCRIPTION
**Pull request by Benjin**

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@Benjin surprise! 😄 Isn't it fast?

**Comment by Benjin** [comment]
> @Benjin surprise! 😄 Isn't it fast?

So fast, I thought it had to be a mistake!

**Comment by udeeshagautam** [comment]
Some check seemed fail? Can u rerun please.

**Review by udeeshagautam — APPROVED** [review]

**Comment by Benjin** [comment]
> Some check seemed fail? Can u rerun please.

Yup, yup.  Initial failure was an infra failure (network disconnect when trying to pull packages)

**Pull request merged**
