### PR TITLE
Move around scripting utils

### PR DESCRIPTION
**Pull request by aaomidi**
No reason for these to be in electron-browser from what I can see.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
OS puts it under electron-browser? Why wouldn't that be under node? https://github.com/Microsoft/vscode/wiki/Code-Organization doesn't seem to say anything about os specifically

**Comment by Charles-Gagnon** [comment]
Oh misread that - yeah ok that makes sense.

**Comment by aaomidi** [comment]
Oh i didn't even notice that. This was an issue we had before. Anyone got any ideas why that code is here?

Where should we move it?

I need these files to be browser only for exploration.

**Comment by aaomidi** [comment]
I think https://github.com/microsoft/sqltoolsservice/pull/874 is a solution to this. Not entirely sure why we were generating the file paths on the frontend.

**Comment by aaomidi** [comment]
@kevcunnane I'm doing a version bump for the tools service here. Just want to get your sign off for it.

**Comment by aaomidi** [comment]
Going to merge this - if anything happens feel free to revert!

**Pull request merged**
