### PR TITLE
Extensions Gallery Update - December Release

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
sorry, I clicked approve too soon. extension authors are supposed to send PR against extensions/rc1 branch and when we are ready to release, the release DRI will create a PR to merge changes from extensions/rc1 to release/extensions.

**Comment by alanrenmsft** [comment]
it is ok to keep this PR open, we will see people updating this PR when their changes are merged to extensions/rc1 :)

**Comment by Charles-Gagnon** [comment]
What do you mean "send a PR against the branch". What we did last time and works fine is people just commit changes to this branch and then notify the release manager to update the gallery. Having people open separate PRs is just a lot of extra busy work so I don't really see that being necessary.

**Comment by Charles-Gagnon** [comment]
Having the PR open like this makes it easy to see what changes have been made and to get notified when new updates are made to the branch.

**Comment by alanrenmsft** [comment]
that is what we discussed during the tech sync a few weeks ago, changes made to extensions/rc1 need to be reviewed and the build information needs to be provided in the PR description. less error prone and easier to communicate.

**Comment by Charles-Gagnon** [comment]
Closing this since the release process is for people to open PRs against this branch and then RM will merge this in after release.

**Pull request closed without merging**
