### PR TITLE
Fix Gridstack DD import

### LINKED ISSUE #15566: Notebook view is incorrectly importing files from node_modules
The notebook view feature is directly importing files out of node_modules at https://github.com/microsoft/azuredatastudio/pull/13914/files#diff-d76a98d7a465c0d7bb93e5469fa65a08979aebd72e13e9f95c2024a848e15541R12.  Importing like this creates the module loader in webmode and isn't the pattern that we're using for importing modules.

If for some reason the file can't be imported like a typical node module please refer to how slickgrid is loaded as an example of how to correctly bypass the module loader.

### PR DESCRIPTION
**Pull request by dhgrajeda**
This PR fixes #15566

### CODE REVIEW

**Comment by caohai** [comment]
The PR Validation pipeline does not build for web mode. You can manually trigger an Ad-Hoc Product Build and that pipeline will create a docker img for web mode testing.
image

**Comment by caohai** [comment]
I just took a look at the docker img and looks like `gridstack` is missing from `node_modules`. You might also need to add it as dependency in these two files for remote builds.
https://github.com/microsoft/azuredatastudio/blob/main/remote/package.json
https://github.com/microsoft/azuredatastudio/blob/main/remote/web/package.json

For reference: #14227

**Comment by dhgrajeda** [comment]
Thanks @caohai! I got the image running and I think I see the issue now. I will try adding gridstack to those packages.

**Review by kburtram — APPROVED** [review]
LGTM, please confirm that it works by testing the docker image.  thanks!

**Comment by dhgrajeda** [comment]
The docker image seems to be working fine now. Thanks @kburtram!

**Comment by caohai** [comment]
I just took a look at the latest docker img and the gridstack issue is gone👍
@kburtram We do have some files in both this repo and release repo, do we want to keep them in sync? I don't think Daniel has access to that one now.

**Pull request merged**
