### PR TITLE
Links handling in commands

### PR DESCRIPTION
**Pull request by abist**
This PR addresses https://github.com/microsoft/vscode/issues/121211 in ADS

Fix taken from - https://github.com/microsoft/vscode/commit/23e346ab55a317c322a184eab4d10597927cd491

Again the files were different, so I couldn't cherry pick and fixed the issues in different files like vscode did. 

**NOTE: If we are using commands to open links anywhere, we will also need to add the `allowCommands` flag to every `openerService.open` call. This will also need some more testing from the team**

The following files in `sql/*` use the `openerService.open()` call which is now updated. I'm adding the files and the people who worked on it (or area owners) to make sure we don't have breaking changes:

EDIT - only these need attention

- [x] `src/sql/workbench/contrib/modelView/browser/webview.component.ts`: @adbist
- [x] `src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts`: @Charles-Gagnon @chlafreniere 
- [x] `src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts`: @Charles-Gagnon

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
This is likely to break a number of scenarios in our stuff - what's the plan for ensuring that we're testing and verifying all these?

I would probably suggest we make a list of calls to openerService.open and then have area owners come in and verify functionality before signing off (or fixing if needed). This will be especially important if we need to get this in quickly so we don't break key scenarios. 

Did you also check to make sure that these changes are the only ones they've made? (there were no follow up PRs or anything to address missed places or something)

**Comment by abist** [comment]
The following files in `sql/*` use the `openerService.open()` call which is now updated. I'm adding the files and the people who worked on it (or area owners) to make sure we don't have breaking changes:

`src/sql/workbench/browser/modeComponents/hyperlink.component.ts` : @Charles-Gagnon 
`src/sql/workbench/contrib/assessment/browser/asmtActions.ts`:  @vchvlad 
`src/sql/workbench/contrib/charts/browser/actions.ts`:  @alanrenmsft 
`/src/sql/workbench/contrib/extensions/browser/extensionsActions.ts` : ?
`src/sql/workbench/contrib/modelView/browser/webview.component.ts`: ?
`src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts`: @qifahs 
`src/sql/workbench/contrib/resourceViewer/browser/resourceViewerTable.ts`: @Charles-Gagnon 
`src/sql/workbench/services/accountManagement/browser/accountManagementService.ts`: @Charles-Gagnon 
`src/sql/workbench/services/query/common/resultSerializer.ts`: @alanrenmsft 
`src/sql/workbench/services/resourceProvider/browser/firewallRuleDialog.ts`: ?
`src/sql/workbench/update/electron-browser/releaseNotes.ts`: @kburtram

**Comment by Charles-Gagnon** [comment]
@abist I moved your comment into the main description so people can sign off more easily on the changes

**Comment by chlafreniere** [comment]
@abist @Charles-Gagnon if I'm reading this correctly, we'll need to add the parameter in linkHandler.directive.ts; command URIs are valid from notebook markdown cells; from what I can see, vscode made changes in their own notebook implementation to pass in `allowCommands` too. We can chat tomorrow about this.

**Comment by abist** [comment]
@chlafreniere You're right, this is for links with commands. However, it wasn't too straightforward to add this because we do the same thing for commands and links now so might need to change a few changes in functions such as `isSupportedLink` to branch out the logic for hyperlinks and commands.

**Comment by chlafreniere** [comment]
> @chlafreniere You're right, this is for links with commands. However, it wasn't too straightforward to add this because we do the same thing for commands and links now so might need to change a few changes in functions such as `isSupportedLink` to branch out the logic for hyperlinks and commands.

Thanks @abist makes sense that other changes will probably be needed as well.

**Comment by Charles-Gagnon** [comment]
@chlafreniere I added allowCommands for the linkDirectives, we'll only get to that point if the notebook is trusted anyways so this should be safe (and is necessary if we want to continue supporting commands)

**Review by Charles-Gagnon — APPROVED** [review]
Looks good for now - although I'm following up offline with the VS Code folks to make sure that we're handling this in our code correctly. We can do follow-up PRs as needed for that though.

**Pull request merged**
