### PR TITLE
Adds add execution plan button and context menu to the bottom half of the plan comparison screen

### LINKED ISSUE #20742: Add Context Menu/Add Execution Plan Button to at the bottom half of the plan comparison screen
The "Add Execution Plan" button in the top left corner of this screen is not easy to spot. The improvement here would be to add a context menu option and to change the "Add execution plans button to compare" information label to a button.

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #20742 by adding the following things:
1. A new context menu to add an execution plan has been added to the bottom half of the execution plan comparison view
2. A button to add an execution plan has also been added to the bottom half of the execution plan comparison view.

### Before:
image

### After:
image

### CODE REVIEW

**Comment by aasimkhan30** [comment]
Can you please adjust the styling, of it so it looks more like a button?

**Comment by aasimkhan30** [comment]
@erinstellato-ms , should we make the entire bottom half clickable or just the button?

**Comment by erinstellato-ms** [comment]
> @erinstellato-ms , should we make the entire bottom half clickable or just the button?

That's an interesting question.  If the entire bottom half is clickable, then I think folks would expect that they could also just drag a saved .sqlplan file into the window.  If we don't support that, then I think just the button.

**Review by aasimkhan30 — APPROVED** [review]
Looks good to me. We can add icon to the button component as well.

**Pull request merged**
