### PR TITLE
Change how dropdowns get their lengths

### LINKED ISSUE #8202: Database drop-down is too short
Issue Type: <b>Bug</b>

The database dropdown above a script is too short, it is very hard to tell which database I'm selecting - I have to wait until the tool-tip appears for confirmation.

This is because our database are the product, plus the branch name, e.g. _FeatureSet2, suffixed by _Dev, _Review, etc for the environment. So they all are too long to short fully in the dropdown.

More than one user moving from SSMS to Azure Data Studio has commented on this.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

### PR DESCRIPTION
**Pull request by aaomidi**
Not sure if this is a good fix but let's try it anyway.

Fixes #8202

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
This looks like it's just going to affect the values list portion - correct? Not the entire control? Could you post a screenshot of what it looks like before & after?

**Comment by aaomidi** [comment]
Yeah, this will only impact the dropdown list. I was looking at making it change the actual UI but I felt it felt a little janky when the box just suddenly gets larger.

**Comment by aaomidi** [comment]
image

**Comment by anthonydresser** [comment]
Take a look at how vscode is doing this for the select box https://github.com/Microsoft/azuredatastudio/blob/master/src/vs/base/browser/ui/selectBox/selectBoxCustom.ts#L699

**Comment by aaomidi** [comment]
I see what they're doing is basically just another way of going about what I'm doing here. The difference is that theirs will have a side effect of making the input box larger too (because it adds the width control element as a sibling of the select box dropdown), and I don't think we want that.

My change only changes the dropdown.

**Comment by aaomidi** [comment]
image

How it looks in notebooks

**Comment by anthonydresser** [comment]
Theirs doesn't make the inputbox longer, you can check in ads in vscode the debug dropdown. I was mainly talking about how they actually measure the text length rather than use a static 8 px. it a more robust and reliable method of measuring text.

**Comment by aaomidi** [comment]
Yes but it comes with its own problems like hiding it from accessibility software. Do you think the extra code is worth it to get a more reliable text measure?

I can change it to use `em` instead of `px` which would have the desired effect.

**Comment by anthonydresser** [comment]
Hiding what from accessibility software? at the end of the day the width is put on the dom, is just how to calculate the width, a static number or a calculated width. em only helps with set font sizes, but not with things like monospace vs non-monospace fonts, in general em should only be used for text size anyways, not the size of elements.

**Comment by aaomidi** [comment]
They're creating a whole new element alongside the actual selectbox just to use in width control - that would have to be hidden by accessibility software using CSS tricks.

**Comment by anthonydresser** [comment]
they are creating a hidden element to get the rendered size of the text, then removing it. Accessibility doesn't care about it, neither should it, no user ever would know it was there.

**Comment by aaomidi** [comment]
In the code snippet you sent above they never remove it

**Comment by anthonydresser** [comment]
O sure in that instance they are using a static one that they just replace the contents of, since they don't want to create an element every time they want to measure something.

But they aren't using the element to show anything to the user, so it has no accessibility implications.

**Comment by kburtram** [comment]
@anthonydresser @aaomidi is this the correct fix?  Or should we do this a different way?  It would be nice to get this bug fixed.

**Comment by aaomidi** [comment]
@kburtram I'm not sure, I believe adding & maintaining extra code to get exact lengths for a dropdown doesn't really make sense - especially for this scenario.

**Comment by anthonydresser** [comment]
Getting the length of text by measure it's rendered length is the only real way to know how long text will be, there are lots of difference css stylings that can change the length of text. We do it several other places so it's not like doing it here will be novel.

**Comment by aaomidi** [comment]
I'll go ahead and make a new PR but I still think we shouldn't be adding extra code to get exact lengths here - we're not dealing with mission critical stuff essentially and more code - especially adding elements to the dom has a bunch of consequences we might have to deal with later.

**Comment by aaomidi** [comment]
Closed in favor of #8356

**Pull request closed without merging**
