### PR TITLE
Notebook Views Actions fix for ADS Web

### LINKED ISSUE #16679: html-to-image breaks web mode
Steps to Reproduce:

1. Download the web docker img and launch a container.
2. Open the web endpoint in the browser
3. Check the network tab of dev too and the request for html-to-image shows 404

image

Root cause:  
The js mapping is not correctly set.
https://github.com/microsoft/azuredatastudio/blob/32c6a19e72fc3ef87a38f2930bae328ce7a78de1/src/vs/code/browser/workbench/workbench.html#L63

### PR DESCRIPTION
**Pull request by dhgrajeda**
This PR fixes #16679

I am removing the html-to-image library for now. I need more time to debug this for ADS Web. This feature is not yet public, so it doesn't affect any users. 

Verified that the Web Build docker image loads ADS Web properly.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Out of curiosity - what was the issue with that package?

**Comment by dhgrajeda** [comment]
> Out of curiosity - what was the issue with that package?

@Charles-Gagnon - I'm not sure yet. I am getting an error when the library loads, but I can't recall the exact error right now. I may not have loaded the library properly. I just setup a VM to debug ADS Web. I'll know more later today when I get a chance to debug it.

**Comment by caohai** [comment]
@dhgrajeda Is there any reason not reverting the whole commit? I assume this PR will leave some of the Notebook Views Actions code not being used.
Personally I think this intermediate state might make things a bit complicated when you want to add this feature back later. But it's up to you if you think this approach is better.

**Comment by dhgrajeda** [comment]
> Personally I think this intermediate state might make things a bit complicated when you want to add this feature back later. But it's up to you if you think this approach is better.

@caohai - Removing this package only prevents thumbnails to be generated for one of the actions. I think it makes more sense to leave the actions, which are still usable, and just not have the thumbnails for that particular action while I find a solution. The thumbnails are very useful but not essential for that particular use case.

**Review by caohai — APPROVED** [review]

**Pull request merged**
