### PR TITLE
Bump Service Downloader

### PR DESCRIPTION
**Pull request by anthonydresser**

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Thanks for taking care of bumping this!

**Comment by anthonydresser** [comment]
Just an update on this, @Charles-Gagnon discovered the changes he made to the service-downloader don't support tars for linux and mac so this is on hold till we solve that problem and update the package again.

**Comment by anthonydresser** [comment]
@Charles-Gagnon is this PR good to go?

**Comment by Charles-Gagnon** [comment]
Looks good to me - if you're happy go ahead and merge it in

**Pull request merged**
