### PR TITLE
Fix for database name in connection details after changing database

### PR DESCRIPTION
**Pull request by smartguest**
Generates new profile ids for non purpose (dashboard/connection etc) type uris such as those for Query Editor or Edit Data. This is to allow for the code to retrieve the correct profile with the right URI such as get current connection string (which expects to look up the profile via ID alone which it is currently not possible) while also allowing for connection and dashboard uris to share the same profile with the same ID (changing the profile ID for every addition of the same connection breaks loading with the connection profile in object explorer, so they will have to remain the same).

Additionally, this makes a change to the UntitledQueryEditorInput or EditDataInput so that it will disconnect the original connection to the database (made when attempting to run a select statement or edit data on a database), as it was observed that the URI for the editor has changed from that of the initial connection, causing the entry not to be deleted from connection status manager when the editor is closed.

GIF of the fix in action:
ChangeDBConnectionStringInAction

GIF of the fix on the base server before connecting (to demonstrate that it works in that scenario):
ChangeDBConnectionStringBaseServer

Addresses #6406

### CODE REVIEW

**Comment by smartguest** [comment]
Connection ID generation has been added to the scriptingUtils file in order to differentiate between the existing dashboard connection and the editor connection (they are counted separately in the connection status manager, so the ids must be different for the check to work, otherwise it's indistinguishable from the dashboard entry).

**Review by cheenamalhotra — APPROVED** [review]

**Comment by cheenamalhotra** [comment]
@alanrenmsft would request your review, since this change mainly applies to Query Editor area.

This is an important change to address connection reliability issues when working with azdata APIs.
It would be good to bring it in the next release.

**Comment by alanrenmsft** [comment]
IIUC, most of the changes are to dispose the original connection when the editor is disposed. I think the correct behavior is to dispose the connection when the event happen, so that this is done in one centralized location. The event I can think of that you should test includes: change database, change connection, save untitled to a file and save as.

**Comment by smartguest** [comment]
@alanrenmsft The disconnect connection isn't really the main fix for the issue it's to address another issue that co-exists with this one.

The actual fix is on this line: https://github.com/microsoft/azuredatastudio/pull/22376/files#diff-ec778410f6b6fdc9a6d158980959b3478e30964e6dcad4551b09a152a635a7a8R102

The disconnect connection is meant for cleaning up a brand new connection that is created here:

when we open up an untitled SQL editor input on a non master database but does not get cleaned up once you close the editor (it closes only the editor uri, but not the initial connection), once the editor is closed, there is no need for this connection anymore, so it has to be disposed along with the editor.

If we try to disconnect the connection when we change the database (including master), we end up closing the main underlying connection by accident and aren't able to continue further

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
