### PR TITLE
Fire onDidSelect event when selecting event from code

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
This is fixing an issue I found when adding the value provider. 

The issue here is that when we select an item by calling select it sets the value on the HTML input element directly - but this doesn't fire the 'change' event and so it never fires the onDidSelect event. I noticed this when setting new values for a dropdown - we'd not get notified until selecting a new item from the UI.

This behavior doesn't seem right to me - I would expect that whenever the value changed (either by user interaction or programmatically) I'd get informed through the event of that happening. 

I could fix this in the vs code layer but I try to avoid that when I can and this should cover all the scenarios that we care about.

I'm still unsure on this approach though - I feel like it may be overloading the meaning of "did select". Some people may take that as only when the USER specifically selected something - and not a value being selected because of other reasons. And so one other thought I had was to add a new event instead onDidValueChange that would fire both when the user selected an item and when it was selected programmatically. 

Any thoughts or preference on this one way or another? 

(I also intend to look at the editable dropdown too - although that's a lot more custom so we may not have the same issue there)

### CODE REVIEW

**Comment by ranasaria** [comment]
I like the idea of add a new onDidValueChange event that will fire when the value changes in any way and leaving onDidSelect to fire when a user makes a selection.

**Comment by Charles-Gagnon** [comment]
I'm slightly leaning that way as well - but if we did that then I think we'd want to have that even be fired whenever onDidSelect was also fired. And it seems a little odd to have two events firing at the same time - but I think as long as we document it enough that would be fine. Then callers can just choose which one they hook in to based on what their needs are.

It would definitely be the safer approach which appeals to me as well.

**Review by alanrenmsft — APPROVED** [review]
I prefer to fire the event regardless of what triggered it. and if I understand correctly, you have to introduce an event here because you don't have access to the event emitter in the base class. that also sounds fair enough to me.

**Comment by Charles-Gagnon** [comment]
Thought about it a bit more and while I could see the separate events being useful I think that firing the event any time the value changes I don't really think there's a scenario where we care about the difference between a value changing because a user selected it and it being selected programmatically. So I'm going to leave this as it is with overriding the event and we can always change it later if we decide that it's worth it.

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 I had to make some fixes to the import wizard to correctly handle this - the code wasn't checking that value was actually defined (all dropdown values might be undefined if there isn't anything to select). Could you look it over?

**Comment by Charles-Gagnon** [comment]
I'm not too concerned with this kind of stuff breaking functionality either in general. It might result in some errors that otherwise wouldn't have shown up but because these are done in an event callback those shouldn't affect the overall application as long as a valid value is selected eventually.

**Review by alanrenmsft — APPROVED** [review]

**Review by aasimkhan30 — APPROVED** [review]

**Pull request merged**
