### PR TITLE
Fix KEY_UP Eventing in Link Callout Dialog

### PR DESCRIPTION
**Pull request by chlafreniere**
Addresses #15167.

I'm not a huge fan of this solution, but I haven't found a better way to do this. Any suggestions welcome 😄.

In actionbar.ts, it handles both KEY_DOWN and KEY_UP events. I checked the past 3 releases, and this functionality is broken in all of those releases while in split/md mode, so I'm fairly convinced that this has just never worked.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
It feels like we should only be handling one of those events for most things, so this might more be an issue with actionbar (or is this in the VS Code)? Where are the two different events being handled that's causing the problem?

**Comment by chlafreniere** [comment]
> It feels like we should only be handling one of those events for most things, so this might more be an issue with actionbar (or is this in the VS Code)? Where are the two different events being handled that's causing the problem?

It's in actionbar:
https://github.com/microsoft/azuredatastudio/blob/ba6bfbb6145ea38770a08bad9cffb588c1582f4e/src/sql/base/browser/ui/taskbar/actionbar.ts#L101

https://github.com/microsoft/azuredatastudio/blob/ba6bfbb6145ea38770a08bad9cffb588c1582f4e/src/sql/base/browser/ui/taskbar/actionbar.ts#L73

One of my goals was to keep this change localized as much as possible, given that we're in ask mode. Not sure if that can be accomplished changing actionbar itself (the file hasn't been touched in ~7 months) 🤒

**Review by lucyzhang929 — APPROVED** [review]

**Comment by chlafreniere** [comment]
@Charles-Gagnon any thoughts here?

**Review by Charles-Gagnon — APPROVED** [review]
Ok, this seems fine as a targeted fix. But we should definitely file an issue and come back and look at this for fixing up better. What I'd like to look at is to remove the actionbar handling stuff on key-up. In general I don't know of a good reason why we would want to be doing that anyways and doing so has already caused problems like this. 

We also sorta have an issue here where the actionbar isn't updating its focused item properly when the dialog is closed since we manually set the focus to the original element. So that's why it's using the list action instead of the link action like I would normally expect it to...but it'd still be broken regardless even if we fixed that since it'd just cause it to open the dialog again so not really a huge concern at the moment.

**Comment by chlafreniere** [comment]
#15484 to track investigating removal of KEY_UP listener.

**Pull request merged**
