### PR TITLE
Filter out high frequency command events

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Just type for now but going to keep an eye on these to make sure we're not sending up a huge amount of requests.

### CODE REVIEW

**Comment by abist** [comment]
Is ['type'] a high frequency event for typing? If yes, then we should maintain a constant list of all high frequency events in the file

**Comment by Charles-Gagnon** [comment]
@kburtram Basically. It doesn't get sent for every keypress but it fires off every half a second or so if you're typing in the editor.

@abist I don't understand your comment. ['type'] is the list, it just has a single item in it right now because I don't know of any other commands that are fired off enough to warrant exclusion here.

**Comment by abist** [comment]
@Charles-Gagnon I would suggest having a const list called "highFrequencyEvents" and then use that const for the registerCommand so we don't have to edit that list in place every time.

**Comment by Charles-Gagnon** [comment]
What benefits does that bring? You would still have to modify the list at some point if you wanted to add more. I don't see this list being used anywhere outside of this one check so making a separate var for it doesn't seem to bring any value.

**Comment by abist** [comment]
That's the point of a constant, you change it at the top of the file instead of looking for "type" or other known high frequency events in the file every time you want to change the list or use it elsewhere.

**Pull request merged**
