### PR TITLE
Fix db nodes expanding to server-level connection

### LINKED ISSUE #6497: New bdc explorer renders sql object tree incorrectly.
Issue Type: <b>Bug</b>

I just connected to a BDC controller endpoint & tried to browse the tree.

bdc-tree

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (6064904151d2ac3b3b6c84f25b890baa20ef43fe, 2019-07-24T22:21:08.135Z)
OS version: Windows_NT x64 10.0.18941

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0
sql-vnext|Mic|0.14.1

</details>

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #6497

Not sure on the context of why this was necessary to begin with, functionality in data explorer trees works as expected without this extra logic. It's likely due to the change I made a little while ago that set all connection node children requests to be at the server level instead of the db level, which would have likely resulted in the nodes here being expanded to the db-level and thus appear to behave correctly. 

Tested with both CMS and BDC views

image

image

### CODE REVIEW

**Comment by abist** [comment]
This will introduce a bug throughout data explorer where context menu actions would always default to master

**Comment by Charles-Gagnon** [comment]
@abist Thanks - let me look into it. Neither behavior is ideal =)

**Comment by abist** [comment]
I'm not sure but Github shoes 0 files changed?

**Comment by Charles-Gagnon** [comment]
Yeah - this isn't going to be necessary anymore. I'm going to just reverthttps://github.com/microsoft/sqltoolsservice/pull/829 to fix this for two reasons :

1. To fix this fully is going to involve adding a lot more custom logic to handle updating the connection correctly when under a DB node
2. There are already numerous complaints about reverting that behavior so I was planning on doing that at some point anyways #6394

**Pull request closed without merging**
