### PR TITLE
make books viewlet only available in insiders

### PR DESCRIPTION
**Pull request by MaddyDev**

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
And actually - why not just have this not included in stable builds to begin with? That'd be a lot simpler way to handle it IMO.

https://github.com/microsoft/azuredatastudio/blob/7eba8c4c03fa6077f9f04d466b8df34da04354b9/build/lib/extensions.ts#L242

(although I question the logic for this check since the comment doesn't seem to match what the logic is actually checking)

**Comment by kburtram** [comment]
@MaddyDev I'm assuming we want this for the September release, correct?

**Comment by MaddyDev** [comment]
@yualan Do we need this for September release? I thought we wanted the books view-let as insiders only, please confirm.

**Comment by kburtram** [comment]
Currently the Jupiter Books viewlet is enabled by default in the September stable build release candidate.  I assume if we are disabling the viewlet in stable builds from master, we likely don't want to ship it as "on by default" in September, correct?

**Comment by kburtram** [comment]
...looks like @chlafreniere already opened a bug to track https://github.com/microsoft/azuredatastudio/issues/7054.  We can merge this PR to the release branch once it's complete.

**Comment by kburtram** [comment]
@MaddyDev this is the last known bug that is blocking the September release at this time.  Is there an update to this PR coming soon?

**Comment by MaddyDev** [comment]
@kburtram Am working on the comments. Will complete it first thing tomorrow.
@Charles-Gagnon Am looking into how I can use the IEnvironmentService.appQuality to bypass the open book commands. Do you know of a quick way to do this?

**Comment by MaddyDev** [comment]
@Charles-Gagnon  That's actually not a ship-blocker, if you can sign-off on this, i'll create another issue for this and work on it.

**Comment by MaddyDev** [comment]
Thanks @Charles-Gagnon!
@kburtram Can you please merge this to release. Sorry about the delay, Thanks.

**Comment by MaddyDev** [comment]
Fix for #7054

**Pull request merged**
