### PR TITLE
update kusto to 0.3.2

### PR DESCRIPTION
**Pull request by gupta1**
This PR fixes #
Build link: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=83144&view=results

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Ping me or @alanrenmsft when you have the new build and we'll get this merged in and gallery updated.

**Comment by gupta1** [comment]
> Ping me or @alanrenmsft when you have the new build and we'll get this merged in and gallery updated.

Yes, this particular build finished https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=83144&view=results
and I have tested the kusto vsix file.

**Comment by alanrenmsft** [comment]
@gupta1 as per the new process, please include the link to the build.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon, I'll handle this one.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@gupta1 the changes have been published to rc1 extension gallery, please verify.

**Pull request merged**
