### PR TITLE
ok button target fix

### PR DESCRIPTION
**Pull request by aaomidi**
Issue #9079

### CODE REVIEW

**Comment by kburtram** [comment]
@anthonydresser was this fix fine for release/1.16?  I didn't see where the discussion landed for this fix?

**Comment by anthonydresser** [comment]
as a release targeted fix, i dont have any issues with this.

**Comment by aaomidi** [comment]
The label Approved is required for using this command.

**Comment by aaomidi** [comment]
Merging PR based on approval from @kburtram

**Pull request merged**
