### PR TITLE
Update extensionsGallery.json for ML 0.11.0

### PR DESCRIPTION
**Pull request by llali**
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3341137/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.11.0.vsix

### CODE REVIEW

**Comment by llali** [comment]
@v-srinisa, can you please help me check in this for the release? I'm not sure why the validation fails

**Comment by Charles-Gagnon** [comment]
@llali Please merge in the latest from the rc1 branch. I ported over a fix there for this issue

**Comment by llali** [comment]
@Charles-Gagnon would you have access to merge this please?

**Comment by v-srinisa** [comment]
gallery updated

**Pull request merged**
