### PR TITLE
[SQL Migration] Release v1.4.0 to Insiders

### PR DESCRIPTION
**Pull request by raymondtruong**
This PR updates the insiders extension gallery to the latest version of the SQL Migration extension. The main change here is the decoupling of the migration extension from STS, where we instead now use our own dedicated Migration service - see https://github.com/microsoft/azuredatastudio/pull/21781

+@aasimkhan30 to verify that no special changes are needed in the extension galleries with this new change.

Link to `Azure Data Studio - Extensions` pipeline run off `main` containing vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=189857&view=results

### CODE REVIEW

**Review by aperfilev — APPROVED** [review]
LGTM

**Comment by alanrenmsft** [comment]
@raymondtruong the size of the package has increased, could you please confirm it is expected?
image

**Comment by raymondtruong** [comment]
> @raymondtruong the size of the package has increased, could you please confirm it is expected? image

@alanrenmsft will look into it, but our team had done thorough signoff on Aasim's changes last week so functionally we're happy with what we have.

@aasimkhan30 any idea off the top of your head why it may have increased? I know we moved all the contract definitions and stuff into the extension now which may explain it, but can't think of anything else that may have contributed ~0.5 mb of extra size.

**Comment by alanrenmsft** [comment]
@raymondtruong I am going to merge the PR since the functionality works as expected. you can open a new PR if you need to remove anything from the package.

**Pull request merged**
