### PR TITLE
Adding light contrast theme

### PR DESCRIPTION
**Pull request by aasimkhan30**
Issue: #19865

Image:
image

Query Editor:
image
Query Plan
image
Notebook
image
Dashboards:
image
image
image
Edit data 
image
Dialog
image
Wizard
image
Marketplace:
image
Table Designer:
image
Azure Pane:
image

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@aasimkhan30 Thanks for making the fix. could you please add more screenshots that covers all the UI components?

**Comment by aasimkhan30** [comment]
@alanrenmsft, I am still adding css rules. It is a WIP. I will add screenshots after I am done.

**Comment by aasimkhan30** [comment]
Will convert this to a draft PR

**Comment by aasimkhan30** [comment]
Azure pane icons are not visible:
image

**Comment by aasimkhan30** [comment]
@alanrenmsft, screenshots added.

**Comment by alanrenmsft** [comment]
@aasimkhan30 does it automatically switches to the corresponding high contrast themes in ADS when you change the Windows theme?

**Comment by alanrenmsft** [comment]
is Azure view the only remaining issue now?

**Comment by aasimkhan30** [comment]
@alanrenmsft , it does automatically switch to light contrast theme and azure viewlet is the only issue right now.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
please update the azure pane screenshot.

**Comment by aasimkhan30** [comment]
@alanrenmsft added screenshot

**Comment by aasimkhan30** [comment]
@alanrenmsft, azure icons in connections pane are still broken
image
Created a vscode PR for it:
https://github.com/microsoft/vscode/pull/175925

**Comment by alanrenmsft** [comment]
@aasimkhan30 go ahead.

**Pull request merged**
