### PR TITLE
update STS to 4.0.0.14

### PR DESCRIPTION
**Pull request by kisantia**
This PR brings in a DacFx update that addresses #19656. 

Other STS commits being brought in with this update @Charles-Gagnon @benrr101
image

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@alanrenmsft @kburtram Thoughts on the stuff that @benrr101 did? We probably should have waited until post-release just for reducing chance of regressions, but in general I feel like the stuff he did is safe so it's not worth rolling back temporarily.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by llali — APPROVED** [review]

**Comment by alanrenmsft** [comment]
> @alanrenmsft @kburtram Thoughts on the stuff that @benrr101 did? We probably should have waited until post-release just for reducing chance of regressions, but in general I feel like the stuff he did is safe so it's not worth rolling back temporarily.

@Charles-Gagnon I think the changes are safe, but since most of the testing has been done already, I am hesitant to reset the test status. maybe we should fork a branch and release from it?

**Comment by kisantia** [comment]
I'll close this PR since we discussed in DRI today that we will create a separate release branch in STS to not take in the additional commits that aren't needed to fix this bug.

**Comment by alanrenmsft** [comment]
this should still go to ADS main, the ADS release branch will be updated directly with new STS version from a release branch.

**Pull request closed without merging**
