### PR TITLE
Replace Axios calls with HttpClient

### LINKED ISSUE #21837: Proxy authentication doesn't complete for AD users
_Received this issue internally, posting here for follow-up and tracking_
**[Needs investigation]**

- Azure Data Studio Version: 1.40.2 (yet to confirm with 1.41.1)
- OS Version: Windows 11

Steps for application login as below.
1. User launches azure data studio
2. User initiates connection by providing login information
3. User click on add account
4. Above step launches browser to provide your azure portal ID and password

Once password is entered next step would be that browser will show the authentication is successful and it would let us to proceed with connect button on Azure Data Studio, to access database, but instead the authentication never proceeds to authentication successful message. Tried on non-hardened and no CyberArk server that just has base image and I see similar issue but on a different window, on step 4 above the authentication successful message comes up on chrome but connection to database doesn't complete.

### Further notes

- If I launch ADS with my userid logged into the server the authentication process never completes
- I login to server with my userid and launch ADS using runas as a different user and if I use a ID that is local to the server. The runas ID could be with or without admin privileges on server and I could launch and sign into ADS successfully.
- I login to server with my userid and launch ADS using runas as a different user and if I use an active directory ID. The runas AD ID could be with or without admin privileges on server and I may or may not be able to login successfully to ADS.
- I login to the server via RDP using local IDs where possible in second point but don’t use runas and I could launch and sign into ADS successfully.
- I login to the server via RDP using AD IDs where possible in third point but don’t use runas and I could launch and sign into ADS successfully on some IDs which is exactly the same IDs that couldn’t sign into ADS on the second point.

Just for clarity my userid is active directory that I use to RDP to the server where we have installed ADS. I deleted the profiles of affected IDs with no luck fixing authentication issue.

### VS Code comparison

- Issue is reproducible with VS Code's Azure Account extension.
- Issue is NOT reproducible with VS Code's Microsoft Authentication provider.

### PR DESCRIPTION
**Pull request by cssuh**
Old Behavior: used axios to make get/post request calls

New Behavior: use HttpClient to make get/post request calls, since axios does not officially support proxy

Fixes #21837

### CODE REVIEW

**Review by cheenamalhotra — APPROVED** [review]

**Review by kburtram — APPROVED** [review]

**Comment by cssuh** [comment]
@Charles-Gagnon the rest of the axios calls are for the ADAL library which is getting deprecated, and we plan to remove it completely by June/July.

**Comment by Charles-Gagnon** [comment]
That doesn't seem to be completely true, the main one I'm looking at is https://github.com/Microsoft/azuredatastudio/blob/86c3f315f22be13e1456ead6423f3c9f1a8aea39/extensions/azurecore/src/azureResource/utils.ts#L342

which is used by a number of helper functions, such as [getManagedDatabases](https://github.com/Microsoft/azuredatastudio/blob/86c3f315f22be13e1456ead6423f3c9f1a8aea39/extensions/azurecore/src/azureResource/utils.ts#L456). These calls are for fetching lists of Azure resources so are independent of the auth method being used.

**Comment by cssuh** [comment]
Ok seems like it will need to get replaced there as well

**Comment by cssuh** [comment]
https://github.com/microsoft/azuredatastudio/issues/22431 I created this issue to track it

**Pull request merged**
