### PR TITLE
Update Kusto extension to 0.3.2 in Insiders marketplace

### PR DESCRIPTION
**Pull request by gupta1**
This PR fixes #
Build link: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=83144&view=results

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@gupta1  this also needs to be released for Nov release, right?

**Comment by alanrenmsft** [comment]
@gupta1 please update this PR: https://github.com/microsoft/azuredatastudio/pull/13223 to include your extension update for Nov release.

**Review by JustinMDotNet — APPROVED** [review]
Looks good

**Comment by gupta1** [comment]
> @gupta1 this also needs to be released for Nov release, right?

Yes, @JustinMDotNet and I are testing few things before pushing it.

**Comment by gupta1** [comment]
> @gupta1 please update this PR: #13223 to include your extension update for Nov release.

Will do once we are done testing it.

**Comment by alanrenmsft** [comment]
@gupta1 , please follow the new process as we chatted today: https://github.com/microsoft/azuredatastudio-docs/blob/main/Guides/UpdateExtensionGallery.md

**Comment by alanrenmsft** [comment]
ping me if you have any questions.

**Comment by Charles-Gagnon** [comment]
@gupta1 I put this in the other PR - but where is this VSIX coming from? We should only be releasing VSIXs that come from official pipeline runs on the main/release branch but I don't see the version updated to 0.3.2 in those yet.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
published to insiders extension gallery, please verify @gupta1

**Pull request merged**
