### PR TITLE
Apply title bar adjustment to edit data

### LINKED ISSUE #5754: Edit Data has a blank gap under the toolbar
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run Edit Data on a table

Expected: UI doesn't have large blank gaps

Actual: Screenshot below

image

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes  #5754

@kburtram  can you help me verify this?

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Still a couple of issues around resizing :

screen

1. The bottom part of the grid can be hidden behind the taskbar with no way to scroll down to see what's there (which importantly is the "null" new row most of the time)

Note that while this exact issue doesn't appear in 1.7 (the scrollbar shows up as expected) it appears there was a separate bug where it wouldn't let you scroll down to the end 

screen

2. Resizing the window causes the top to collapse and the title bar to be hidden

So while at least we don't have that huge gap it'd be good if we could fix these other issues too

**Comment by anthonydresser** [comment]
@Charles-Gagnon could you checkout to cf8f8907ee0bd8d492f8ebab2a21e26858d30715 and verify which of these repro there? I want to prioritize issues that are new from the custom menu bar

**Comment by Charles-Gagnon** [comment]
1. Same as above in the 1.7 release, the scrollbar appears but it never actually lets you scroll to the bottom (keeps jumping up one row)

2. This is a new issue, it behaves correctly in previous versions

**Comment by anthonydresser** [comment]
@Charles-Gagnon I reworked the layout method and it should fix the bugs you pointed out.

**Pull request merged**
