### PR TITLE
Fixes the high CPU usage

### PR DESCRIPTION
**Pull request by aaomidi**
https://github.com/microsoft/vscode/issues/81535

https://github.com/microsoft/vscode/commit/080a1fa86fa42efee6a9e3cd0a5b9ca320f0090f

### CODE REVIEW

**Comment by anthonydresser** [comment]
We'll get this change tonight as part of the vscode merge

**Comment by kburtram** [comment]
@anthonydresser @aaomidi I think it's fine to wait for the merge if we expect it to get in EOD.  Otherwise, I'd recommend taking the fix by itself to make sure tomorrow's insider build is in good shape.  Thanks!

**Comment by aaomidi** [comment]
@anthonydresser Thanks! I'll close this PR once the merge is finalized :)

**Comment by anthonydresser** [comment]
If the change is the exact same as vscodes there shouldn't be any issues taking this

**Comment by kburtram** [comment]
@aaomidi do we need this any more?

**Comment by aaomidi** [comment]
Nope! We're good now :)

**Pull request closed without merging**
