### PR TITLE
Add to gallery "Extra Sql Script As" extension

### PR DESCRIPTION
**Pull request by pacoweb**
Add the new "Extra Sql Script As" extension to the extensions gallery

### CODE REVIEW

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
The changes here look good but your extension is missing a couple of things : 

1. You should have an icon field in your package.json pointing to the extension icon so it shows up in the gallery view 
2. You should have a license field in your package.json pointing to the license file in your repo

See https://github.com/microsoft/azuredatastudio/blob/main/extensions/arc/package.json for an example

**Comment by pacoweb** [comment]
Hi @Charles-Gagnon 

Updated package.json, generated new vsix and updated version on gallery files (f3f7d37)

Thanks

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by pacoweb** [comment]
Thanks!

**Comment by Charles-Gagnon** [comment]
Gallery has been updated, thanks for your contribution!

**Pull request merged**
