### PR TITLE
Updating server group colors

### PR DESCRIPTION
**Pull request by aasimkhan30**
UX diagram
image

Now:
image
image

Before:
image

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
TIL that we allow overriding server group colors. Is that documented anywhere?

The change looks fine, but where did this ask come from? Some a11y feedback?

**Comment by alanrenmsft** [comment]
I was about to ask the same question :)

**Comment by Charles-Gagnon** [comment]
Was the mockup an actual suggestion or just example colors to use? It just seems surprising to change these colors after years of having them as the current set.

**Comment by alanrenmsft** [comment]
I'd recommend not to update the colors:
1. These colors already meet the contrast ratio requirements.
2. If you update the colors, when user edit existing server group, no color will be selected, not a huge problem but may cause confusion.

so unless there is a compelling reason...

**Pull request closed without merging**
