### PR TITLE
Dev/brih/features/feedback support request buttons

### PR DESCRIPTION
**Pull request by brian-harris**
This PR fixes #
* adding new images for Feedback and support request buttons and Feedback rating stars
* add feedback button / dialog to sql migration main page
* adding feedback as an action Telemetry event
* add support request button to sql migration main page and migration cutover/details page 
** note: button is currently hidden until support topics can be created
* fix error notification when sql migration fails to start

Feedback button on main page
image

Feedback dialog
image

Feedback sent notification
image

(currently hidden) New service request button when visible on SQL Migration main page
image

(currently hidden) New service request button on migration cutover/status page:
image

Error notification bug fix:
image

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@brian-harris  I noticed there is no approval on this PR and also, the validation builds didn't finish. any reason you have to merge this PR without waiting for these?

**Comment by brian-harris** [comment]
Hi Alan, the check-in was unexpected.  I thought the PR would gate the merge when I was wanting to merge latest into my branch.

**Comment by alanrenmsft** [comment]
are you planning to revert this commit?

**Comment by brian-harris** [comment]
yes, I will

**Comment by Charles-Gagnon** [comment]
@brian-harris How did you merge in this PR? Somehow it looks like you managed to bypass the squash merging but that shouldn't be possible 🤔

**Pull request merged**
