### PR TITLE
added markdown renderer for publish dialog

### PR DESCRIPTION
**Pull request by abist**
Added a markdown renderer inside the publish changes dialogs. I tested out with test markdown strings myself.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
screenshots for
1. different themes
2. different length (both width and height) to observe the scroll behaviors

**Comment by caohai** [comment]
Can you add screenshots for:
1) what a markdown string looks like in the publish changes dialog
2) what the current plain text content looks like in the publish changes dialog (this is just to make sure merging this change won't break the current text implementation as I haven't started the markdown string generation yet)

**Comment by abist** [comment]
@alanrenmsft @caohai 

Plain text in the markdown renderer - 
Screen Shot 2022-03-04 at 2 49 35 PM

Markdown string I formatted myself with the same text in both themes -
Screen Shot 2022-03-04 at 3 27 20 PM
 
Screen Shot 2022-03-04 at 3 27 44 PM

**Comment by Charles-Gagnon** [comment]
1. Why is "Supporting Actions" indented differently than the rest?
2. The entries under "User actions" appear to be trying to use a format string but not actually doing the replacement (they have {0} in them which appears to be the name of the table that appears at the end of the string). Is this intended?

**Comment by abist** [comment]
@Charles-Gagnon 
1. Yes
2. Yes, the current string that I added is'nt markdown. I just added some formatting to show it works.

Yes, but @alanrenmsft and @caohai can elaborate on the backend part.

**Comment by alanrenmsft** [comment]
I thought you have merged this one on Friday, after that I created another issue and assigned it to @caohai https://github.com/microsoft/azuredatastudio/issues/18650, you guys can decide how to proceed. I think it would be beneficial to support different formats which gives more flexibility.

**Comment by abist** [comment]
@alanrenmsft I need PR approval for it

**Review by alanrenmsft — APPROVED** [review]

**Review by caohai — APPROVED** [review]

**Pull request merged**
