### PR TITLE
Bump extension versions (#8674)

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
cherry picked from commit 9587edd8673ae636df247a071f8cf6f38e6acaa2

### CODE REVIEW

**Comment by kburtram** [comment]
Merging to port to release/1.14 for the next build.

**Comment by kburtram** [comment]
Oh, this is against release/1.14, so I'll port to master assuming it's not already there.

**Comment by Charles-Gagnon** [comment]
@kburtram It's already in master - I realized after I could have just sent you the commit to cherry pick yourself but figured I had already done the work so just left this one as is

**Comment by Charles-Gagnon** [comment]
And yes - I'll update the extensions gallery.

**Pull request merged**
