### PR TITLE
Fix hygiene/compile issues (release/1.26)

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes the hygiene issues that are stopping the CI builds from completing

It looks like these were fixed in main with the vs code merge so that's why we aren't seeing them there.

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
@Charles-Gagnon thanks for fixing!  It looks like there are some build breaks in the CI that may need to be fixed prior to merging.

**Comment by alanrenmsft** [comment]
oh man, why do we have all these issues? the 1.26 doesn't have vscode merge. right?

**Comment by Charles-Gagnon** [comment]
Correct. The vs code merge solved these for main.

I wonder if the electron bump is causing this. It's the only thing I can think of that's gone in that would have had this kind of widespread impact - although I don't know why that would be breaking this stuff in particular.

**Comment by kburtram** [comment]
@Charles-Gagnon yeah, this is weird.  I didn't need to do all this in release/1.25 when we took the electron bump there.  But I did have to do a lot of this stuff in main for the merge.  Let me double check the previous commits to verify nothing unexpected went in.  This is the type of thing we see when bumping typescript version, or something like that.

**Comment by kburtram** [comment]
@Charles-Gagnon now that I think about it, it's likely bumping the dev dependency version of Electron that caused all these breaks.  In release/1.25 I just bumped the runtime version.  I guess it's worth working through this issues (vs. rolling back the dev dependency bump).  Please let me know if you'd like me to take over fixing these issues.

**Comment by Charles-Gagnon** [comment]
That sounds reasonable - thanks for looking into it.

I think this last set of changes should do it, I'll ping you if I think I need additional help.

**Comment by kburtram** [comment]
@Charles-Gagnon I'm sure you can fix.  Just don't want to waste your time cleaning up my breaks. 😄 Thanks!

**Comment by Charles-Gagnon** [comment]
Alright, finally got everything compiling + tests passing. If you could take another quick look this should be ready for merging in!

**Review by chlafreniere — APPROVED** [review]

**Pull request merged**
