### PR TITLE
Edit Data Refresh PR

### PR DESCRIPTION
**Pull request by smartguest**
This PR addresses the add new row functionality such as hitting enter at the new row, makes commits when changing to a new row, fixes tab navigation, and finally adds features such as saving for dirty states upon closing (and saving cells in general). It also adds the function to preserve the last entered value in case of switching tabs or after an invalid edit and has general improvements to recovering from invalid edits.  It also fixes the restore view state callback by disabling dispose on the grid until the Edit Data input is actually destroyed. Screenshots and more will come later.

Issues fixed will be listed below:

### CODE REVIEW

**Comment by alanrenmsft** [comment]
have you tested the changes using the test cases you created?

**Comment by smartguest** [comment]
@alanrenmsft Will do after lunch this afternoon.

**Comment by alanrenmsft** [comment]
please include me in the test meeting.

**Comment by kburtram** [comment]
@smartguest should we close out this older PR since I think it will still need a bit of work to get merged?  We can reopen later if we pick this back up.

**Comment by smartguest** [comment]
Yeah it should @kburtram

**Pull request closed without merging**
