### PR TITLE
Updating migration extension in insiders

### PR DESCRIPTION
**Pull request by aasimkhan30**

### CODE REVIEW

**Review by abist — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@aasimkhan30 looks like you are not following the extension release process, you are sending this PR before the vsix is actually is produced, latest product build still has the 0.0.9 version
image

**Comment by aasimkhan30** [comment]
@alanrenmsft, this is a private preview extensions. AFAIK, this does not have to follow the release process because of how frequently it gets updated and its target audience.

**Comment by alanrenmsft** [comment]
@aasimkhan30 release more frequently is totally fine, but where is the vsix file? as per the release process, you need to provide a link to the build in the PR description, otherwise the release DRI needs to follow up you offline to find out the vsix files, we want to avoid this kind of things.

**Comment by aasimkhan30** [comment]
@alanrenmsft, if you are referring to the vsix file, Here is the link to the build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=101309&view=results

The vsix file is already uploaded to the blob storage. Please let me know if there is additional details needed for the PR.

**Comment by alanrenmsft** [comment]
I see, yeah, you should provide these information in the PR description when you send out the PR. PR against the extension gallery branch is a bit special, it is more than just merging the PR, the release DRI need to:
1. upload the new vsix (if first party)
2. merge the PR
3. publish the new gallery files
4. verify the new version is showing up in ADS
5. notify the PR author to do the functional verification

It would save the release DRI time if the necessary information is provided at PR creation time. 

I will do these steps now.
BTW, going forward, the developers should try not to directly touch the storage account for extensions, the release DRI should handle it.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@aasimkhan30 the new gallery file has been published, please do some functional testing.

**Comment by aasimkhan30** [comment]
I'll keep that in mind. Thanks!

**Pull request merged**
