### PR TITLE
Notebooks: Fix starting and separators in a row

### LINKED ISSUE #7785: Context Menu for Text Cells Has Too Many Separators on PC
Click the "..." on the right of a text cell on PC (strangely, doesn't appear to repro on Mac):

image

Should only be one separator 😄

### PR DESCRIPTION
**Pull request by chlafreniere**
I don't like this. But the canRun() method only takes into account CellContext, not the other items in the items array. If anyone has any other ideas please let me know 😄 

Fixes #7785.

Code cells:
image

Text cells:
image

### CODE REVIEW

**Comment by anthonydresser** [comment]
This is what vscode menu filling code is for _shrug_

**Comment by chlafreniere** [comment]
@anthonydresser can you expand on this with an example? Sorry I'm just not super familiar there

**Comment by anthonydresser** [comment]
The entire menuing system that vscode has built, utilizing contributions is meant to handle these cases.

**Comment by kevcunnane** [comment]
@anthonydresser can you give Chris an example code fix for this? E.g. for internal actions (not contributed actions), what code change would be needed to do things right? Convert things into menu groupings for example and then use a layout function based on that? Helping Chris (and myself) learn best practice would ensure future scenarios don't have the same issue.

**Pull request merged**
