### PR TITLE
Make declarative table read blank for empty text cells

### LINKED ISSUE #6152: [Accessibility]A11y_AzureDataStudio_CreateConntionDataSrc_ScreenReader: NVDA is not announcing the blank column.
"Bug Description:
[Check out Keros!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.
Environment Details:
Application name: Azure Data Studio (Agent, Create External Data, Notebooks)
App Version: 1.9.0-insider (user setup)
VS Code 1.33.1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
Additional Details:
Tool Name: NVDA
MAS Reference:MAS1.3.1
Repro Steps:
1.Install the app Azure Data Studio.
2.Enable SQL server2019 preview.
3.Select table from the database.
4.Create External Table screen should open.
5.Next button->Create Database Master Key screen should open.
6.Click on next button.
7.Open NVDA and observe the announcement of screen reader.
Actual:
Screen Reader is not announcing blank column as a blank it is keeping quite after announcing column header.
Expected:
It should announce the blank column as a blank.
User Impact:
User with disabilities will be confuse whether the column is blank or having some data in it.
Recommendation:
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
MAS Reference:MAS1.3.1
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}
Attachment for Reference:

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #6152

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@udeeshagautam You said in the linked issue that https://github.com/microsoft/azuredatastudio/pull/7008 should have fixed it - but I'm not seeing anything in that about read "blank" for empty text. Am I missing something?

**Comment by Charles-Gagnon** [comment]
Also - has there been any other fixes doing a similar thing? I feel like this should be a more general problem so am surprised that there doesn't seem to be any other issues opened for that in the quick search I did of the a11y bugs.

**Comment by Benjin** [comment]
> Also - has there been any other fixes doing a similar thing? I feel like this should be a more general problem so am surprised that there doesn't seem to be any other issues opened for that in the quick search I did of the a11y bugs.

Not that I've made or seen done.

**Comment by udeeshagautam** [comment]
@Charles-Gagnon there were similar fixes in table componnet formatter (a function named slickGridDataItemColumnValueWithNoData) but not for declarative table I think, sorry, I might have not realized at the time that this was declarative table component.

**Comment by Charles-Gagnon** [comment]
Ah ok, yeah looks like that and https://github.com/microsoft/azuredatastudio/blob/f7bef3f87b0f9457b859d67d4d2c9429f3a422fa/src/vs/editor/browser/widget/diffReview.ts#L733 are doing similar things.

**Pull request merged**
