### PR TITLE
Change name from import new database project

### LINKED ISSUE #11279: Change "Import New Database Project" to a different name
A couple options so far are "Create New Database Project" or "Export into database project"

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes #11279. This changes the name from "Import New Database Project" to "Create Database Project" in the UI. 

The one I'm not too sure about is in the viewlet when no projects are open. Maybe it would be clearer for that one to be "Create Project From Database"?
Screen Shot 2020-08-25 at 10 09 37 AM
Screen Shot 2020-08-25 at 10 09 17 AM
Screen Shot 2020-08-25 at 10 08 58 AM
Screen Shot 2020-08-25 at 10 08 37 AM

### CODE REVIEW

**Comment by SakshiS-harma** [comment]
> This PR fixes #11279. This changes the name from "Import New Database Project" to "Create Database Project" in the UI.
> 
> The one I'm not too sure about is in the viewlet when no projects are open. Maybe it would be clearer for that one to be "Create Project From Database"?
> Screen Shot 2020-08-24 at 5 48 10 PM
> Screen Shot 2020-08-24 at 5 47 40 PM
> Screen Shot 2020-08-24 at 5 47 51 PM
> Screen Shot 2020-08-24 at 5 52 48 PM

I agree, it should be "Create Project From Database". Create Database project and New Project are confusing.

**Comment by dzsquared** [comment]
I'm good with "Create Project From Database". Similar functionality in the SSDT interface is "Import Database" but the step is delayed to post-project creation.

**Comment by Benjin** [comment]
+1 to "Create Project from Database"

**Comment by kisantia** [comment]
updated the screenshots in the description with the command changed to "Create Project From Database"

**Pull request merged**
