### PR TITLE
Update Extension for Oracle to v0.1.1

### PR DESCRIPTION
**Pull request by nahk-ivanov**
Update extensions gallery to include latest version of `Extension for Oracle`. This includes few bug fixes, so only bumping patch version.

### CODE REVIEW

**Comment by nahk-ivanov** [comment]
As usual - I will test updated feeds locally right now and let you know once we are good to go! Please hold off on merging this just yet.

**Comment by nahk-ivanov** [comment]
Oh, I can no longer test it:

> Access to XMLHttpRequest at 'https://raw.githubusercontent.com/microsoft/azuredatastudio/2e08b7f4a8bf0c698e6ba33b828524f3ea7ba77b/extensionsGallery.json' from origin 'vscode-file://vscode-app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

:(

I guess we merge it and deal with the consequences...

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Ah interesting, when we test we usually upload a test gallery file to our blob storage and then use that. Guess that request is going through a different path to trigger the CORS preflight request.

We can find a solution if needed, but typically as long as you've tested the VSIX itself yourself then most other things are checked automatically by validate-galleries (for example verifying that the links are all active)

**Comment by Charles-Gagnon** [comment]
Galleries updated!

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon Thanks!

Tested just now - seems to be working as expected.

I was usually testing with the actual file that is going to be the result of my PR, so that I'm good on my end all the way to where you merge and publish (or whatever). It was giving me confidence that if anything breaks - it's not on my end. 😎

**Pull request merged**
