### PR TITLE
Fix notebook icon path

### PR DESCRIPTION
**Pull request by abist**
Fix notebook icon path because it's causing build failures

### CODE REVIEW

**Comment by anthonydresser** [comment]
This won't fix all the issues, I'll have a PR soon that fixes all the build issues

**Comment by abist** [comment]
@anthonydresser this is for fixing the build step
there are still issues in the yml files

**Comment by anthonydresser** [comment]
I mean there are other icons that won't resolve correctly.

**Comment by anthonydresser** [comment]
This was caused by my relayering. I normally run a package before I merge when doing relayering, but I guess i forgot this time. I'll work on fixing the packaging task.

**Comment by Charles-Gagnon** [comment]
@anthonydresser - So is this change still necessary after your other fix?

**Comment by anthonydresser** [comment]
no

**Pull request closed without merging**
