### PR TITLE
bump extension gallery for server reports

### PR DESCRIPTION
**Pull request by dzsquared**

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
Will merge this in once we have a build with the new extension version

**Comment by Charles-Gagnon** [comment]
@dzsquared Do the latest builds have all the changes you want for this?

**Comment by dzsquared** [comment]
It looks like @alanrenmsft took care of this while my github notifs weren't functioning - thanks! (closing)

**Comment by alanrenmsft** [comment]
@dzsquared oops, sorry, I didn't realize the very existence of this PR, otherwise I would have reused it. haha

**Pull request closed without merging**
