### PR TITLE
Remove adstest package

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
We've never used this and it just makes the code harder to deal with and adds extra unneeded dependencies. Can add back in if we ever do anything more with this.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
IIRC, Arvind may still have the test running, have you checked with him?

**Comment by Charles-Gagnon** [comment]
@ranasaria I'm not aware of this being actively used currently - is that correct?

**Comment by ranasaria** [comment]
yes not being used.

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Look good to you?

**Pull request merged**
