### PR TITLE
Stops second invocation of createNewSession while expanding OE tree items on disconnected servers

### LINKED ISSUE #21428: createNewSession is called twice when trying to expand a saved connection in OE
This is called twice:
https://github.com/microsoft/azuredatastudio/blob/02e9f8d3ef0d0eb5c3d4115c6cf2b2e184e7a97f/src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts#L347

I believe this will cause the server node not to expand.

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR fixes #21428

Problem Description:

When a user clicks on any Object Explorer tree view item, a mouse down event is fired and captured by the treeView’s listeners. The execution flow for this handler routes to `onTreeSelect` in `treeSelectionHandler.ts`, which invokes `sendSelectionEvent` in the context of a `setTimeout`, assigning the timer ID to `this._clickTimer`. The function invoked by the timeout eventually calls the `createNewSession` method found in `objectExplorerService.ts`.

If the `treeView` node that was initially clicked was for a disconnected server, then there’s also a second event that is fired when the connection to the server is established. That second event is handled by `$onConnectionComplete` in `mainThreadDataProtocol.ts`. The flow of execution here also eventually makes it to the `onTreeSelect` method in `treeSelectionHandler.ts`, assigning the timer ID to `this._otherTimer`. The function invoked by this second timeout also eventually calls the `createNewSession` method found in `objectExplorerService.ts`. The issue here is that depending on when this second invocation to `createNewSession` occurs results in the server node not able to expand.

Solution:

Uses an `ObjectExplorerRequestStatus` object to prevent a second session from being created when a user clicks on a disconnected server node in Object Explorer, which was previously preventing the nodes in Object Explorer from expanding.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@lewis-sanchez  is it possible to avoid the unnecessary request instead of debouncing it? I am worried there will be some unexpected side effects.

**Review by aasimkhan30 — APPROVED** [review]
Looks good to me. Please wait on other reviewers to approve before you merge your PR in.

**Comment by alanrenmsft** [comment]
looks good to me, let me try it out locally.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@aasimkhan30 the change is in a high impact area, please examine the changes carefully to avoid any unexpected behaviors.

**Comment by aasimkhan30** [comment]
I have tested OE on a couple of providers and so far it seems to work well.

**Pull request merged**
