### PR TITLE
[Loc] Update to arc extension for localization and fix for sql-database-projects lcl file in Chinese Simplified, along with small additions to XLFS

### LINKED ISSUE #17209: arc extension raising missing LOC resource error on startup
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Launch ADS with arc extension, such as in the default dev env

Expected: no errors

Actual: Error from arc about missing resource strings.  See below.  It looks like the resources were removed in this PR https://github.com/microsoft/azuredatastudio/pull/17119/files#diff-2659e47f1ac2a1511ae01a88b9b9799a810e271476108397667b5ecaaf3a4f50L88.  Please either add back strings or remove references to these strings.

image

### PR DESCRIPTION
**Pull request by smartguest**
This PR adds several strings to notebook, sql-database-projects, sql-migration and SQL XLF files. It also removes a duplicate string from the sql-database-projects lcl file for Chinese simplified that was causing the CI build to fail. Additionally this renames the Arc extension replica description to high-availability as it was changed in package.nls.json but not in the main file.

This PR fixes #17209

### CODE REVIEW

**Comment by smartguest** [comment]
It turns out we forgot to rename the replica description strings for Arc so they errored upon startup, this time I renamed them to match the current name in the nls file.

**Comment by Charles-Gagnon** [comment]
FYI - please make sure the title accurately reflects the changes being made. There are more than just changes to arc and sql-database-projects here.

**Review by Charles-Gagnon — APPROVED** [review]
Please wait for confirmation from @candiceye before merging in.

**Review by kburtram — APPROVED** [review]
It looks like this PR will fix this bug I just opened https://github.com/microsoft/azuredatastudio/issues/17209.  Please close the bug when merging if so.  Thanks!

**Review by candiceye — APPROVED** [review]

**Pull request merged**
