### PR TITLE
Update extension galleries for Arc and Azcli 1.7.0

### PR DESCRIPTION
**Pull request by candiceye**
Please use vsix files **arc-1.7.0.vsix** and **azcli-1.7.0.vsix** from the below link, but please don't merge in the PR until I give the OK: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=178506&view=artifacts&pathAsName=false&type=publishedArtifacts

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@candiceye  `but please don't merge in the PR until I give the OK`
why not send this later when you are ready or mark it as draft?

**Comment by candiceye** [comment]
@alanrenmsft I thought that because you would have to update the vsix files for validate-galleries before merging the PR in, it would be more considerate if I sent the PR out first and then asked you to merge it in later once my team gives the OK to release the extension. But in the future if you'd prefer for me to keep it as a draft in the future and only make the PR live once it is ready to release, I can do that.

**Comment by alanrenmsft** [comment]
:) I was under the impression that you might need to use different vsix files based on testing.

don't worry about the time to upload vsix and build run time, create PR when you are ready to avoid confusion.

**Comment by candiceye** [comment]
@alanrenmsft  Gotcha and will do! Thanks for clarifying

**Comment by candiceye** [comment]
@alanrenmsft  Could you help me merge it in now?

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
