### PR TITLE
Porting STS version update to release branch 1.48

### PR DESCRIPTION
**Pull request by ssreerama**
image

### CODE REVIEW

**Review by erpett — APPROVED** [review]

**Comment by kisantia** [comment]
@ssreerama can you please create an issue in the Feb milestone and link this to it?

**Review by corivera — APPROVED** [review]

**Comment by ssreerama** [comment]
created the issue 
https://github.com/microsoft/azuredatastudio/issues/25361

**Comment by kisantia** [comment]
> @kisantia, One of the checks are failing continuously, any Idea what is related to ?

Cory fixed this in https://github.com/microsoft/azuredatastudio/pull/25359. It should pass if you merge from the `release/1.48` branch

**Comment by ssreerama** [comment]
Oh cool, let me get the latest changes then :)

**Review by kisantia — APPROVED** [review]

**Pull request merged**
