### PR TITLE
PostgreSQL Extension to 0.3.1

### PR DESCRIPTION
**Pull request by DaeunYim**
VSIX files location: https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.3.1/azuredatastudio-postgresql-0.3.1.vsix

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@DaeunYim looks like you only produced platform specific vsix files, those are good to have so that user can download them directly, but in the extension gallery, we need a vsix that works with all platforms. could you please add it?

**Comment by alanrenmsft** [comment]
please refer to this release: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.2.7

**Comment by DaeunYim** [comment]
> please refer to this release: https://github.com/microsoft/azuredatastudio-postgresql/releases/tag/v0.2.7
> 
> image
> 
> VS
> 
> image

Hi, I just added this file https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v0.3.1/azuredatastudio-postgresql-0.3.1.vsix

**Comment by alanrenmsft** [comment]
@DaeunYim I compared them again and found a few more issues:

1. Release 0.3.1 is missing the Linux installer - not a blocking issue for this PR.

2. In release 0.3.1, the file sizes are all the same which means the platform-specific installers doesn't include the platform-specific PGToolsService bundled within them; The purpose of these installers are for offline scenarios where the user doesn't have internet access on the machine where they use Azure Data Studio. - not a blocking issue for this PR.

3. Release 0.3.1 installer is significantly smaller than the one in 0.2.7 release, is this expected? please make sure the reduction in size is well understood and expected.

image

image

**Comment by DaeunYim** [comment]
@alanrenmsft 
Yes, thanks for taking a look into this. 
1. We are not working on supporting Linux OS at this time. Is this something required to release an extension?
2. Yes, so for those packages with specific OSes in the previous version, they are bigger because they include pgsqltoolsservice executable and postgres executables for its OS. I asked in the Teams chat about uploading offline packages and online packages. So do you want me to only upload offline packages (which already include pgsqltoolsservice executables) in Github ?
3. Same here. It's only magnificently smaller because of missing pgsqltoolsservice. Let me know what would be the best approach with offlien/online packaging!

**Comment by alanrenmsft** [comment]
@DaeunYim
1. It is up to your team to decide the supported platforms, we have no issue if there is no Linux support.
2. The size reduction I was talking about is between the online installers, it used to be 3.49MB in release 0.2.7 and it is now only 1.1.6MB, is this expected?
3. I've added a section to cover the platform specific installers in the Wiki page, please take a look and let me know if you have any questions.

**Comment by DaeunYim** [comment]
> @DaeunYim
> 
> 1. It is up to your team to decide the supported platforms, we have no issue if there is no Linux support.
> 2. The size reduction I was talking about is between the online installers, it used to be 3.49MB in release 0.2.7 and it is now only 1.1.6MB, is this expected?
> 3. I've added a section to cover the platform specific installers in the Wiki page, please take a look and let me know if you have any questions.

2. I checked and the source folder size is almost same. I think this might be caused by updating the old libraries and node version to the latest? We tested the vsix file and the features didn't have any issues. 

3. Updated Windows specific vsix file in the release link. But I'm having an issue with creating offline packages for Mac OS. Code signing deletes python executables (pg executables are still there) and the extension downloads the executable from the remote repo when started. I'll need to spend time for investigation and have no clue yet. I'm assuming this is not necessarily a blocker for releasing online version but let me know your thoughts.

**Comment by Charles-Gagnon** [comment]
Just did a quick check myself, and yeah it looks like the node_modules changes you did were the main cause here. So should be fine (and I also verified that things seem to work in a basic smoke test of connect + run query)

image

**Comment by alanrenmsft** [comment]
@DaeunYim, you are right, those are not blocking issues, so follow up work items for you:
1. test and fix issues for Linux platform
2. fix the macOS offline installer issue.
3. update the readme to include a section about offline installers.

**Review by alanrenmsft — APPROVED** [review]

**Comment by DaeunYim** [comment]
> @DaeunYim, you are right, those are not blocking issues, so follow up work items for you:
> 
> 1. test and fix issues for Linux platform
> 2. fix the macOS offline installer issue.
> 3. update the readme to include a section about offline installers.

Acked!

**Pull request merged**
