### PR TITLE
check for isDirty false explicitly (#14427)

### PR DESCRIPTION
**Pull request by MaddyDev**
* check for isDirty false explicitly

* revert back test to not pass isDirty

This PR ports #14427  into release to address #14481

### CODE REVIEW

**Comment by kburtram** [comment]
@MaddyDev should these port requests be targeting `release/1.27`?

**Comment by MaddyDev** [comment]
@chlafreniere Aren't we porting these? I don't think I need to port these to release/1.27 because they are merged way before and must be in it.

**Comment by chlafreniere** [comment]
@MaddyDev there was some conversation yesterday around this (I can sync with you offline); this is targeting the right branch, all good 😄.

**Comment by Charles-Gagnon** [comment]
@MaddyDev What's the status of this? Do we need it anymore with 1.27 being out?

**Pull request closed without merging**
