### PR TITLE
update schema compare to 1.10.0 in RC

### PR DESCRIPTION
**Pull request by kisantia**
build with schema compare vsix: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=99644&view=artifacts&pathAsName=false&type=publishedArtifacts

### CODE REVIEW

**Comment by udeeshagautam** [comment]
We are updating SC this time?

**Comment by kisantia** [comment]
@udeeshagautam yup to get the fix for https://github.com/microsoft/azuredatastudio/issues/14957 and https://github.com/microsoft/azuredatastudio/issues/12779

**Review by abist — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@abist I am assuming the release DRI will merge and publish, right?

**Review by alanrenmsft — APPROVED** [review]

**Comment by abist** [comment]
Extension uploaded.

**Comment by kisantia** [comment]
@abist did you also upload the extensions-gallery file? I don't see the updated schema compare extension in the RC build yet

**Pull request merged**
