### PR TITLE
Merging after release completion

### PR DESCRIPTION
**Pull request by erpett**
This PR fixes #

### CODE REVIEW

**Review by alanrenmsft — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Below people - please verify that these extensions are ready to be updated in stable
@corivera - .NET Interactive
@kisantia @Benjin Schema-compare
@alanrenmsft @languy CosmosDB

**Comment by alanrenmsft** [comment]
@Charles-Gagnon  did i merge it too soon?

**Comment by Charles-Gagnon** [comment]
Or not 😄

It's probably fine (they were purposely updated in RC branch after all). I just wanted to be extra sure

**Comment by alanrenmsft** [comment]
I can confirm the following updates: cosmosdb, sql-database-proj, schema-compare.

**Comment by corivera** [comment]
.NET Interactive looks good

**Pull request merged**
