### PR TITLE
Remove ADS/azdata refs from SQL Bindings

### LINKED ISSUE #19103: Remove azdata/ADS references from sql bindings
Since we do not plan on supporting SQL Bindings for ADS due to the Azure Functions extension dependency (for the near future). We can remove the references to azdata/ADS.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #19103.

This removes all references of azdata and azuredatastudio apart from the license and vscode-development instructions. We can further discuss where this extension should live in the future.

### CODE REVIEW

**Review by lucyzhang929 — APPROVED** [review]

**Review by Charles-Gagnon — COMMENTED** [review]
We should also look into removing it from the extensions that are loaded up when dev ADS is launched - that way we don't have to worry about ensuring that this doesn't cause any errors on startup or anything.

**Review by barbaravaldez — APPROVED** [review]

**Comment by alanrenmsft** [comment]
if you are not planning to support this extension in ADS, I think you should move the code to its own repo.

**Comment by VasuBhog** [comment]
@Charles-Gagnon I was not able to find anything on removing the extension on load up for dev ADS. 

@alanrenmsft we will be discussing this in the near future :)

**Comment by Charles-Gagnon** [comment]
Alright, I found where the loading is happening but we won't be able to skip sql-bindings unless we either modify the VS Code stuff or move it to a different folder. So for now we'll keep it here, but if you think we've never going to want this in ADS then we should move it out (which will also reduce the overhead of building/packaging the thing too)

**Comment by VasuBhog** [comment]
Thanks for looking into this @Charles-Gagnon. 

@alanrenmsft we will be deciding this whether it will be worth moving this and setting up a new extension prior to our Build release or if we should do it after for June release.

**Pull request merged**
