### PR TITLE
[Port] [SQL Migration] Bug fixes for new feature SKU Recommendation in migration extension

### PR DESCRIPTION
**Pull request by neetusingh-ms**
https://github.com/microsoft/azuredatastudio/commit/80c8b06ec87debe417713346ce5194f902babbf6.
Adding telemetry for errors happening during data collection/ telemetry for SKU recommendation.
Adding click and close events to disposable collection to avoid leaks.
Updating migration workflow strings.

https://github.com/microsoft/azuredatastudio/commit/8135867e064f18b4b46cb2671027b7da985d68ae
Updating readme with new gif that includes SKU Recommendation usage.

Approved Issue https://github.com/microsoft/azuredatastudio/issues/18428

### CODE REVIEW

**Review by raymondtruong — APPROVED** [review]

**Comment by brian-harris** [comment]
@neetusingh-ms  are all 34 commits part of this port request or do you want to cherry pick your commits only?

**Review by raymondtruong — CHANGES_REQUESTED** [review]
Discussed internally, will recreate PR to only include relevant commits

**Comment by neetusingh-ms** [comment]
> @neetusingh-ms are all 34 commits part of this port request or do you want to cherry pick your commits only?

**Comment by Charles-Gagnon** [comment]
It doesn't really matter since we squash merge anyways as long as the only changes are the ones you need.

**Review by kburtram — APPROVED** [review]

**Review by raymondtruong — APPROVED** [review]

**Pull request merged**
