### PR TITLE
Handle some server properties not being supported for certain SQL versions

### PR DESCRIPTION
**Pull request by corivera**
The ADS half of this STS PR: https://github.com/microsoft/sqltoolsservice/pull/2261

When a property is unsupported, the related controls have to be hidden from Properties dialog. We indicate that by returning a property as null or undefined.

Also fixes this issue just from the STS bump: https://github.com/microsoft/azuredatastudio/issues/24567

### CODE REVIEW

**Comment by corivera** [comment]
Missed some properties for SQL 2014, so I'll reopen this PR once the STS changes are published.

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@corivera Make sure to include the STS changes and tag anyone who's commits are included with this bump to verify there's no issues with updating.

**Review by barbaravaldez — APPROVED** [review]

**Comment by corivera** [comment]
Changes included in the STS bump to 4.10.0.14
VersionBump

VersionBump2

FYI for @aasimkhan30 @cheenamalhotra @smartguest @zijchen @Benjin @Ramudaykumar in case there are any changes we shouldn't bring into ADS yet.

**Review by aasimkhan30 — APPROVED** [review]
Sts changes looked good to me

**Comment by Benjin** [comment]
Looks like the unit test pipeline is hitting some test failures due to my change in STS; I'll look into it.

**Comment by Benjin** [comment]
Okay, all fixed now:
* Updating the baseline with an improved error message
* Fixed an issue where STS was now expecting full DSP strings
* Discovered and fixed an issue where creating new SQL projects could fail silently

**Pull request merged**
