### PR TITLE
10887 - Icon vertical position beside Cell and Run all in notebook toolbar.

### LINKED ISSUE #10887: notebook main toolbar button's text and icon are not vertically aligned properly
text is a bit higher than icon
Screen Shot 2020-06-11 at 2 55 04 PM

### PR DESCRIPTION
**Pull request by halerankin**
This PR fixes #10887 
New positioning value fixes icon position beside Cell and Run all in notebook toolbar.

image

### CODE REVIEW

**Comment by chlafreniere** [comment]
@halerankin this was fixed previously but i believe it impacted some other icons on the toolbar. can you double check that this doesn't have a similar effect?

**Comment by halerankin** [comment]
@chlafreniere Yes, it was in [this PR](https://github.com/microsoft/azuredatastudio/pull/10681) that I had adjusted the container so the text would sit evenly across the toolbar. The layout issue addressed in this PR is the vertical positioning of the icons located in pseudo element :before.

**Comment by chlafreniere** [comment]
@halerankin thank you. Appreciate the thoroughness. Looks good!

**Comment by halerankin** [comment]
@Charles-Gagnon This PR is now up to date. Good to go.

**Comment by Charles-Gagnon** [comment]
We've already signed off so once the checks pass you're good to merge in 😄

**Pull request merged**
