### PR TITLE
Stop executing the same code three times

### PR DESCRIPTION
**Pull request by aaomidi**
Repeated code was causing some other code paths to execute 3-4 times. This is all extra CPU cycles we're wasting and has an impact on performance. 

I'm not 100% sure of the side effects for this, so please help me do thorough testing.

### CODE REVIEW

**Comment by anthonydresser** [comment]
I personally wouldnt feel comfortable changing this code since its such a mess, unless it was really hurting performance in a meaningful way.

**Comment by aaomidi** [comment]
Maybe we should do this after we've branched off for April release. I think it's technical debt that should probably go away (Since we're not re-writing any of this anytime soon) and we'll try to keep an eye out during insiders/etc

**Comment by Charles-Gagnon** [comment]
Yeah that sounds fine. I agree this is too late for me to feel comfortable getting in at this point but a full month of testing with it in should be enough.

**Comment by aaomidi** [comment]
Hopefully I won't forget after the release branch is made. I'll rely on you two to remind me as well :P

**Comment by aaomidi** [comment]
This can potentially cause issues, but we're in a good state to make sure we can test this before next release.

**Comment by anthonydresser** [comment]
This broke the smoke tests, can you revert and figure out the issue.

**Pull request merged**
