### PR TITLE
Removed clear results in set input and keep results visible.

### LINKED ISSUE #1876: Saving a query with a new file name causes results to disappear
- SQL Operations Studio Version: fbd5e81

Steps to Reproduce:
1. Open an untitled query editor and write a new query (or run a script operation to get a new query editor with a query)
2. Run the query and get results
3. Save the editor. If the editor wasn't already untitled, use "save as" with a new filename 

Actual behavior: The open query results disappear
Expected behavior: The query results stay open

### PR DESCRIPTION
**Pull request by smartguest**
This PR removes the clearing of the results tab and messages tab when the editor is replaced (when pressing "save" on a file, this issue does not occur, but renaming the file or saving it for the first time does)  following a "save as". However, as a result, this preserves the results and editor when a new query tab is added, but it will be refreshed with the right results when run is pressed again.

This PR fixes #1876

### CODE REVIEW

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
Did a brief test and found at least one issue : 

1. Open two query editor tabs
2. Run a query on one of them (the other is still blank)
3. Switch to the second tab

The second tab still shows the results from the first. It should be clearing those (that's why this was done in the first place I imagine). 

Make sure you're testing all the different scenarios that the input could be set (new file, saving untitled, saving existing doc under different name, switching editors)

**Comment by smartguest** [comment]
@Charles-Gagnon Yes that was exactly the issue I mentioned in my report, however clicking "save as" technically creates a new editor entirely, should there be a flag to indicate if this is a "save as" and to disable the clear results and keep results visible when it happens? This is going to require a lot of passed booleans. The results will be cleared if we remove the "clear results tab and messages tab" from queryResultsView, while still keeping the results and messages tab open but empty.

**Comment by Charles-Gagnon** [comment]
That's definitely not something we should allow to happen since that could easily result in the user thinking the results are wrong.

You should look into when we set the state ensuring that we update the display properly - if there isn't a state (or it's empty) then we should clear the grid/hide the tab.

**Comment by smartguest** [comment]
Added a flag for textResourceEditorInput to indicate if the view state is needed to be preserved since that is what passed in to the queryEditor when a saveAs happens (don't want to break anything at the moment).

**Comment by smartguest** [comment]
Edit, needs to work for save button

**Comment by smartguest** [comment]
There is an issue where if you open one new query and run the results on it, saving it to a file, then run another new query and saving onto the first one, it replaces the contents of the query, but not the results, since there is currently no way to pass in the query input of the untitled editor into the new one.

**Comment by smartguest** [comment]
@Charles-Gagnon The main issue so far is that when saving, the file is turned into a TextResourceEditorInput by vscode and this means that the status for the query window is lost as a result. this is on top of numerous import violations and creating subclasses of the querytexteditorinput based on the other versions of other abstractTextClasses. 

I'm starting to think that by design, vscode doesn't allow this to be done at all without the vscode edit that I proposed.

**Comment by Charles-Gagnon** [comment]
What I think you should be looking at here is looking at overriding the save for the UntitledQueryEditorInput such that it calls save on the text input like [it does currently](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/common/editor/query/queryEditorInput.ts#L226) but then instead of returning that new file input directly create a new FileQueryEditorInput using the returned text input and setting the properties such as results state on that new input.

(note that the save is done in the abstract class, so you'd just be overriding that behavior in the Untitled version of the input since saving the File input shouldn't change at all)

**Comment by smartguest** [comment]
@Charles-Gagnon That doesn't seem to work as attempting to change the state of resultsVisible on the text input casted as FileQueryEditorInput results in an "undefined" error, also the import of the FileQueryEditorInput violates vs-nls imports as well. Also even if this was able to be done, vscode calls a registerEditorOverride function that creates a new FileEditorInput given a resource file, and this does not preserve the state of the editor.

**Review by kburtram — CHANGES_REQUESTED** [review]
Let's try to avoid duplicating so much code from vs in to sql directories.  Likely there is a more targeted approach that involves overriding specific behavior that does the conversion from the untitled input to the normal file input.

**Comment by Charles-Gagnon** [comment]
> @Charles-Gagnon That doesn't seem to work as attempting to change the state of resultsVisible on the text input casted as FileQueryEditorInput results in an "undefined" error, also the import of the FileQueryEditorInput violates vs-nls imports as well. Also even if this was able to be done, vscode calls a registerEditorOverride function that creates a new FileEditorInput given a file resource, and this does not preserve the state of the editor.

I'm not saying just cast it - because yeah that won't work since the object isn't an actual FileQueryEditorInput. You need to create a NEW FileQueryEditorInput and give it the FileEditorInput that was created by the call to save, and then update the state of that new FileQueryEditorInput.

The editor override stuff is going to be a problem as it is though - that's correct. Currently they call the override before the input is actually created and so we only have the resource URI. The good news here though is that in the next VS Code merge we should be getting the newer version of that API that was updated to pass in the input instead : https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/editor/common/editorResolverService.ts#L105 which means we should be able to handle your case as well (since we can just ignore inputs that are already query inputs and not create a new one).

So my suggestion here is to put this off until the next VS Code merge comes in and then look at fixing it then since that should be more possible with my suggestion at that point.

**Comment by smartguest** [comment]
@Charles-Gagnon Yeah, I'm going to need to put in an initialization service for UntitledQueryEditorInput to create a new FileQueryEditorInput

**Comment by smartguest** [comment]
@Charles-Gagnon As an update: the FileQueryEditorInput doesn't seem to play nice with the sqltoolsservice when it tries to run getQueryRows, it gets an error saying "The Requested Query does not exist." Changing the sqltoolsservice to accommodate this may break SSMS if this happens. 

I found that adding the resultsVisible Property in the saveAs for untitledQueryEditorInput works without modifying the vs files themselves, however as you mentioned this is risky to do this. But now its isolated only to the Query related only SQL code this time.

**Comment by smartguest** [comment]
It turns out my approach to the fix is wrong so far, the results clearing is needed to prevent bleeding from one window to another, but the input passed in stores a gridPanelState that contains the results, this is not passed in when a saveAs happens due to the editor being replaced. This means I need to find a way to pass in the gridPanelState as well as the boolean flag to show the results.

**Pull request closed without merging**
