### PR TITLE
Added localization for connection option group names

### PR DESCRIPTION
**Pull request by smartguest**
This PR is the first step for fixing issue: https://github.com/microsoft/azuredatastudio/issues/6333

### CODE REVIEW

**Review by Xtrimmer — APPROVED** [review]

**Review by Charles-Gagnon — COMMENTED** [review]
It looks like you'll also want to update the `General` group name here : https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/browser/modal/optionsDialogHelper.ts#L170

It seems like localizing the group names isn't going to impact anything (i.e. we don't have hardcoded non-localized values we're checking again or anything...) but just to verify, did you try setting some values under the localized group headers and verify that they are still passed to the connection correctly?

**Review by alanrenmsft — APPROVED** [review]

**Review by andrewchoi5 — APPROVED** [review]

**Comment by smartguest** [comment]
@Charles-Gagnon they are passed in correctly in non localized mode, but I'll test if they work in localized mode or not.

**Comment by smartguest** [comment]
It works in localized mode with no differences, so it's good to go.

**Review by Charles-Gagnon — APPROVED** [review]
Thanks for verifying!

**Pull request merged**
