### PR TITLE
Fixes tab focus not visible after deploy a server button #10621

### LINKED ISSUE #10621: A11y_AzureDataStudioStayHealthy_Welcome_Resources_Keyboard:The tab focus is not visible after deploy a server button.
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#NonBenchmark;#DesktopApp;#MAS2.4.7;#SQL Azure Data Studio;#FTP;#Keyboard;#STP;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS2.4.7

**Repro Steps:**
1 . Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 . Navigate till Resources section "History tab" using tab key,

**Actual:**
The tab focus after deploy a server button is not visible and when screen reader is on the invisible focus make an announcement of a radio button and on the next tab key the focus is on the history tab under Resources section.

**Expected:**
The tab focus after deploy a server button should be on the history tab and the screen reader should make the announcement of it when in focus under Resources section 

**User Impact:**
Keyboard users will not know where the focus has been moved too. 

**Attachment link for Reference:**
[10621A11y_AzureDataStudioStayHealthy_Welcome_Resources_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/4700711/10621A11y_AzureDataStudioStayHealthy_Welcome_Resources_Keyboard.zip)

### PR DESCRIPTION
**Pull request by v-bbrady**
When on the welcome page and using the keyboard to navigate, if you press enter on the "deploy a server" button the tab focus was then lost. I have removed the tab index on the unused checkbox that was causing this, and added a comment regarding the reason for the unused checkbox.

This PR fixes #10621

### CODE REVIEW

**Comment by alanrenmsft** [comment]
not sure what are the new changes for, please only include the changes for the issue you are trying to fix.

**Comment by v-bbrady** [comment]
> 
> 
> not sure what are the new changes for, please only include the changes for the issue you are trying to fix.

@alanrenmsft my mistake those changes were for another branch, they have been removed other than the merge which was needed.

**Comment by alanrenmsft** [comment]
if i remember correctly, this is the only change when I first reviewed this PR. but now it still has a lot more than it, merge from latest main branch is fine, but they wouldn't show up as changes. 
Screen Shot 2020-07-17 at 11 49 27 AM

**Comment by v-bbrady** [comment]
This branch got messed up with too many changes, a new branch was created.
New branch: https://github.com/microsoft/azuredatastudio/pull/11410

**Pull request closed without merging**
