### PR TITLE
Add dummy tests for all of our extensions

### PR DESCRIPTION
**Pull request by aaomidi**
When there are no tests to run, mocha never knows when to quit.

### CODE REVIEW

**Comment by chlafreniere** [comment]
Take a look at https://github.com/corivera/vscodetestcover/commit/c67fffa74ee508ea15cd1fd8ce3f0cebe3315167

**Comment by aaomidi** [comment]
I see. Is it that the rest of the extensions haven't been updated?

**Comment by chlafreniere** [comment]
> I see. Is it that the rest of the extensions haven't been updated?

I believe a new version needs to be pushed, and we then need to update the extensions to use that.

**Comment by aaomidi** [comment]
I see. @corivera can you push the latest version up? I'm running the pipeline with these set of changes to see if they fix the problem.

Although I'm guessing our timeout issues in the core might be related to this too.

**Comment by chlafreniere** [comment]
It looks like this also includes a bump to the version of mocha as well. Are there any risks there that we'd need to worry about? Do we need to revert that change in that branch?

**Comment by aaomidi** [comment]
I think it'll be fine. Probably. Worse case we release a new version?

**Comment by chlafreniere** [comment]
Cool

**Comment by Charles-Gagnon** [comment]
We already have a new release : https://github.com/corivera/vscodetestcover/releases/tag/v1.0.5

So just update the extensions to use that version.

**Comment by aaomidi** [comment]
Closing in favor of #9490

**Pull request closed without merging**
