### PR TITLE
added langpack update to insiders gallery

### PR DESCRIPTION
**Pull request by smartguest**
Adds in the most recent langpacks to the Insiders gallery. If the date needs to be changed let me know, but they were uploaded on that date technically. (Posting this again to account for changes to the release/extensions branch)

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@kburtram any issues with this? Right now we don't really have a defined process for how langpack updates are done and while I don't see any huge problems with this the timing gets a bit weird - especially where extensions are involved which may or may not actually have updated versions pushed to the gallery yet.

If we really wanted to ensure proper localization at all times then we'd likely need to invest in splitting the non-bundled extensions to include their own localizations (instead of bundling with the ADS langpacks).

**Comment by kburtram** [comment]
@smartguest do we still need this PR?  if not, please close it.

@Charles-Gagnon I don't think there is generally a reason to update loc for insiders separate from stable.  Unless we wanted feedback from insider users a particular month related to a new change.  I think we should push to both galleries at the same time aligned with each stable release in general.

**Comment by Charles-Gagnon** [comment]
Sounds reasonable to me.

@smartguest Can you get the PR out for updating the galleries with the new 1.35 langpacks? We decided to hold off on that until you got back.

**Comment by smartguest** [comment]
@Charles-Gagnon the main gallery langpacks were already updated to 1.35, this one updates the insiders one to match. Are there any additional changes I need to make before this can be merged in?

**Comment by Charles-Gagnon** [comment]
Oh yeah, sorry was looking at the wrong commit. Everything looks good.

**Pull request merged**
