### PR TITLE
update schema compare and sql database projects in insiders

### PR DESCRIPTION
**Pull request by kisantia**
This updates schema compare to 1.13.0 and sql database projects to 0.15.0 in insiders.

Build with vsixs: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=142107&view=results

### CODE REVIEW

**Review by Benjin — APPROVED** [review]

**Review by udeeshagautam — APPROVED** [review]

**Comment by udeeshagautam** [comment]
Hmm, is it expected that PR build is failing to retrieve SC?

**Comment by kisantia** [comment]
> Hmm, is it expected that PR build is failing to retrieve SC?

it's failing because the extensions haven't been updated to blob storage yet.

**Comment by Charles-Gagnon** [comment]
You're saying the validate-galleries? We haven't uploaded it yet (it's preferred to have the extension DRIs do that to ensure things are uploaded in the correct spots)

**Comment by Charles-Gagnon** [comment]
@kisantia Please don't use adhoc builds for published extensions. Can we use the build from last night? Or wait until the build tomorrow?

**Comment by kisantia** [comment]
> @kisantia Please don't use adhoc builds for published extensions. Can we use the build from last night? Or wait until the build tomorrow?

sure we can wait until tomorrow's build. I checked in one more fix today.

**Comment by udeeshagautam** [comment]
> > @kisantia Please don't use adhoc builds for published extensions. Can we use the build from last night? Or wait until the build tomorrow?
> 
> sure we can wait until tomorrow's build. I checked in one more fix today.

@kisantia since we exactly were talking about this point, can we document it for future please.

**Comment by kisantia** [comment]
> > > @kisantia Please don't use adhoc builds for published extensions. Can we use the build from last night? Or wait until the build tomorrow?
> > 
> > 
> > sure we can wait until tomorrow's build. I checked in one more fix today.
> 
> @kisantia since we exactly were talking about this point, can we document it for future please.

yup I sent a PR to update it, but Charles said he will send another PR to update other things too and will include this, so I closed it.

**Comment by Charles-Gagnon** [comment]
Galleries updated!

**Pull request merged**
