### PR TITLE
Adds a script to audit our package.json

### PR DESCRIPTION
**Pull request by aaomidi**

### CODE REVIEW

**Comment by anthonydresser** [comment]
The governance audit task does the same thing. I don't see why we need this.

**Comment by aaomidi** [comment]
We can use this to fail builds on PR

**Comment by anthonydresser** [comment]
the governance task can also fail builds, see https://github.com/microsoft/azuredatastudio/pull/8096/files#diff-42a49d406e55711ca10c2213569ab204R65

**Comment by aaomidi** [comment]
Does that task search all the various package.jsons under our project?

**Comment by anthonydresser** [comment]
Yes is checks every package.json, every lock file and every node nodule

**Pull request closed without merging**
