### PR TITLE
Fix for issue #13936, check if there is a token before trying to use it.

### LINKED ISSUE #13936: Error "TypeError: Cannot read property 'accessToken' of undefined" for any DB connection request
Issue Type: <b>Bug</b>

All of a sudden I can no longer connect to any of my prod/uat environment databases. Whenever I try to connect, I get the error "TypeError: Cannot read property 'accessToken' of undefined".

However, I can connect to the same database servers / DBs using other clients like SQL Server Management Studio etc.

This has been happening suddenly since about a week now, and I had been successfully using ADS for the same DB connections for over an year until then.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (21.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by martenbohlin**
This PR fixes #13936
Checking if there is a token before trying to use the token helps fixing this issue and will ask for a new login instead of showing an error.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Thank you for the submission @martenbohlin ! Can you detail how this fixes the exact issue linked though? I'm not seeing a reference to `accessToken` anywhere and it seems like currently if a token isn't able to be retrieved it'll throw and then move on to the next tenant which seems like the correct behavior.

@cssuh Could you please work with @martenbohlin here to get this in?

**Comment by martenbohlin** [comment]
Hi, thanks for a great tool!

Yes you are correct, the error message that I got was slightly different I got this:
`Error: Cannot read property 'token' of undefined`
I just made a google for it and then that issue came up. Do you want me to log a new issue for my problem?

I have not analysed exactly why my fix helped. But my guess was that there was a check if there were errors or not when the AzureSubscriptionError was caught.

**Comment by martenbohlin** [comment]
Done some more testing now and I can not reproduce the original issue I had. So the only thing this PR does is to remove warnings each time you need to refresh your credentials.

**Comment by cssuh** [comment]
@martenbohlin looks like the Hygiene check has failed, can you run the `Format Document` command and push that to this branch?

**Comment by martenbohlin** [comment]
@cssuh Fixed and pushed.

**Comment by cssuh** [comment]
Looks like this was fixed in https://github.com/microsoft/azuredatastudio/pull/19192

**Comment by martenbohlin** [comment]
Thanks @cssuh

**Pull request closed without merging**
