### PR TITLE
Fix small icon in dev build

### LINKED ISSUE #8662: Icon on desktop tab for ADS is very small.
Steps to Reproduce:

1. Start running the build, and you'll see that the desktop tab icon is microscopic in comparison to other icons. See attached screenshot:

Small Icon

This doesn't look very good and it looks inconsistent with other apps.

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Fixes #8662

Caused by merge https://github.com/microsoft/azuredatastudio/commit/4ba6a979baa5adb455bc0bb20634b6a72180c05e

I don't know exactly why this is small when set this way since we embed the same icon into the built versions and it's fine there - so maybe they do some sort of smart scaling/trimming.

One way we could also fix this is to do what VS Code does and update the source icon to take up the entire icon space 

image

But we'd want to check what that does to the built insiders icons - VS Code currently still has the icon with spacing that we have for their built version so that might be something that's actually needed for the built version.

image

I'm personally in favor of dealing with less mixin stuff and just doing this fix - @anthonydresser / @kburtram any comments on your end?

### CODE REVIEW

**Comment by anthonydresser** [comment]
I would rather just fix the underlying issue rather than adding a patch that "fixes" it. We found multiple times that just modifying what we do to work better with what vscode is doing works better in the long term than trying to patch what they are doing.

**Comment by Charles-Gagnon** [comment]
I've asked for an updated icon from UX. @kburtram let me know if you have any issues with waiting and then just updating the icons we use. Since this only happens in dev builds I don't see much harm in waiting until we can get those icons.

**Comment by Charles-Gagnon** [comment]
Alright, updated with new icons from UX and distro update for new stable icons.

**Comment by Charles-Gagnon** [comment]
@kburtram @anthonydresser Everything look good? Here's the icon after the fix :

image

I also verified that a stable build with the changes still displays the correct icon : 

image

**Comment by anthonydresser** [comment]
Looks good to me, we will want to do a second verification on master when this is merged. Let me know when you merge so I can update the distro repo.

**Pull request merged**
