### PR TITLE
Update extensionsGallery.json

### PR DESCRIPTION
**Pull request by yterterian**
Adding In-Query Generator for Azure Data Studio with new features and dependency fixes

Overview:
The In-Query Generator is an Azure Data Studio extension that simplifies the creation of SQL IN clauses. It allows users to quickly convert selected data or clipboard content into properly formatted IN statements, supporting both numeric and string data types.

Key features:
- Convert selected text to an IN clause directly in the editor
- Generate IN clauses from clipboard content
- Automatically handle both numeric and string data types
- Escape single quotes in string values
- Support for NULL values in the IN clause

Recent changes:
1. Added new 'splitOnWhitespace' configuration option
   - Allows users to choose between splitting into newlines/tabs or all whitespace
   - Implemented via a new command: 'inQueryGenerator.toggleSplitOnWhitespace'

2. Introduced status bar item
   - Displays current split option state
   - Provides quick toggle functionality

3. Updated parseText function
   - Now respects the 'splitOnWhitespace' setting

4. Improved error handling and user feedback

5. Updated extension activation and deactivation logic

6. Dependency updates and vulnerability fixes
   - Addressed Dependabot alerts
   - Updated minimist and other dependencies to resolve security issues
   - Implemented resolutions in package.json for conflicting dependencies

7. Code refactoring for better maintainability These updates enhance the extension's flexibility and user experience while addressing essential security concerns. Users now have more control over how their IN statements are generated, with an easy-to-use toggle in the status bar.

Version: 0.0.9

### CODE REVIEW

**Comment by yterterian** [comment]
@microsoft-github-policy-service agree

**Review by Charles-Gagnon — APPROVED** [review]

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
https://github.com/YakovT/sql-in-query-statement-generator doesn't appear to be a valid repo. Do you have it set to private or something?

If you do and don't want to make it public, you can create a public facing repo with just the icon/readme/manifest/license and point the links there instead.

**Comment by yterterian** [comment]
Hi @Charles-Gagnon, apologies, I have updated the repo details

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
All asset URLs need to be from a https://raw.githubusercontent.com/ URL for 3rd party extensions, see other extensions in this file for examples.

**Comment by yterterian** [comment]
Updated, thank you

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
Thank you for your contribution!

**Pull request merged**
