### PR TITLE
Updating electron to 19.1.8

### PR DESCRIPTION
**Pull request by aasimkhan30**

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
Please also update https://github.com/microsoft/azuredatastudio-sqlite and do a new release of that so @lewis-sanchez can continue to work on the smoke tests.

**Comment by alanrenmsft** [comment]
@aasimkhan30 yesterday you mentioned there is a performance regression with this version of Electron, is the issue resolved?

**Comment by aasimkhan30** [comment]
@alanrenmsft , I have tried with an adhoc build and it seems to work fine. Also, I stopped noticing any dev issues after a restart. Can you please test it out locally?  https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=181251&view=results

**Comment by aasimkhan30** [comment]
@alanrenmsft  and @Charles-Gagnon should I cherry-pick this commit from upstream? 

https://github.com/microsoft/vscode/pull/167677/files

**Comment by aasimkhan30** [comment]
@alanrenmsft  and @Charles-Gagnon should I cherrypick this commit from upstream? 

https://github.com/microsoft/vscode/pull/167677/files

**Comment by alanrenmsft** [comment]
@aasimkhan30 yes, I think so.

> @alanrenmsft and @Charles-Gagnon should I cherry-pick this commit from upstream?
> 
> https://github.com/microsoft/vscode/pull/167677/files

**Comment by alanrenmsft** [comment]
> @alanrenmsft , I have tried with an adhoc build and it seems to work fine. Also, I stopped noticing any dev issues after a restart. Can you please test it out locally? https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=181251&view=results

@aasimkhan30 tried the windows zip version, looks okay to me.

**Pull request closed without merging**
