### PR TITLE
remove sql server 2005 and 2008 as options for sql database projects

### PR DESCRIPTION
**Pull request by kisantia**
Removing SQL Server 2005 and 2008 as options for target platform, as discussed in standup. Also fixing an unrelated test I updated a few weeks ago that was failing on windows.

image

### CODE REVIEW

**Comment by dzsquared** [comment]
with support dropped for SQL2005 and 2008, should we drop them from the list?

**Comment by kisantia** [comment]
@dzsquared sure that makes sense. I'll remove them and we can see if anyone asks for them to be added back

**Review by udeeshagautam — APPROVED** [review]
just the removal not the default change please as discussed.

**Comment by kisantia** [comment]
changed the default target platform back to sql server 2019 so this PR now only removes sql server 2005 and 2008 as options for target platform

**Review by dzsquared — APPROVED** [review]

**Pull request merged**
