### PR TITLE
Fix release job

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
LinuxWeb was being skipped which caused Release job to evaluate to false. Updating condition to allow Succeeded or Skipped for LinuxWeb only.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Are you going to do that? I don't have any context there and this is currently blocking insiders builds from going out so if it's not going to be a quick fix I think we should still do this as a temporary workaround.

**Comment by anthonydresser** [comment]
done

**Comment by aaomidi** [comment]
@anthonydresser was there a code change for enabling that task?

**Comment by anthonydresser** [comment]
#10880

**Comment by aaomidi** [comment]
But that PR is the reason we're having issues now

**Comment by aaomidi** [comment]
Alright so we just changed a variable on ADO

```
    "VSCODE_BUILD_WEB": {
      "value": "true",
      "allowOverride": true
    },
```

**Comment by anthonydresser** [comment]
I already changed the added the variable, I did it when I closed the pr

**Comment by aaomidi** [comment]
Hmm I was just looking at ADO history

image

**Comment by aaomidi** [comment]
Yeah I just wanted to learn what the change was haha

**Pull request closed without merging**
