### PR TITLE
Update extensionsGallery-insider.json

### PR DESCRIPTION
**Pull request by jimmystelzer**
Add Select Top N extension to the gallery.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@jimmystelzer please also update the extensionsGallery.json for the stable ADS builds.

**Comment by jimmystelzer** [comment]
> @jimmystelzer please also update the extensionsGallery.json for the stable ADS builds.

@alanrenmsft please could you point me out where?

**Comment by alanrenmsft** [comment]
@jimmystelzer  it is right next to the file you updated. https://github.com/jimmystelzer/azuredatastudio/tree/release/extensions

**Comment by jimmystelzer** [comment]
@alanrenmsft sorry for the dummy question. File updated.

**Review by alanrenmsft — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@jimmystelzer Thanks for the contribution. I have published your extension and it is now available in both insider and stable galleries, I gave it a try and it works great.

**Pull request merged**
