### PR TITLE
Temporarily skip failing notebook integration tests

### PR DESCRIPTION
**Pull request by lucyzhang929**
Some notebook integration tests are failing due to recent changes in the open notebook logic. Temporarily skipping the failing tests for now while I investigate to unblock insiders builds.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Are you sure that the failing tests aren't because of a product issue? Generally for this kind of thing I would lean more towards reverting the change and investigating that instead of just ignoring failing tests.

**Comment by chlafreniere** [comment]
I asked the same question @Charles-Gagnon. @lucyzhang929 and @VasuBhog looked into this and verified that there is no product issue in these code paths. It's currently believed that there's some test setup fixes necessary to get these tests back to green.

**Comment by lucyzhang929** [comment]
I haven't been able to find the exact part of the change that is causing the test failures but based on the manual testing @VasuBhog and I have been doing, we haven't run into any issues with opening notebooks. 

@VasuBhog @chlafreniere Thoughts on reverting this PR https://github.com/microsoft/azuredatastudio/pull/14978?

**Comment by chlafreniere** [comment]
If we've tested, I'm ok skipping tests for now. But let's please dedicate time on Monday to get to the bottom of this 😄

**Review by chlafreniere — APPROVED** [review]

**Pull request merged**
