### PR TITLE
kusto gallery update to 0.4.0

### PR DESCRIPTION
**Pull request by gupta1**
This PR fixes #

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Is this for the Dec release or can it go out now?

**Comment by gupta1** [comment]
> Is this for the Dec release or can it go out now?

This can go out even now.

**Comment by Charles-Gagnon** [comment]
Ok. In the future if you are doing an out-of-band release you can just do the update to both galleries in the same PR to save the extra hassle/confusion

**Comment by Charles-Gagnon** [comment]
Galleries updated

**Comment by gupta1** [comment]
> Ok. In the future if you are doing an out-of-band release you can just do the update to both galleries in the same PR to save the extra hassle/confusion

Yeah I can definitely include vsix link with both PRs. The idea was to first release it in insiders and then take it to main release just to be extra cautious

**Comment by Charles-Gagnon** [comment]
But you opened both PRs which seemed to imply that you wanted them both released at the same time...are you saying you didn't want this pushed to stable? That wasn't clear if that was the case...

**Comment by gupta1** [comment]
> But you opened both PRs which seemed to imply that you wanted them both released at the same time...are you saying you didn't want this pushed to stable? That wasn't clear if that was the case...

Last time I was advised to create separate PRs so I followed the same pattern actually, thinking first insiders will be published by default and later it will be published in main. But makes sense, I will only open the PR when I immediately want it to be published in future for any specific build to avoid confusion as well.

**Comment by alanrenmsft** [comment]
@gupta1 the RC1 gallery has been updated with your changes. please test it.

**Comment by alanrenmsft** [comment]
I did a diff for the rc1 gallery file and your change is published just now.

**Pull request merged**
