### PR TITLE
new version of asde and db project

### PR DESCRIPTION
**Pull request by alanrenmsft**
these are not tied to the new release, i will publish the changes after merge.

### CODE REVIEW

**Comment by udeeshagautam** [comment]
Lets wait for testing before uploading stable please... 
... Also do we need to update one more file for RC testing?

**Review by kisantia — APPROVED** [review]
please only update db proj in insiders for now until we finish testing this week. Thanks!

**Review by udeeshagautam — APPROVED** [review]

**Comment by alanrenmsft** [comment]
> Lets wait for testing before uploading stable please...
> ... Also do we need to update one more file for RC testing?

@udeeshagautam , RC gallery is copied from stable, no separate file for it

**Comment by alanrenmsft** [comment]
asde -> insider, stable.
sqldbproj->insider

**Pull request merged**
