### PR TITLE
Remove/comment out connection title generation from all areas.

### PR DESCRIPTION
**Pull request by smartguest**
Removes and comments out the title generation function from all areas but retains support for advanced connection options.

Companion PR for STS: https://github.com/microsoft/sqltoolsservice/pull/2145

Comparison Screenshots
Object Explorer:
Stable (These two connections are treated as one due to same target database):
StableOETree

Dev:
DevOETree

Recent Connections:
Stable (Only two, as the first one has a different target database technically):
RecentConnectionsStable

Dev:
RecentConnectionsDev

Dashboard:
Stable:
DashboardStable

Dev (header is the same):
DashboardDev

Notebook:
Stable:
NotebookStable

Dev:
NotebookDev

Server Status:
Stable:
ServerStatusStable

Dev:
ServerStatusDev

Query Editor:
Stable:
QueryEditorStable

Dev:
QueryEditorDev

Table Designer:
Stable:
TableDesignerStable

Dev:
TableDesignerDev

OE without connection name:
Stable:
StableOENoNameTree

Dev:
DevOENoNameTree

Recent Connections without connection name:
Stable:
StableRecentNoName

Dev:
DevRecentNoName

### CODE REVIEW

**Comment by cheenamalhotra** [comment]
@smartguest 

Instead of commenting, I'd recommend removing code to keep source clean. 
We can always revert PRs if this is needed again.

**Comment by smartguest** [comment]
code has been cleaned up now

**Comment by alanrenmsft** [comment]
would be nice if you could share some screenshots for comparison.

**Review by cheenamalhotra — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
> would be nice if you could share some screenshots for comparison.

+1, and preferably with comparison shots of current stable

**Comment by smartguest** [comment]
@Charles-Gagnon  @alanrenmsft Screenshots have been uploaded showing comparison

**Comment by Charles-Gagnon** [comment]
Could you include some screenshots of dev without a connection name as well? (but still with the "duplicate" connections)

**Comment by smartguest** [comment]
@Charles-Gagnon Added screenshots to the end of the original post.

**Comment by cheenamalhotra** [comment]
Proceeding to merge.

**Pull request merged**
