### PR TITLE
Add write permissions to PR labelling action

### PR DESCRIPTION
**Pull request by corivera**
Opening this PR to see if the permissions issue is fixed with the PR labelling action.

Edit: Label action succeeded, so we can actually merge this change

### CODE REVIEW

**Comment by corivera** [comment]
@kisantia can I merge this change in directly, or should I make a PR for it in main first?

**Comment by kisantia** [comment]
> @kisantia can I merge this change in directly, or should I make a PR for it in main first?

can you change the target branch for this PR to main, then port it to the release branch? So that this will be fixed for the next releases too

**Comment by corivera** [comment]
> > @kisantia can I merge this change in directly, or should I make a PR for it in main first?
> 
> can you change the target branch for this PR to main, then port it to the release branch? So that this will be fixed for the next releases too

Done

**Review by kisantia — APPROVED** [review]

**Comment by corivera** [comment]
I'll skip the validation checks, since this only applied to the one action

**Pull request merged**
