### PR TITLE
Update overflow styling for long database names

### PR DESCRIPTION
**Pull request by goyal-anjali**
This PR fixes 
ADS UI - Long database names are clipped in Assessment dialog - Task 1245920

### CODE REVIEW

**Comment by aasimkhan30** [comment]
@goyal-anjali, can you add screenshots to the PR?

**Comment by goyal-anjali** [comment]
Before -
image
After -
image

**Comment by aasimkhan30** [comment]
This PR does not fix the bug. It just allows some additional characters to be shown. The names can still overflow within the column. 
For example:
image

The correct solution to this problem is to add overflowing scroll to the column cells or add a tooltip.

@brian-harris what do you think we should do here?

**Comment by rchlkm** [comment]
I agree with @aasimkhan30, I think a tooltip would be a better solution to the problem. An overflowing scroll feels like an increase in complexity on the screen, but a tooltip with the full database name could help the user see the full name via hover.

**Comment by goyal-anjali** [comment]
My latest commit - added tooltip with overflow styling and also removed my previous changes. Please check if the issue is fixed now.
Before -
image

After -
image

**Comment by brian-harris** [comment]
it looks like in the comment above the ellipses ...  have been added but the issues count are gone (off screen).

**Review by kburtram — APPROVED** [review]

**Review by Charles-Gagnon — APPROVED** [review]
@goyal-anjali A couple things : 

1. Please update the title to be accurate whenever you make changes (in this case you're no longer just increasing the width)
2. What is the "task" that you mentioned in the description? Do you have a Github issue that you meant to link instead? Typically we should be tracking these issues in Github when we can

**Comment by goyal-anjali** [comment]
Noted @Charles-Gagnon 
Thanks! I'm still learning, reviews are helpful.

**Pull request closed without merging**
