### PR TITLE
Handle tenant failures

### PR DESCRIPTION
**Pull request by aaomidi**
This was an issue that was caught on a live debugging session

### CODE REVIEW

**Comment by aaomidi** [comment]
I'm just used to writing <=, but i essentially meant it as === 0.

**Comment by abist** [comment]
@aaomidi what I meant was we should be checking the length of the array instead of the uri - 

`tenantDetails.length` instead of `tenantDetailsUri.length`

**Comment by aaomidi** [comment]
Where am I using tenantDetailsUri.length?

**Comment by abist** [comment]
@aaomidi In this link I pasted above (line 273) -
```
displayName: tenantDetailsUri.length && tenantDetails[0].displayName
```

**Comment by aaomidi** [comment]
Ooooh sorry, I was looking at my changed code.

**Pull request merged**
