### PR TITLE
fix accessibility issues

### LINKED ISSUE #9472: A11y_SQLAzureDataStudio_Query_Create&Run_ScreenReader: Screen reader does not read the content present inside results grid.
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopApp;#MacOs;#Benchmark;#A11y_SQLAzureDataStudioBenchmark;#A11ySev1;#MAS1.3.1;#Voiceover;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.15.0-insider
Commit: 3a8b74a
Date: 2020-02-11T05:49:41.181Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Mac OS:10.15.3

**Additional Details:**
MAS reference: MAS1.3.1
Mac OS:10.15.3

**Repro Steps:**
1.Launch Azure Data Studio.
2.Navigate to File > New Query
3.Connect to a Server in the Query Editor and choose the credential, and optionally the database to connect to the server.
4.Type a SQL query statement.
5.Click Run.
6.Navigate to Results section.
7.Check if all content present under results grid is read by screen reader.

**Actual:**
The content present below the results grid is not read by screen reader.

**Expected:**
All the content present on the page should be read by screen reader.

**User Impact:**
Screen reader users will not receive all the information that is present on the screen.

**Attachment link reference:**
[9472_A11y_SQLAzureDataStudio_Query_Create&Run_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4296638/9472_A11y_SQLAzureDataStudio_Query_Create.Run_ScreenReader.zip)

### PR DESCRIPTION
**Pull request by anthonydresser**
fixes #9472

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Corresponding changes in slickgrid : https://github.com/anthonydresser/SlickGrid/pull/31

**Comment by Charles-Gagnon** [comment]
@anthonydresser Update remote/package.json as well

**Comment by Charles-Gagnon** [comment]
Also does this fix it for you? The tab headers have a tabindex of -1 which means I can't even tab to them, much less try to tab into the results grid.

**Comment by Charles-Gagnon** [comment]
Ok so the tabbing thing is on purpose as per https://github.com/microsoft/azuredatastudio/pull/6774 - arrow keys are used to navigate between tabs and then tab should be used to go into the content (that isn't how other tab panels like the bottom pane handle it, but ignoring that for now)

But tabbing while on the results tab doesn't focus into the grid that I can see - which the bug is saying should happen.

**Comment by anthonydresser** [comment]
@Charles-Gagnon I fixed that.

**Comment by alanrenmsft** [comment]
I tried the scenario with your branch and it is still not working, there is no way i can get the focus into the results area with keyboard only navigation.

**Comment by anthonydresser** [comment]
It is working for me @alanrenmsft

**Comment by anthonydresser** [comment]
make sure you rerun yarn

**Comment by alanrenmsft** [comment]
I did git clean and rebuilt the whole thing. i opened the node_modules and made sure it is .33 version.

Apr-01-2020 19-09-38

as shown in the gif above, after switching to the results tab, I pressed tab key multiple times, the expected behavior is the keyboard focus goes to the results grid and the buttons on the right side, but the keyboard focus is not going anywhere.

**Comment by alanrenmsft** [comment]
maybe we can meet quickly tomorrow to talk about this.

**Comment by Charles-Gagnon** [comment]
@alanrenmsft It works for me - not sure why yours isn't working.

**Comment by alanrenmsft** [comment]
> @alanrenmsft It works for me - not sure why yours isn't working.

You tried it this morning, right? Anthony made another commit after my comment.

**Comment by anthonydresser** [comment]
Issues 2 and 3 are separate, and are not a part of this PR.

**Comment by anthonydresser** [comment]
Issue 1 is also an existing issue unrelated to these changes.

**Pull request merged**
