### PR TITLE
[Kusto] Update ReadMe file

### PR DESCRIPTION
**Pull request by markingmyname**
This PR fixes #

### CODE REVIEW

**Comment by aaomidi** [comment]
Go to line 98 of gulpfile.hygiene.js, right after the SQL CARBON EDIT, add the following:

`'!**/*.gif',`

**Comment by markingmyname** [comment]
@aaomidi,

That worked. 

Thank you.

**Comment by markingmyname** [comment]
#sign-off

**Comment by markingmyname** [comment]
Had to correct the spelling to one of the gifs.  it works again.

Once processing is complete, I will sign-off again.

**Comment by markingmyname** [comment]
#sign-off

**Review by MsSQLGirl — APPROVED** [review]
Good to go. We can modify later in case there are additional features to add. Thanks!

**Review by aaomidi — APPROVED** [review]

**Pull request merged**
