### PR TITLE
Adding support for inputbox placeholder in declarative table

### PR DESCRIPTION
**Pull request by aasimkhan30**
image

### CODE REVIEW

**Review by Charles-Gagnon — COMMENTED** [review]
Could you just use an actual input component instead?

**Comment by aasimkhan30** [comment]
> Could you just use an actual input component instead?

It is always a pain to add or remove new rows when doing that. Is there some benefit of doing that?

**Comment by Charles-Gagnon** [comment]
Not a huge fan of adding a property that is only used for one specific type of component (and doesn't really make sense for any of the others). What happens if we start wanting to add other similar features for the other types of cells?

Potentially you could at least make it so there's a new cell type DeclarativeTableInput or something that contains all the values for an input box.

But I'm interested in knowing what makes adding/removing rows a "pain". Because if that's the case then we should look into fixing/improving that I would think - especially if there's blocking issues.

**Comment by aasimkhan30** [comment]
> Not a huge fan of adding a property that is only used for one specific type of component (and doesn't really make sense for any of the others). What happens if we start wanting to add other similar features for the other types of cells?
> 
> Potentially you could at least make it so there's a new cell type DeclarativeTableInput or something that contains all the values for an input box.
> 
> But I'm interested in knowing what makes adding/removing rows a "pain". Because if that's the case then we should look into fixing/improving that I would think - especially if there's blocking issues.

The problem with the current implementation is that whenever we want to change dataValues from the extension, we lose the added components from the view. This forces us to recreate new components and add them to the view again. Moreover, we need to have add individual listeners for all the components.

**Comment by Charles-Gagnon** [comment]
Then my preference would be to fix this - because I agree that it's a pretty annoying issue and limits the usefulness of the Component in a declarative table feature 😄 

Given the use case that this is being added for do you see any of these being a huge blocker? I would rather we have one issue (broken adding of components requiring re-creating components each time) rather than one issue + bandaid fixes over said issues when it comes to our public API.

**Pull request closed without merging**
