### PR TITLE
Bump sanitize_html to latest version

### PR DESCRIPTION
**Pull request by kburtram**
Update sanitize-html to 2.7.1 per dependency upgrade recommendation.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@chlafreniere FYI - this is only used by notebook stuff currently

**Comment by kburtram** [comment]
@Charles-Gagnon according to the npm page it says *"The primary change in the 2.x version of sanitize-html is that it no longer includes a build that is ready for browser use. Developers are expected to include sanitize-html in their project builds (e.g., webpack) as they would any other dependency."*  So there is no longer a bundled JS we can link to in the package.  I think there will need to be some custom build script updates needed to consume the update package.

I'm leaning toward abandoning this update.  Let me know if you feel like picking it up.

**Comment by chlafreniere** [comment]
@Charles-Gagnon no issues from my end re: skipping this for now. I'll leave this up to you re: how to best track this potential bundling work in the future.

**Comment by Charles-Gagnon** [comment]
I'll just make a personal note and if this is something that seems reasonable but I don't have time myself I'll make an actual issue to track.

**Pull request closed without merging**
