### PR TITLE
Extensions Gallery Update - December Release

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by alanrenmsft** [comment]
seems like you are trying to do an out of band stable extension gallery update, but the title made me think this should go to RC gallery, if so, our new process is to commit stable release extension updates to extensions\rc1 branch.

**Comment by Charles-Gagnon** [comment]
No this is meant for the December release.

Yeah I forgot about the rc1 branch. But why does it matter if we re-use the same branch? Is there any benefit we get vs just making a new one each release?

**Comment by alanrenmsft** [comment]
@Charles-Gagnon the benefit of using a well known branch is the team won't have to ask the new branch name when they need to send a PR.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon to be accurate, we are not re-using the same branch, in the process doc, it is documented as delete and recreate the extensions/rc1 branch. (to avoid needing to deal with merging)

**Pull request closed without merging**
