### PR TITLE
Bumped extensionsGallery version for langpacks for code complete

### PR DESCRIPTION
**Pull request by smartguest**
August Langpack update to the version gallery.

The generated langpacks can be found in this ad-hoc build: 
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114485&view=results

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@smartguest You should only be updating insiders right now - the stable release should be done in a separate PR against the RC1 branch once that's created.

**Comment by smartguest** [comment]
@Charles-Gagnon Done so, reverted the update to the main gallery file.

**Comment by Charles-Gagnon** [comment]
@smartguest Can we use https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=114412&view=results instead? We should try to avoid using artifacts from ad-hoc builds for published content. 

(you didn't set SIGNED=true in that build anyways so we shouldn't be using it regardless)

**Comment by smartguest** [comment]
I will link to the new product build once the latest source code string updates have been pushed in, for the next morning @Charles-Gagnon

**Comment by Charles-Gagnon** [comment]
Insiders gallery updated!

**Pull request merged**
