### PR TITLE
Updating extensionGallery.json for ML 0.10.0

### PR DESCRIPTION
**Pull request by llali**
VSIX from the release build: https://mssqltools.visualstudio.com/_apis/resources/Containers/3115191/drop?itemPath=drop%2Fextensions%2Fmachine-learning-0.10.0.vsix

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@v-srinisa @chayaverma7 Please merge this in and update the gallery when you get a chance, I've already uploaded the VSIX.

**Comment by chayaverma7** [comment]
The gallery has been updated.

**Comment by alanrenmsft** [comment]
@chayaverma7 I noticed you said gallery has been updated prior to merging the PR. did you use the files from Leila's branch? if so, it could lead to errors, her branch might not be up to date.

**Comment by Charles-Gagnon** [comment]
We discussed this, I've updated the doc instructions to be more clear about this to avoid such situations in the future =)

**Pull request merged**
