### PR TITLE
Alanren/edit data1004

### PR DESCRIPTION
**Pull request by alanrenmsft**
fix issue #2683 
1. The keyboard focus moved away after the new row is added when clicking on a cell in a new row.
2. The keyboard focus is not in the edit data grid when the window is first opened.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
fix for issue #2683 and Focus related issues:
The keyboard focus moved away after the new row is added when clicking on a cell in a new row.
The keyboard focus is not in the edit data grid when the window is first opened.
The keyboard focus is not in the grid when we switching tabs.

fix for issue #2686
now the behavior is consistent with SSMS, a new row will be added only if you have made changes in the last row, previously it is impossible to navigate out of the Edit Data grid using keyboard which is an accessibility issue.

**Comment by alanrenmsft** [comment]
@kburtram @MattIrv @anthonydresser I have updated this PR, please take another look.  Thanks!

**Comment by MattIrv** [comment]
Looks good to me. This would be a good candidate for some automated testing though since the logic is kind of complex

**Comment by alanrenmsft** [comment]
@MattIrv Thanks, Will do!

**Pull request merged**
