### PR TITLE
Fix server and database dialog width

### PR DESCRIPTION
**Pull request by barbaravaldez**
1. Fix dialog width to fit the horizontal tabs: 

databasePropertiesWidth
serverPropertiesWidth

For: https://github.com/microsoft/azuredatastudio/issues/24403

### CODE REVIEW

**Comment by ssreerama** [comment]
Is this a temporary update to avoid the scroll bar? Should we also adjust the input items to occupy the full width?

**Comment by barbaravaldez** [comment]
> Is this a temporary update to avoid the scroll bar? Should we also adjust the input items to occupy the full width?

@erinstellato-ms, any thoughts here for adjusting the width for the other items in the dialog?

**Comment by erinstellato-ms** [comment]
@barbaravaldez Can you explain what you mean by "adjusting the width for the other items in the dialog"?  I need a visual (before and after) if possible...

**Comment by corivera** [comment]
@barbaravaldez Could you break out the package.json changes into a separate PR? I don't think the UX width changes would hit the shiproom bar for ask mode.

**Comment by ssreerama** [comment]
@erinstellato-ms , increasing the input textbox widths to fit the increased dialog width
 image

**Comment by erinstellato-ms** [comment]
@barbaravaldez I don't think we need to increase the width of the textboxes just because the window is wider.

However, in the DB properties that @ssreerama did, he does have a scrollbar at the top of the window.  Can we be consistent between the two properties windows?  Either both have a scrollbar, or neither does.

**Pull request closed without merging**
