### PR TITLE
Adds support for installing azdata on Linux

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Will follow up with updating tests to account for the new logic.

A couple things I want to iron out but will do in separate PRs : 

1. Currently this prompts for each command executed which gets pretty spammy. Will look into doing all commands at once to reduce down to one prompt
1. Making sure errors are localized correctly when displayed to user
1. Verifying lsb_release usage and how it works with the download path for the repo

### CODE REVIEW

**Comment by alanrenmsft** [comment]
please sync up with Arvind, he already implemented this feature in resource-deployment extension and meanwhile it also handles more linux distributions. we should create a package to handle this so that it can be shared by different extensions.

**Comment by Charles-Gagnon** [comment]
Well - the intention is that other extensions will use this extension to query that. I don't think making a package here makes sense. That's just extra overhead for something we're only rarely going to use.

I'll be updating resource deployment to use this extension and removing Arvind's code sometime down the line. (I based all this logic off of his work)

**Comment by Charles-Gagnon** [comment]
Not sure what you mean by "handles more distributions". He only has support for apt - nothing else like yum or any other package managers. So this supports the exact same distributions that his does.

@ranasaria Correct me if I'm wrong here.

**Comment by alanrenmsft** [comment]
hmm, I remembered there used to be multiple distro handling logic but it seems there is only one now.

**Pull request merged**
