### PR TITLE
Microsoft logo in SVG format

### PR DESCRIPTION
**Pull request by rajmera3**
Adding SVG for microsoft logo. Will allow for scalable use of image in notebooks, extension websites, etc

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Could you include an embedded image of what this looks like?

Was this from a specific ask or are you going to be following up with component owners to get this updated in the places that need it?

**Comment by rajmera3** [comment]
@Charles-Gagnon 
> * Could you include an embedded image of what this looks like?
https://microsoft.sharepoint.com/teams/BrandCentral/Pages/Bundles/Microsoft_logo_BlackWhiteandGray_All_sizes.aspx - first image seen here.
> * Was this from a specific ask or are you going to be following up with component owners to get this updated in the places that need it?
No, I noticed that we were currently using the .png file in the folder, but its resolution does not scale with size. Will be following up with owners to get it updated in notebooks/ADS
> * I think it'd be better just to keep it as microsoft_logo.svg unless there's a specific reason you need the other stuff in the title.
I agree -> will change to microsoft_logo_gray.
> * Is this dark/light/contrast theme friendly?
It is light/contrast theme friendly - will need a version with white text for dark themes.

**Comment by rajmera3** [comment]
@Charles-Gagnon Do you mind explaining why the build failed?

**Comment by aaomidi** [comment]
@rajmera3 Just started another one, the build had been queued before I made the changes. Next one should be green :)

**Pull request merged**
