### PR TITLE
Remove unwanted icon override

### LINKED ISSUE #23512: Post merge > OE icon issues observed in light theme
- Azure Data Studio Version: Insiders (Light theme)
- OS Version: Windows 11 

1. OE node icon changes to white icon on selection:
2. Azure tree icons are not rendering

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Fixes #23512 

Icons were being overridden by inverse icon on focus - removed custom CSS.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra Did you check the other light color themes (specifically the ADS light theme)? Those have a darker highlight color so let's make sure it still looks good there

**Comment by cheenamalhotra** [comment]
Oh! I didn't catch other darker highlights.. let me rethink a better way to solve this..

**Review by aasimkhan30 — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
We might want to just remove the themes that don't look good for now (the new ones that were added with the latest merge at least) until we can have time to go through and thoroughly test them. Unfortunately the way we do icons (static SVGs) is different from how VS Code does theirs (custom font file) so choosing the correct color will be difficult.

**Comment by cheenamalhotra** [comment]
We can fix it with the new Azure icons planned for server tree (similar as Azure tree).. I guess now is the time to do it soon 👀

**Comment by cheenamalhotra** [comment]
Closing this for now - will address with new icons instead.

**Pull request closed without merging**
