### PR TITLE
Bump required azdata engine version for schema compare

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by udeeshagautam** [comment]
@Charles-Gagnon 
@kisantia  pointed out that Schema Compare doesn't really need new ADS to operate, it only needs new ADS (new mssqltools) to show new bug fixes... it will work though without it also.... So leaving it up to you if you want to get this in or not...

**Comment by Charles-Gagnon** [comment]
Not sure I understand - is there functionality that was added in 1.10 that is required for the extension to operate (API changes and the like)?

**Comment by kisantia** [comment]
There weren't any API changes. The extension just needs the new SqlToolsService changes to get a couple changes that were made in DacFx.

**Comment by Charles-Gagnon** [comment]
Alright, that still sounds like enough of a reason to bump the required version to ensure that the extension is using the correct version of the sqltoolsservice.

**Pull request merged**
