### PR TITLE
Use codicons instead of svg's

### PR DESCRIPTION
**Pull request by abist**
These areas haven't been touched in a long while, and we have a better and efficient way to use icons rather than have redundant files in the repo. There are way more places where this can be done, but I tested and verified the areas I know and have worked with.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]
Awesome, love seeing this kind of cleanup.

It would be helpful to compile a list of the icons that were changed because of this (with screenshots preferably) so we can make sure they're verified by different people on multiple platforms.

Did you verify this on a bundled build as well? Sometimes that messes up the CSS so would be good to do so.

**Comment by abist** [comment]
@Charles-Gagnon I haven't tried the bundled build, let me try that

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
screenshots? also the PR validation build failed.

**Comment by Charles-Gagnon** [comment]
@abist Are you still planning on getting this in?

**Comment by kburtram** [comment]
@abist do you have plans to do anything else with this PR?  or should it be closed as part of stale PR cleanup?

**Pull request closed without merging**
