### PR TITLE
Add big-data-cluster and resource-deployment to sqlBuiltinExtensions

### PR DESCRIPTION
**Pull request by ranasaria**
This PR fixes does two things:

1. Moves vscode for resource-deployment extension to dependencies section from devDependencies as the product code depends on it.
2. It adds two extensions to sqlBuiltInExtensions so that they are their separate packages. I am doing this to workaround "too many files open" issue observed during linux builds. Discussing with Amir, this looked like a good change to do, in any case but I am not too sure about it. So I thought I will open a PR and discuss the pros and cons of doing this here.

### CODE REVIEW

**Comment by aaomidi** [comment]
You shouldn't need the vscode package.

My suggestion is essentially only valid if there wasn't anything else we could do to decrease the size of the extension.

**Comment by ranasaria** [comment]
> 1. Why do you need vscode as a run-time dependency?
I am consused, if this package uses vscode.Event<T> from the vscode package and vscode.commands.registerCommand and other similar functionality from the vscode package, then is that not a run-time dependency?

**Comment by ranasaria** [comment]
> Vscode dependency includes a testing framework which isn't necessary for production

We use vscode.Event<T> and vscode.commands.registerCommand and other functionality from vscode package, that is not for testing but for product features.

**Comment by aaomidi** [comment]
That's not the vscode package, that functionality is included as part of azure data studio.

The vscode package for our context only does testing: https://www.npmjs.com/package/vscode

**Comment by ranasaria** [comment]
Abandoning as this change is not needed.

**Comment by kevcunnane** [comment]
FYI in case Arvind was wondering - we dynamically inject the azdata and vscode modules at runtime by hooking the require / import calls. Hence no NPM package reference is needed / none should be included for the dependencies. Only need for devDependency to enable testing, and for extensions not in the Azure Data Studio repository so that they can pull down a typings file to compile against.

**Comment by Charles-Gagnon** [comment]
And for testing we should really be using vscode-test instead. (Typings are now from @types/vscode)

https://github.com/Microsoft/vscode-extension-vscode#readme

**Comment by aaomidi** [comment]
@Charles-Gagnon vscode themselves aren't using that package for built-in extensions I believe. Might be wrong?

**Comment by Charles-Gagnon** [comment]
That's correct - I don't know why but their public stance appears to be using the vscode-test. I'm not saying we should go through and update all ours now but something to keep in mind (I haven't checked whether vscode is getting the same updates as vscode-test for example. At some point I imagine that's going to be deprecated)

**Comment by aaomidi** [comment]
I actually looked into updating this and I realized I'm going to need to copy a lot of code that already exists in `vscode`. Like basically a copy/paste. And we have to do that for every single extension - so it might not be worth it?

**Comment by Charles-Gagnon** [comment]
Like what? There doesn't appear to be much there besides the testrunner and the typings file

**Comment by aaomidi** [comment]
I don't remember anymore - should look at it again.

**Comment by Charles-Gagnon** [comment]
Don't spend too much time on it - I'm not suggesting we actually do it at this point.

**Pull request closed without merging**
