### PR TITLE
Remove duplicate extensions from browse filter

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Original : 

image

Fixed : 

image

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Also I noticed that the placeholder value is hardcoded to just say sqlproj

image

Not sure if you want to fix that - maybe just something generic like `Select project file`?

**Review by kisantia — APPROVED** [review]
it's a little weird showing SQL Database and SQL Edge as separate since they have the same file extension, but it's been like that since the edge template was added

**Comment by kisantia** [comment]
> Also I noticed that the placeholder value is hardcoded to just say sqlproj
> 
> https://github.com/microsoft/azuredatastudio/blob/main/extensions/data-workspace/src/common/constants.ts#L67
> 
> image
> 
> Not sure if you want to fix that - maybe just something generic like `Select project file`?

ah yes that was copied from the mockups and would be good to fix, especially since there's a pg projects extension being worked on that will use these dialogs too

**Comment by Charles-Gagnon** [comment]
> it's a little weird showing SQL Database and SQL Edge as separate since they have the same file extension, but it's been like that since the edge template was added

Agreed, but I'm not really sure that there's a clean way to handle that since the names are so much longer. I think it's fine for now unless you start getting a ton of duplicate entries.

**Review by zijchen — APPROVED** [review]

**Pull request merged**
