### PR TITLE
Update schema compare extension in insiders

### LINKED ISSUE #10967: Schema compare from sql proj doesn't have Source set to dacpac
Steps to Reproduce:
1. Right click on project and select "Schema Compare"
2. Schema compare window opens with source text box empty

Expected:
Source should be pre-populated with the dacpac created from building the project

### PR DESCRIPTION
**Pull request by kisantia**
Update schema compare extension in insiders to 1.5.0 for the changes that Sql Project needs. This PR fixes #10967.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
have you already updated the version of the this extension in main branch? shall i just grab the vsix from there?

**Comment by kisantia** [comment]
@alanrenmsft Nope haven't updated the version in main yet. Yup the vsix in the current builds should be good to take.

**Comment by alanrenmsft** [comment]
@kisantia confused 😕 , I just checked, it is 1.15 now, what do you mean by "Haven't updated the version in main yet" ?😆

**Comment by kisantia** [comment]
@alanrenmsft the version got bumped to 1.5 after 1.4 got released last time in March. I meant I haven't updated again since that.

**Comment by alanrenmsft** [comment]
i see, i have uploaded the latest vsix.

**Comment by kisantia** [comment]
Thanks Alan! :)

**Comment by alanrenmsft** [comment]
@kisantia extension gallery updated, I was able to install it, please do some testing to make sure

**Pull request merged**
