### PR TITLE
Enables streaming job validation, minor bugfix

### LINKED ISSUE #13233: "Validate External Streaming Job" not showing up when external streaming job is added to project
Steps to Reproduce:

1. Add an external streaming job to a project
2. Right click on newly added external streaming job to open context menu

Expected: "Validate External Streaming Job" should be the first option in the context menu
Actual: only "Exclude from project" and "Delete" are in the context menu

it shows up correctly if the project is closed and opened again
validateExternalStreamingJob

### LINKED ISSUE #13234: No message after clicking "Validate External Streaming Job"
There should be an information message if successful or error message if validation failed, but there isn't any that pops up. This is with sqltoolsservice updated to 3.0.0-release.50.

I tried adding a break point on line 595 and it wasn't getting hit. https://github.com/microsoft/azuredatastudio/blob/342ff47e512bd30b66ac0fdad0d487a2235f2a18/extensions/sql-database-projects/src/controllers/projectController.ts#L593-L600

### PR DESCRIPTION
**Pull request by Benjin**
Fixes #13233 by correctly tagging the in-memory object at creation time; previously only got tagged when loaded from sqlproj
Fixes #13234 by re-enabling the validation menu item now that SqlToolsService is updated

### CODE REVIEW

**Review by kisantia — APPROVED** [review]
I just merged the extension version bump, so please merge with main so that the PR validation creates the extension with the updated version. I think the package.json also needs to be updated so that the engine dependency "azdata": ">=1.24.0" since this depends on the latest sqltoolsservice changes

**Comment by udeeshagautam** [comment]
+1 to @kisantia's comment and thanks for fixing these quickly

**Review by udeeshagautam — APPROVED** [review]

**Comment by udeeshagautam** [comment]
You might also have to update the PR for extension gallery.. right @kisantia?

**Comment by kisantia** [comment]
yup we'll have to send out a new PR to update RC extension gallery and insiders

**Review by udeeshagautam — APPROVED** [review]

**Pull request merged**
