### PR TITLE
Update PowerShell extension to v2020.3.0

### PR DESCRIPTION
**Pull request by rjmholt**
Updates the version of the PowerShell extension in ADS to 2020.3.0.
**Note**: This is an automated PR.

### CODE REVIEW

**Comment by rjmholt** [comment]
> Have you gone through testing with the latest stable/insiders versions?

What do you mean by that?

**Comment by Charles-Gagnon** [comment]
No specific process, just making sure that you've tested that the extension works correctly and there doesn't seem to be any breaking issues. The amount of testing done is up to you but we've had some issues with extensions being broken because of changes made in ADS so it's good to have you verify things before pushing an update on people.

**Comment by rjmholt** [comment]
> just making sure that you've tested that the extension works correctly and there doesn't seem to be any breaking issues

Understood. I've tested out the extension in ADS on Windows and it seems to be working well.

I should say that with only a couple of us on the extension and already testing on multiple platforms with VSCode, we've been depending on ADS behaving like VSCode.

> broken because of changes made in ADS

Is there any list or indication of what these changes are, or how we could target ADS specifically in our extension code to deal with those changes?

> it's good to have you verify things before pushing an update on people

We have a preview channel in VSCode to help with this, so maybe that's a strategy we could take for ADS.

**Comment by Charles-Gagnon** [comment]
Thanks - I appreciate the extra validation. Trusting us to behave like VS Code is generally safe and for your scenario I'd say it's even safer since you don't rely on ADS-specific APIs. But since we do disable some parts of the VS Code API it's still probably a good idea to do some basic smoke test when updating the extension (we can help with this too if you have guidance on what kind of things to test)

The particular issues we've had are generally around the azdata API so unlikely to affect you - and in general these issues have just been bugs and so aren't something we can inform you about ahead of time unfortunately.

What do you mean you have a preview channel? Is it just this? https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview We could do something similar - although I'm not sure it's worth the effort.

In the end I'll leave it up to you to determine if you wanted to do anything extra in this case - I don't see a huge issue with pushing the updates to stable as you release them, I just want to make sure the customers are having the best experience they can 😄

**Comment by rjmholt** [comment]
> But since we do disable some parts of the VS Code API it's still probably a good idea to do some basic smoke test when updating the extension

Absolutely!

> (we can help with this too if you have guidance on what kind of things to test)

Hmmm, we don't but we should definitely write some down if only for our own sake (/cc @TylerLeonhardt, @SydneyhSmith)

> and in general these issues have just been bugs and so aren't something we can inform you about ahead of time unfortunately.

Gotcha, just wanted to confirm if there were any significant differences we should know about.

> What do you mean you have a preview channel? Is it just this? https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell-Preview We could do something similar - although I'm not sure it's worth the effort.

That's the one (the only way to make a "preview channel" in the VSCode marketplace was to make a new extension it seems). Agreed on the effort, but if we are able to better automate our releases that bar might lower.

> I just want to make sure the customers are having the best experience they can 😄

Yes, absolutely. And thanks for following up with me and talking me through it all. There's definitely more we (on the PowerShell team) can do here. We're still sifting through a bit of debt, but hopefully we can find time to make improvements.

**Comment by Charles-Gagnon** [comment]
Awesome, yeah everything sounds good. Let us know what we can do to make this easier for you as well - we definitely want to make this process as easy as possible for you and other extension authors.

**Comment by Charles-Gagnon** [comment]
@rjmholt Just published the updated gallery files so the update should be live now!

**Pull request merged**
