### PR TITLE
Update to edit data grid panel.

### PR DESCRIPTION
**Pull request by smartguest**
This PR makes changes to edit data to allow for the support of hitting enter to commit changes and also numerous changes to try and mitigate errors when an invalid cell is entered, so to allow the user to continue editing, and it brings the experience to be closer to that of SSMS (as much as slickgrid can do). Additionally, it helps with a bug where if a user decides to click on another cell while the table is loading, the table will fail to load fully, and edits won't work. Now the table will be disabled from view before its fully loaded and the first cell is selected.

addresses the following issues (others may be addressed by this PR too but these are the ones currently known to be addressed):
https://github.com/microsoft/azuredatastudio/issues/19126

https://github.com/microsoft/azuredatastudio/issues/13666

### CODE REVIEW

**Comment by smartguest** [comment]
There is a bug involving adding an invalid cell to the new row and clicking on a new cell that is causing the select focus to not revert, I am addressing it currently right now.

**Comment by alanrenmsft** [comment]
@smartguest please add a few GIF images to show the changes.

**Comment by smartguest** [comment]
Gif showing a few different scenarios involving the new row: 

EditDataFixNoDirtyRows

**Comment by smartguest** [comment]
Switching branch to a different one as this branch removes the dirty cell functionality, which is considered a regression, the new branch will support dirty rows.

**Pull request closed without merging**
