### PR TITLE
[SQL Migration] Release v1.4.4 to Worldwide

### PR DESCRIPTION
**Pull request by raymondtruong**
This PR updates the wolrdwide extension gallery to the latest version of the SQL Migration extension. This version was already released to insiders in https://github.com/microsoft/azuredatastudio/pull/22788 and the same vsix can be used.

### CODE REVIEW

**Comment by alanrenmsft** [comment]
> This PR updates the **insiders** extension gallery to the latest version of the SQL Migration extension...

is this: `insiders` a typo? @raymondtruong

**Comment by raymondtruong** [comment]
> > This PR updates the **insiders** extension gallery to the latest version of the SQL Migration extension...
> 
> is this: `insiders` a typo? @raymondtruong

yep, good catch - this is intended to update the WW gallery. Just copied and pasted the wrong PR description

**Comment by alanrenmsft** [comment]
I see, btw, we call it stable build extension gallery :)

**Comment by raymondtruong** [comment]
> I see, btw, we call it stable build extension gallery :)

noted, will keep that in mind for the future - thanks for pointing that out :)

**Pull request merged**
