### PR TITLE
Added Notebook telemetry for livesite notebooks (#9948)

### LINKED ISSUE #9906: Custom Metadata gets deleted from notebooks
- Azure Data Studio Version: 1.16.1

**Steps to Reproduce:**

1. Edit a notebook .ipnb file in text editor and add a field to metadata property.
2: Open that notebook in ADS, edit and save

**Observation:**
Custom field added to the metadata properties disappears

**Expected:**
ADS should retain custom properties

### PR DESCRIPTION
**Pull request by rajeshka**
* Added Notebook telemetry for livesite

* added back the metadata retension code

* Unified Telemetry services

* fixed names

* Fixed texts to use new NullAdsTelemetryService

* Validate GUID before sending it

* made GUID check a bit more robust

Co-authored-by: Rajesh Kamath <rajkashop@hotmail.com>

This PR fixes  #9906

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@rajeshka Do we need this in stable? We produce separate builds for SAW so this doesn't seem like something that needs to be pushed to stable.

**Comment by rajeshka** [comment]
@Charles-Gagnon  LiveSite Notebooks will be used everywhere and not just SAW so we need this in stable.

**Comment by aaomidi** [comment]
Merging PR based on approval from @qifahs

**Pull request merged**
