### PR TITLE
Bump GitHub Copilot extension version to 1.128.504

### LINKED ISSUE #24743: Bump GitHub Copilot extension version to 1.128.504
Upgrade Copilot version in the insiders extension gallery to 1.128.504 to bring in the latest updates to the extension after VS Code 1.82 was merged into ADS.

### PR DESCRIPTION
**Pull request by lewis-sanchez**
This PR closes #24743

Update Copilot version in the insiders extension gallery to 1.128.504 after VS Code version 1.82 was merged into ADS.

Link to files to upload: https://microsoft-my.sharepoint.com/:f:/p/lewissanchez/EukjwrSRcRJMvQRR5FN50bMBZ6BD2rhfd0rnsp4Hv3iuGw?e=mRxXHz

### CODE REVIEW

**Comment by lewis-sanchez** [comment]
Does anyone have any context on what the GitOps/MandatoryFiles check is mad about? I only modified the insiders gallery copilot extension version.

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Did you figure out what that was? It looked like there was a rebase or something mucking up the commit history, did that have something to do with it?

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
@Charles-Gagnon I merged it with the release/extensions branch and the error is gone.

**Comment by Charles-Gagnon** [comment]
Yeah, weird. @lewis-sanchez do you remember how you madethis branch? And what commands you ran afterwards?

**Comment by lewis-sanchez** [comment]
@Charles-Gagnon, I made the branch for this PR by running `git pull` while having the `release/extensions` branch checked out locally in git to update my local branch. Then I branched off `release/extensions` by using `git checkout -b lewissanchez/feat/upgrade-copilot-to-1.128.504`. I made the file change shown in the PR, committed, and pushed.

My mistake could have been that the first time I opened the PR (#24744), I forgot to switch out `main` for `release/extensions`
image

So for a moment PR #24744, in the screenshot, was saying that I wanted to merge `lewissanchez/feat/upgrade-copilot-to-1.128.504` into `main` instead of `release/extensions`. I made that correction, but the problem with the license persisted, so I closed it. Then I opened a second PR #24745, and opened it targeting `release/extensions` from the start where I was also seeing the same error about a missing/dropped license.

**Pull request merged**
