### PR TITLE
port PR 9937 to release branch

### PR DESCRIPTION
**Pull request by alanrenmsft**
port the fix for https://github.com/microsoft/azuredatastudio/pull/9975 to release branch

### CODE REVIEW

**Comment by kburtram** [comment]
@alanrenmsft could you please link to the issue that Ken approved for this bug port?

**Comment by alanrenmsft** [comment]
issue: https://github.com/microsoft/azuredatastudio/issues/9975, I will ask Ken to take a look at the issue.

**Comment by alanrenmsft** [comment]
@kburtram, Ken has approved the issue.

**Comment by chlafreniere** [comment]
We discussed this during the DRI meeting, and decided that I should handle merging Alan's PRs while @kburtram is sick.

**Pull request merged**
