### PR TITLE
vbump STS

### PR DESCRIPTION
**Pull request by alanrenmsft**
bring in the fix for the sql variant column handling.

image

@smartguest please confirm your XELite changes are also good to go for the release branch.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]

**Review by Charles-Gagnon — CHANGES_REQUESTED** [review]
Oh wait, yeah no we can't take this with the XELite changes. Guess I was too optimistic with not having any ask mode changes...

**Comment by Charles-Gagnon** [comment]
Unfortunately I think the most straightforward route is to roll back those changes temporarily, get a new build and use that for the release and then merge in the XELite changes later. @smartguest could you work with @alanrenmsft on doing that?

**Comment by alanrenmsft** [comment]
let me revert the xelite changes now, @smartguest lets merge the xelite changes when the new release is out. but long term, looks like we should have a release branch for STS as well.

**Comment by Charles-Gagnon** [comment]
That gets real tricky with the whole automated release stuff that the STS branch does currently. Something to keep on our radar but I'm not sure there's a good solution without some hefty refactoring of how STS releases are published.

**Comment by alanrenmsft** [comment]
the new process should also consider STS is being used by vscode-mssql extension as well.

**Pull request closed without merging**
