### PR TITLE
Remove "New Python Installation" option in Configure Python dialog

### PR DESCRIPTION
**Pull request by corivera**
The current provided python package has gotten pretty old and is nontrivial to update, so we decided to deprecate the New Python Install option. We already automatically detect installed versions of python and also provide a guided experience to install required pip packages, so the only work a user would need to do is install python on their machine before using jupyter notebooks. I improved the automatic version detection as well, so it picks up more recent versions of python.

I also cleaned up some unused jupyter code in the machine-learning extension at the same time, since I already had to make some changes in that area as part of this larger work.

Screenshots of new dialog UX:

1. With python already setup
EditPath

2. When specifying different versions
PathDropdown

### CODE REVIEW

**Comment by corivera** [comment]
One question I had is whether it's worth it to still have that first "Edit" UX. Before it was used to cover up all the controls for New/Existing install to reduce clutter when python had already been configured, but now the page looks basically the same either way.

@kisantia Your thoughts?

**Comment by kisantia** [comment]
> One question I had is whether it's worth it to still have that first "Edit" UX. Before it was used to cover up all the controls for New/Existing install to reduce clutter when python had already been configured, but now the page looks basically the same either way.
> 
> @kisantia Your thoughts?

To make sure I'm understanding the question - is it if the first screenshot scenario should be removed and it just always be the second screenshot?

**Comment by corivera** [comment]
> > One question I had is whether it's worth it to still have that first "Edit" UX. Before it was used to cover up all the controls for New/Existing install to reduce clutter when python had already been configured, but now the page looks basically the same either way.
> > @kisantia Your thoughts?
> 
> To make sure I'm understanding the question - is it if the first screenshot scenario should be removed and it just always be the second screenshot?

Correct

**Comment by corivera** [comment]
I'll make that change in a subsequent PR to keep this one from getting more complicated.

**Review by Charles-Gagnon — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

**Pull request merged**
