### PR TITLE
STS VBump with v147

### PR DESCRIPTION
**Pull request by ssreerama**
This PR fixes #

### CODE REVIEW

**Comment by alanrenmsft** [comment]
I was just about to do it:) you should include more information in your PR about the changes you are bringing in.

these are the changes:
1. table designer change
2. query plan code port from SSMS
3. vbump of dacfx compact level 150 to 160 update.

image

**Review by alanrenmsft — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
And importantly the schema compare rollback that @Benjin did.

@ssreerama I assume you are doing this on his behalf or something?

**Review by Charles-Gagnon — APPROVED** [review]
Looks good, but make sure you have confirmation from @Benjin that his change should be going in.

**Comment by alanrenmsft** [comment]
> Looks good, but make sure you have confirmation from @Benjin that his change should be going in.

@Charles-Gagnon Benjin has reverted his changes in both ADS and STS and he is working on fixing the issue he found last week. 

I asked Benjin to revert the changes in STS so that other folks can bring in new version of STS just like this one.

**Comment by ssreerama** [comment]
Sorry, I should mention some information in this PR. @Charles-Gagnon , as Alan said, Benjin has reverted the changes that have the ADS SC dependent changes. This PR includes the support of **DacFx160** Nuget instead of DacFx_SqlProj(this branch is archived). Thanks.

**Comment by kisantia** [comment]
@ssreerama fyi build for sql projects on linux is broken with this DacFx build https://github.com/microsoft/DacFx/pull/51#issuecomment-963645958

@zijchen already has a CR out with the fix for this in Dacfx, so we'll need to make sure to update the Dacfx nuget used here again before the December release.

**Pull request merged**
