### PR TITLE
Revert "Notebook Views Actions"

### PR DESCRIPTION
**Pull request by kburtram**
Reverts microsoft/azuredatastudio#16207

### CODE REVIEW

**Comment by kburtram** [comment]
@dhgrajeda the Notebook views PR broke webmode.  Please let me know if you can prepare a fix for this today or if we should revert this change until a fix can be prepared?

**Comment by dhgrajeda** [comment]
I think I have a fix. I am currently running a web build to verify it.

**Comment by kburtram** [comment]
@dhgrajeda thanks!  once you have a PR out we can close this one.

**Comment by dhgrajeda** [comment]
Added PR #16707. It reverts only the addition of the library that is causing problems.

**Pull request closed without merging**
