### PR TITLE
add key command ctl + L to run query plan

### PR DESCRIPTION
**Pull request by hungrybear88**
add key binding for #1127  ctrl + L , does this seem ok or should the binding be something else

@kburtram  @MattIrv

### CODE REVIEW

**Comment by kburtram** [comment]
@hungrybear88 in SSMS it looks like `Ctrl-L` gets the estimated plan.  This is getting the actual plan.  I wonder if this matters?

**Comment by hungrybear88** [comment]
we could change to actual which is ctrl M  in SSMS

**Comment by kburtram** [comment]
@hungrybear88 perhaps using Ctrl-M is preferable to maintain compatibility with SSMS for the same feature.  This makes it easier for users coming from SSMS to not have to learn new things. 😄

**Comment by hungrybear88** [comment]
@kburtram  ok i have changed to Ctrl-M  please merge

**Comment by kburtram** [comment]
@hungrybear88 thanks, merged!

**Pull request merged**
