### PR TITLE
Auto Column Sizing

### PR DESCRIPTION
**Pull request by anthonydresser**
Adds auto column sizing behind the `resultsGrid.autoSizeColumns` setting

It does have a performance impact for large datasets.

`SELECT CAST(REPLICATE(CAST('X' AS VARCHAR(MAX)), 1024 * 1024 * 5) AS VARBINARY(MAX)) as num1, CAST(REPLICATE(CAST('X' AS VARCHAR(MAX)), 1024 * 1024 * 5) AS VARBINARY(MAX)) as num2`
The UI will hang for a few seconds (you can run with autosize and without to see the difference). And the impact will be linear for ever increasing data sets sizes (both number of columns and cell sizes impact performance).

### CODE REVIEW

**Comment by kenvanhyning** [comment]
Can we add some visual element indicating work is going on?  Looking forward to the streaming results work, will this have issues with partial data streaming in?

**Comment by kburtram** [comment]
@anthonydresser would it reduce the perf impact if we update `getMaxColumnTextWidth`  to not scan the entire dataset?  Perhaps if we look at the first 10 rows (with reasonable minimum column sizes) this may be a good enough column width with less measuring cost.  Though I agree with @kenvanhyning if the sizing can take a couple seconds with out be good to have some UI busy indicator...typically ~500ms is when people start noticing a delay.

**Comment by anthonydresser** [comment]
@kburtram it doesn't scan all the data, it only scans whats in the current viewport, which is most cases for us its 8-10 rows

**Comment by kburtram** [comment]
@anthonydresser do you think we should put an upper limit like 8 rows, so we don't slow down in cases when more rows are visible?  I think on larger monitors it could easily be 30+ rows?  Or this doesn't matter?  Just wonder why this is taking multiple seconds and if we can make it faster somehow?

**Comment by anthonydresser** [comment]
Measuring in html requires putting the data on the dom and letting the chrome engine render it, then measure how long it is. This is slow for large data and lots of data.

The real only alternative is just have a constant for characters and check the length of the string and just do a multiplication, but this is really inaccurate since font and font styles can vastly change how long a string actually is displayed as.

**Comment by kburtram** [comment]
@anthonydresser I would guess that using some heuristic based on fixed character width and expected number of characters for various data types (probably with some simple scanning of the data) would be much better than the current sizing, and probably good enough for most common use cases.  This would avoid the render then resizing.

**Comment by anthonydresser** [comment]
I'll merge this in since it works for the most part and is optional opt in. We can continue to tune the performance based on user feed back if necessary.

**Pull request merged**
