### PR TITLE
Open the dialog when someone clicks connect

### LINKED ISSUE #10025: Connect button on query editor is not working
- Azure Data Studio Version: 
latest master

Steps to Reproduce:
1. make sure you don't have any active connections
2. open a new query window
3. click on the connect button

Expected:
The connection dialog appears

Actual:
nothing happens

### PR DESCRIPTION
**Pull request by aaomidi**
Fixes #10025

https://github.com/microsoft/azuredatastudio/pull/10026

### CODE REVIEW

**Comment by anthonydresser** [comment]
Can you run an ad hoc build against this to verify it fixes the smoke tests

**Comment by aaomidi** [comment]
Good idea!

https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=61604&view=results

**Comment by anthonydresser** [comment]
It doesn't look this this is fixing the smoke test, but my revert does fix the smoke test. So i'm going to merge my revert while this is figured out.

**Comment by kburtram** [comment]
Closing stale PRs

**Pull request closed without merging**
