### PR TITLE
Vsix build task for langpacks

### PR DESCRIPTION
**Pull request by smartguest**
This PR is the same as #15388 but it removes the refresh-langpack function as that function is still under work due to new findings about how extensions are localized.

This only packages the current lang packs as vsix files.

### CODE REVIEW

**Review by aasimkhan30 — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@smartguest Can you please link a test build that has the generated langpacks for verification?

**Comment by smartguest** [comment]
@Charles-Gagnon This build should produce lang packs as part of the drops, its not complete yet. https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104757&view=results

**Comment by Charles-Gagnon** [comment]
So it seems like the langpacks also include translations for non-builtin extensions such as dacpac, schema compare, import, etc. Is that intended? I would expect those to be bundled into the extensions themselves.

**Comment by smartguest** [comment]
@Charles-Gagnon This uses the current langpack source files right now to create the drops, but once I merge the new langpacks first into ADS, this function will use those to create the new langpacks without the unnecessary extension translations

**Comment by Charles-Gagnon** [comment]
Alright, I'd suggest we wait until those changes get in and then do another test build to verify that things look accurate after that.

**Comment by smartguest** [comment]
@Charles-Gagnon Just created a build with the latest language packs, so far they're generated properly https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=104921&view=artifacts&pathAsName=false&type=publishedArtifacts

**Review by kburtram — APPROVED** [review]

**Comment by kburtram** [comment]
@smartguest looks fine to me, but please follow-up with @Charles-Gagnon if he is waiting for changes here.  Thanks!

**Review by Charles-Gagnon — APPROVED** [review]

**Pull request merged**
