### PR TITLE
Trying to get Ext localization to work

### PR DESCRIPTION
**Pull request by udeeshagautam**
This is the change I had to do to in ext build get non-in-builds to understand localization. Along with this we also need the per file i18n.json - Will change loc tool to produce that.

### CODE REVIEW

**Comment by kburtram** [comment]
Please verify the CI builds are unrelated to the change.

**Comment by aaomidi** [comment]
The failure is unrelated to this change. Looks like yarn installer failed for a second there.

https://dev.azure.com/azuredatastudio/azuredatastudio/_build/results?buildId=1377&view=logs

**Comment by udeeshagautam** [comment]
Thanks for taking a look. Not checking in just yet since I have some new pointers on getting the sign files work too... so will look into that as well

**Comment by udeeshagautam** [comment]
@kburtram will abandon this and move forward with other one :)

**Pull request closed without merging**
