### PR TITLE
Add Deferred to azdata

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
This is used often enough and is generally useful enough to just add to our API so extensions don't have to keep redefining it.

### CODE REVIEW

**Comment by aaomidi** [comment]
Oh wow thank you for changing all instances of this.

**Comment by anthonydresser** [comment]
Keep in mind, deferred is general considered an anti-pattern.

**Comment by aaomidi** [comment]
Deferred is only an anti-pattern if its used in a redundant way, rather than it just being an antipattern as a whole from my understanding.

**Comment by anthonydresser** [comment]
The need to use a deferred promise generally means your code flow is wrong (anti-pattern). Its far too easy to create a promise that will never actually be resolved using deferred and not know that is what your code is doing. There are some cases that deferred makes sense (and it still isn't pretty), but those are the exception.

**Comment by aaomidi** [comment]
That is 100% true, when moving to this common interface it might be worth looking to see if deferred makes sense or not.

**Comment by aaomidi** [comment]
@Charles-Gagnon could you add a JSDoc for the deferred to point out that this shouldn't be necessary most of the time?

**Comment by Charles-Gagnon** [comment]
Hmmm, ok I'll at least spend a bit of time looking over the existing usage of Deferred and see if we can get rid of some of them while I'm looking at this.

**Comment by anthonydresser** [comment]
I'd also say lets not put it in azdata since thats basically us signing off on bad programming practice; if you want to abstract it out I would rather make it a library instead.

**Comment by anthonydresser** [comment]
It also doesn't make much since for this to live in azdata since we talk in terms of Thenable to extensions, not promises.

**Comment by anthonydresser** [comment]
We also shouldn't be providing generic javascript abstraction for the extensions unless it directly relates to using our api. We don't want to end up providing essentially a core-js in our apis.

**Pull request closed without merging**
