### PR TITLE
Fixing port request actions 

### LINKED ISSUE #19682: Port Request Labeler Install Actions task not working.
Issue found with the build pipeline: 

https://github.com/microsoft/azuredatastudio/runs/6787543057?check_suite_focus=true 

According to the error, in "on-pr-open.yml": while running the following command under a created folder called "actions":

npm install --production --prefix ./actions/build/actions

It results in an error:  enoent ENOENT: no such file or directory, open '/home/runner/work/azuredatastudio/azuredatastudio/actions/build/actions/package.json'

Running the command locally produces a folder in the azuredatastudio folder, with: 

\actions\build\actions\node_modules\azuredatastudio

which does not appear to match the expected file path.

### PR DESCRIPTION
**Pull request by aasimkhan30**
It seems that the actions folder was accidentally deleted causing the port request labeler workflow to fail when it tried to compile it 

This pr brings it back from release/1.36 branch (The latest release to have it before it was deleted) 

This PR fixes #19682

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
It wasn't on accident - I did it on purpose in https://github.com/microsoft/azuredatastudio/pull/19283 since I thought we weren't using it anymore. 

It looks like VS Code has moved all their actions to a separate repo : https://github.com/microsoft/vscode-github-triage-actions

For now bringing this back for now is fine, but could you take the opportunity to look through that repo and update our stuff with what they have there in case there's fixes or improvements made we can pull in?

**Comment by aasimkhan30** [comment]
@Charles-Gagnon, I looked into https://github.com/microsoft/vscode-github-triage-actions. We can fork the repo and make our own action using the apis they have created. However, I think it will be a decent amount of engineering work for a very small task. My recommendation is to keep using the old action for now. We can have DRI discussion to figure out if we want to migrate to the vscode actions. They do have auto labelling, auto assign and other fun stuff.

**Comment by Charles-Gagnon** [comment]
I definitely don't think we should be forking their repo, that's a lot of overhead for something we barely use. Bringing back the original code is fine, but I'm going to follow up with updating the code here with what's in their repo (mostly for the dependencies) to ensure that we have the latest fixes for everything.

**Review by alanrenmsft — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Is this waiting on anything?

**Comment by aasimkhan30** [comment]
@Charles-Gagnon, the macOS CI workflow has failed twice on the same test. I will merge from the main and see if everything passes before merging it in.

**Pull request merged**
