### PR TITLE
Add Data Grid Provider API

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Second iteration on API for the Resource Viewer.

This is adding a generic "Data Grid Provider" API that will allow extensions to register a provider that can list a set of a columns and data items for use in a general data grid. The exact implementation isn't specified - but to start with I'm mostly making this compatible with the SlickGrid table implementation we have. 

The main use case for this is the new "Resource Viewer" which is meant to show items for a variety of sources - such as Arc Data Controllers and Azure. These resources are best contributed from extensions so that new data sources can easily be added as needed without needing to update the core code to understand every type of data source.

On the extension side it'll look like this :

```
	azdata.dataprotocol.registerDataGridProvider({
		providerId: 'arc',
		getDataGridItems: async () => {
			return [
				{ id: 'item1', typeId: 'arcController', properties: { name: 'MyArcController', location: 'eastus2', subscriptionId: 'sub1'} },
				{ id: 'item2', typeId: 'sqlDatabase', properties: { name: 'MySqlDatabase', location: 'westus', subscriptionId: 'sub1'} },
				{ id: 'item3', typeId: 'sqlServer', properties: { name: 'mySqlServer', location: 'eastus', subscriptionId: 'sub2'} }
			];
		},
		getDataGridColumns: async () => {
			return [
				{ id: 'name', field: 'name', name: 'Name' },
				{ id: 'location', field: 'location', name: 'Location' },
				{ id: 'subscriptionId', field: 'subscriptionId', name: 'Subscription ID' }
			];
		}
	});
```

and on the main thread side it'll look like this 

```
		const columns = await dataGridProviderService.getDataGridColumns('arc');
		const items = await dataGridProviderService.getDataGridColumns('arc');
```

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Ping on this if anyone has time to take a look. Otherwise I plan on merging it in today and then if there's any follow-up feedback making changes as needed since this is all going to be in proposed for a while.

**Comment by anthonydresser** [comment]
We should stop just sticking things in the data protocol , separate classes for separate features is far more maintainable, and I can't see a good reason to put this in the data protocol class

**Comment by Charles-Gagnon** [comment]
I agree - but in this case I was thinking I'd rather have all our DataProviders be together.

But if people really care then I can move it 🤷‍♂️

**Comment by anthonydresser** [comment]
what even is a `data provider`; basically everything the extensions provide is in some way providing data...the initial intention of the data protocol has lost its meaning in the product really. I think every feature through have its own entry point; its just far more maintainable. I would be in favor of deleteing the `dataprotocol` classes and separating them out into their own, but this are back compat issues with that....so for anything new, it should definitely live on its own.

**Comment by Charles-Gagnon** [comment]
@anthonydresser I definitely agree with you - but in the interest of time and me not really feeling like moving it would benefit anything greatly I'm merging this in now. Happy to discuss and then move it later if there's a desire to clean things up though.

**Pull request merged**
