### PR TITLE
Fix Notebook Grid Layout Issue

### LINKED ISSUE #11818: Notebooks: Cannot read property 'layout' of undefined when rendering grid
On insiders, seeing the following issue when executing a notebook that outputs a grid:

image

### PR DESCRIPTION
**Pull request by chlafreniere**
Fixes #11818.

### CODE REVIEW

**Comment by corivera** [comment]
What line is throwing this undefined error?

**Comment by chlafreniere** [comment]
> What line is throwing this undefined error?

https://github.com/microsoft/azuredatastudio/blob/fix/layoutrenderer/src/sql/workbench/contrib/query/browser/gridPanel.ts#L646

**Comment by anthonydresser** [comment]
Would be great to add a basic smoke test for something like this.

**Comment by chlafreniere** [comment]
> Would be great to add a basic smoke test for something like this.

Agreed. We have an integration test that passed even when this exception was thrown (we need to investigate why the test still passed), but +100 on the need for smoke tests here.

**Pull request merged**
