### PR TITLE
Update css styling for radio card

### PR DESCRIPTION
**Pull request by goyal-anjali**
This PR updates css styling for radio card.
- on sku recommendation page, add border radius and transistion

image

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
What is the transition for? Please include a gif showing the new behavior.

**Comment by alanrenmsft** [comment]
is the transition really needed? the only effect is make it a little bit slower to show the selected outline, which I don't think is needed, also, by adding the border radius, now the outline and border are not fully overlapping, leaving  weird white corner(for dark theme)
image

I personally don't think this change is necessary.

**Comment by Charles-Gagnon** [comment]
I agree, this seems like such a minor thing and if we're going to be updating outlines we should be considering it across the entire app. Not just for a single specific case.

**Comment by goyal-anjali** [comment]
Could you please confirm about this @brian-harris   as the designer had suggested these changes? I'll 
go ahead and close this PR if it's not required for this page.

**Comment by brian-harris** [comment]
> Could you please confirm about this @brian-harris as the designer had suggested these changes? I'll
> go ahead and close this PR if it's not required for this page.

can this custom style be applied to the extension code?  does the card control support applying this style so the common control doesn't need to change?

**Comment by goyal-anjali** [comment]
> > Could you please confirm about this @brian-harris as the designer had suggested these changes? I'll
> > go ahead and close this PR if it's not required for this page.
> 
> can this custom style be applied to the extension code? does the card control support applying this style so the common control doesn't need to change?

It is product type component and, as I see it, css cannot be applied to the extension code only.

**Comment by alanrenmsft** [comment]
@brian-harris I don't think we have support to let extension control the style of cards, I still don't think we need this change.

**Pull request closed without merging**
