### PR TITLE
Update extensionsGallery.json for ML 0.7.0

### PR DESCRIPTION
**Pull request by llali**
The vsix file is already uploaded here: https://sqlopsextensions.blob.core.windows.net/extensions/machine-learning/machine-learning-0.5.0.vsix

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@llali Is this intended for immediate release or for the February ADS release?

**Comment by llali** [comment]
@Charles-Gagnon this is for Feb release.

**Comment by Charles-Gagnon** [comment]
Oh whoops, missed that it was to the RC1 branch!

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
RC1 gallery updated

**Pull request merged**
