### PR TITLE
Replace plotly.js-dist with plotly.js-dist-min

### PR DESCRIPTION
**Pull request by aaomidi**
This reduces the footprint of the dependency

### CODE REVIEW

**Comment by anthonydresser** [comment]
Can we just delete the dependency :upside_down_face:

**Comment by chlafreniere** [comment]
Can you provide some documentation around the difference between these two npm packages? I'd like to ensure that we retain compatibility 😄. Have you been able to test that notebooks still work?

**Comment by aaomidi** [comment]
This is essentially the minified version of it. I did a version bump as well because I didn't see anything super obvious that breaks.

But yeah this is the exact same library, just minor version bumped and minified.

**Comment by aaomidi** [comment]
@chlafreniere Are you okay with merging this in and letting it sit in insiders to make sure we're not breaking anything?

**Comment by chlafreniere** [comment]
Sorry was late here; catching up on mail 😄. You did the right thing. Thanks, @aaomidi.

**Pull request merged**
