### PR TITLE
'sai/sql db options map table from sts'

### PR DESCRIPTION
**Pull request by ssreerama**
… from STS

This PR contains:
1. Deployment options names are getting from DacFx property from DisplayNameAttribute and removed lot of useless logic.
2. Include object names are getting from the DacFx objectType enum as a Dictionaty/Map to verify and update the options UI checkboxes.
3. Updated the styles for checkbox and options.
4. Publishing options are now loading from the publish profile if have, else loads default options from the DacFx API(from STS).

### CODE REVIEW

**Comment by ssreerama** [comment]
Some checks are failing because they need the STS changes to pass all, as the STS PR is out, will plan to merge all at same time.

**Comment by kisantia** [comment]
can you please split this up into separate PRs? Then it'll be easier to review and not all the changes will need to wait for the STS changes :)
- PR with the style changes and screenshot
- PR for adding the Object Types tab to the publish options dialog with screenshot
- PR for loading options from profile
- PR for updating deployment options to use DisplayNameAttribute

**Comment by ssreerama** [comment]
I'll try to split into independent PRs, but mostly they have to be created on top of each other. It would be easy for reviewing but not much for updating changes and maintaining  unless we merge them ASAP, before multiple people merge their changes. Thanks :)

**Comment by ssreerama** [comment]
Please ignore this PR:

This PR has been separated into below PRs:
1. Options Map Table: https://github.com/microsoft/azuredatastudio/pull/19789
2. Include Objects Options: https://github.com/microsoft/azuredatastudio/pull/19790
3. Profiles Options: https://github.com/microsoft/azuredatastudio/pull/19791
4. Options dialog CSS Changes: https://github.com/microsoft/azuredatastudio/pull/19792

Thanks.

**Comment by Charles-Gagnon** [comment]
@ssreerama Do you need this one anymore?

**Comment by ssreerama** [comment]
This isn't needed anymore as this was divided into multiple PRs and some were merged already!

**Pull request closed without merging**
