### PR TITLE
Update urlProtocol

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Currently all versions of ADS have the `urlProtocol` set to `azuredatastudio`. This is set every time ADS launches - which means that if you type `azuredatastudio://` into the address bar it'll try to open up the latest version of ADS that you had opened. This is not only confusing, but can lead to weird bugs such as :

1. User has both stable and insiders installed
2. They open up ADS insiders so now `azuredatastudio://` links will open up the insiders version of the app
3. They then close and uninstall ADS Insiders
4. Now `azuredatastudio://` links are broken until they open up ADS stable to re-register the protocol handler

I'm fixing it here to use separate urlProtocols based on the quality level : 

dev - `azuredatastudio-oss` (based on VS Code one here)
stable - `azuredatastudio`
insiders - `azuredatastudio-insiders`
saw - `azuredatastudio-saw`
rc1 - `azuredatastudio-rc1`

@MsSQLGirl @qifahs Do you see any issues with changing this for any of your stuff?

### CODE REVIEW

**Comment by alanrenmsft** [comment]
so the actual changes are in the distro repo?

**Comment by Charles-Gagnon** [comment]
The non-dev build ones are, yes. They look the same as the change here though for those respective files.

**Review by alanrenmsft — APPROVED** [review]

**Comment by alanrenmsft** [comment]
where are we using this feature?

**Comment by Charles-Gagnon** [comment]
Notebooks, resource deployment (for deploying Arc controllers from the portal) and opening TSGs from the portal are the 3 main ones I know of.

**Review by kburtram — APPROVED** [review]

**Comment by MsSQLGirl** [comment]
Apologies for the late reply. The proposed changes should be fine.

Thanks!

**Pull request merged**
