### PR TITLE
Updating axios package to fix component governance issue.

### PR DESCRIPTION
**Pull request by aasimkhan30**
Updating the necessary libraries to remove the CG error. I will request reviews from the area owners for testing and sanity check. 

1. Extensions/Features directly or indirectly affected by the package updates:

- [x] Arc @Charles-Gagnon 
- [x] Machine learning @llali 
- [x] Azure Accounts  @cssuh
- [x] SQL Migration @aasimkhan30 
- [x] Resource Deployment @aasimkhan30, @Charles-Gagnon, @alanrenmsft
- [x] Browse Connections

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
Have you done any sort of testing @aasimkhan30? I would suggest making a checklist of features that had their packages updated so that we can verify which ones have been checked to ensure that functionality is intact.

**Comment by aasimkhan30** [comment]
@Charles-Gagnon , I have tested sql-migration, sql vm and db deployements. 
In the core side, I have tested azure account.

**Comment by aasimkhan30** [comment]
Also, I am adding packages that are consuming azure core.

**Comment by Charles-Gagnon** [comment]
Why did you list Arc? Is it just because of its contribution to resource deployment?

**Comment by Charles-Gagnon** [comment]
If you've already tested azurecore stuff like fetching subs then we should be good for anything using it - that code is going to be all the same anyways.

**Comment by Charles-Gagnon** [comment]
Please update the checkboxes with what you've tested so we can see what's been completed.

**Comment by alanrenmsft** [comment]
How am I supposed to do the testing? did you produce a build? also, please add the "connection dialog - browse tab"to the checklist

**Comment by aasimkhan30** [comment]
@Charles-Gagnon , I just listed the extensions using azure core.  Sorry, if it was not using axios specific stuff.

**Comment by aasimkhan30** [comment]
@Charles-Gagnon , I just listed the extensions using azure core.  Sorry, if it was not using axios specific stuff.

**Comment by aasimkhan30** [comment]
There is an azure-resourcegraph package in azurecore extension that requires ms-rest-js package which in turn requires node-fetch package. However, running the yarn command, does not automatically pulls this 'node-fetch' package. This was causing a test failure as the extension could not activate successfully due to the missing package. Adding node-fetch to azurecore separately fixes this bug.

**Review by kburtram — APPROVED** [review]
Source code looks fine, though agree that this would require runtime testing verify any breaks.

**Pull request merged**
