### PR TITLE
Allow zonejs to clean up errors

### PR DESCRIPTION
**Pull request by aaomidi**
This is the last time im going to be trying this

Reverts microsoft/azuredatastudio#7568

### CODE REVIEW

**Comment by aaomidi** [comment]
> Just make sure we're testing this with a packaged build manually first 😁

Yeah the tests are saying this is failing. I'm going to wait on this one because I'm not entirely sure what the issue is.

**Comment by aaomidi** [comment]
Wow, this actually worked. @anthonydresser do you have any insight on why my last commit fixed the product issue?

**Comment by anthonydresser** [comment]
What's the issue that was fixed?

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/issues/7562

**Comment by anthonydresser** [comment]
Does it only happen in production?

**Comment by aaomidi** [comment]
Yup

**Comment by anthonydresser** [comment]
Probably has to do with how the optmizer is creating the main file and the order. You could just put the unhandled error handling as a carbon edit in the vscode error file

**Comment by aaomidi** [comment]
@anthonydresser Should we access the global in a common folder?

**Comment by aaomidi** [comment]
image

**Comment by aaomidi** [comment]
Lets start with a really simple version of this and then add more to it.

**Pull request closed without merging**
