### PR TITLE
Update azure-cosmosdb-ads-extension version to 0.1.4

### PR DESCRIPTION
**Pull request by languy**
This PR fixes updates azure-cosmosdb-ads-extension to version 0.1.4 and fixes its Engine dependencies.

Please find the signed VSIX build [here](https://msdata.visualstudio.com/CosmosDB/_build/results?buildId=75703604&view=artifacts&pathAsName=false&type=publishedArtifacts).

### CODE REVIEW

**Comment by alanrenmsft** [comment]
@languy how about the stable gallery file?

**Comment by alanrenmsft** [comment]
@languy The file size was pretty large so I took a look at the contents, it turns out it contains a lot of files that shouldn't be there. Please fix the script and at least remove item 3 from the package.

1. mongoshell - should be downloaded at runtime, for offline environment, you can provide platform specific vsix files.
image

2. a large JSON file - is this really needed?
image

3. ADS binaries - these should definitely not be here.
image

**Comment by languy** [comment]
> @languy The file size was pretty large so I took a look at the contents, it turns out it contains a lot of files that shouldn't be there. Please fix the script and at least remove item 3 from the package.
> 
> 1. mongoshell - should be downloaded at runtime, for offline environment, you can provide platform specific vsix files.
>    image
> 2. a large JSON file - is this really needed?
>    image
> 3. ADS binaries - these should definitely not be here.
>    image

1. My original design was indeeed to download these binaries from the ADS storage just like how other extensions do it with their binaries, but our security team added two items to address:  a/ DOS prevention for the storage hosting the mongo binaries b/ Update mechanism for the mongo binaries.
What was recommended to me at the time to alleviate b/ and get past the review was to ship the extension with the binary and rely on ADS/Vscode version extension mechanism to update these shipped binaries (if the user doesn't prevent extension updates). 
Let me revisit these tickets with our (new) security. I'll challenge c/ as a non-issue, since the extensions itself along with all other extensions live on the same storage. And forcing an update of the extension may update the zip files that ship, but not the unzipped files. Downloading the zip and deleting the local unzipped files upon activation/installation should be sufficient.

2. This is the sample data (we have a "Sample Data" button that creates a collection and imports the sample data. Can definitely be downloaded from storage.

3. Will work on removing: this was accidentally introduced when I fixed the unit tests in CI (which now download ads instead of vscode to perform the tests).

0.1.4 is a hotfix for a customer issue. So I would like to ship 0.1.4 asap with 1. and 2. (without 3.) and create a 0.2.0 version without 1. and 2. subsequently if that's ok with you guys.

**Comment by alanrenmsft** [comment]
@languy sounds good to me.

**Comment by languy** [comment]
I updated the download link in the description.

**Review by alanrenmsft — APPROVED** [review]

**Pull request merged**
