### PR TITLE
Remove Notebook grammar

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
@chlafreniere Maybe you have more context on why that was added (https://github.com/microsoft/azuredatastudio/pull/7375) but I'm not really seeing why this is necessary since as far as I'm aware we don't really have a need to support people modifying the text content of a Notebook in VS Code. And removing this gets rid of the "tokenization skipped" warning message that pops up a lot which is pretty confusing for the user.

### CODE REVIEW

**Comment by chlafreniere** [comment]
@Charles-Gagnon let me look into this and do some testing.

**Comment by Charles-Gagnon** [comment]
This definitely doesn't need to go into this release so whenever you get a chance. I've just been annoyed by that message for so long I wanted to see if we could do something about it.

**Comment by chlafreniere** [comment]
> This definitely doesn't need to go into this release so whenever you get a chance. I've just been annoyed by that message for so long I wanted to see if we could do something about it.

I hear ya. The change makes me nervous in general (especially around hot exit scenarios), so we'll have to do our due diligence here.

**Comment by Charles-Gagnon** [comment]
How would the grammar have anything to do with hot exit scenarios? As far as I'm aware the grammar is really only used for stuff like suggestions, highlighting, paren auto-close and such 

https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide

**Comment by chlafreniere** [comment]
@Charles-Gagnon my understanding is that tokenization is critical to do things like bracket matching (e.g. here in the nb text file model): https://github.com/microsoft/azuredatastudio/blob/chgagnon/removeNotebookGrammar/src/sql/workbench/contrib/notebook/browser/models/notebookTextFileModel.ts#L306)

**Comment by Charles-Gagnon** [comment]
Yeah but that'd just be for the text editor right? Given that we have our own custom editor when would that come up? (unless we wanted to support opening a Notebook as JSON and modifying it directly there. But I don't think that's really something we support now, or at least I can't find a way to do that)

**Comment by chlafreniere** [comment]
> Yeah but that'd just be for the text editor right? Given that we have our own custom editor when would that come up? (unless we wanted to support opening a Notebook as JSON and modifying it directly there. But I don't think that's really something we support now, or at least I can't find a way to do that that isn't just a bug)

If it's only for the text editor layer and doesn't actually affect tokenization at the editorModel then all good 😄

**Comment by Charles-Gagnon** [comment]
I'd have to look into it - how do you think our stuff is using the tokens? I thought that was mostly limited to just built-in intellisense type stuff but I may be wrong on that if we're utilizing that for other things.

**Comment by Charles-Gagnon** [comment]
@chlafreniere I haven't been able to find anything that's actually using the grammar here, do you have any issues with getting this in at this point?

**Review by chlafreniere — APPROVED** [review]

**Pull request merged**
