### PR TITLE
fix schema compare dropdown not selecting correct db when multiple active connections

### PR DESCRIPTION
**Pull request by kisantia**
This PR fixes https://github.com/microsoft/azuredatastudio/issues/12779 and addresses https://github.com/microsoft/azuredatastudio/issues/14957. This missing parenthesis was causing the string comparison to fail when looking for the previously selected server connection, so it was defaulting to the most recent connection when there were multiple active connections.
https://github.com/microsoft/azuredatastudio/blob/a3cddbc8aadf4106fd9877b111ec64b3d609cc61/extensions/schema-compare/src/dialogs/schemaCompareDialog.ts#L559-L564

schemaCompareDropdown

### CODE REVIEW

**Review by udeeshagautam — APPROVED** [review]

**Review by SakshiS-harma — COMMENTED** [review]
This doesn't  fully solve the problem. If the pre-populated server is the first in the list, the issue is resolved. But if the server (that we are using for schema compare in Source) is second in list, the pre-populated server info in Source falls back to the first server (and the first listed database).

**Comment by udeeshagautam** [comment]
> This doesn't fully solve the problem. If the pre-populated server is the first in the list, the issue is resolved. But if the server (that we are using for schema compare in Source) is second in list, the pre-populated server info in Source falls back to the first server (and the first listed database).

@SakshiS-harma  not sure i fully understand - this changes compare server names (not database names) - so why the right server name wont be picked?

**Comment by kisantia** [comment]
@udeeshagautam the problem @SakshiS-harma found was when connecting with windows auth instead of username and password. "Default" gets put in parenthesis for the connection names in the dropdowns for windows auth, but that wasn't getting set in the sourceEndpointInfo, so the string comparison wasn't working correctly.

**Review by SakshiS-harma — APPROVED** [review]

**Comment by udeeshagautam** [comment]
Ah thanks both for the clarification!

**Pull request merged**
