### PR TITLE
Add a new developer to the list of developers for onboarding purposes

### PR DESCRIPTION
**Pull request by lewis-sanchez**
Onboarding pull request.

### CODE REVIEW

**Review by Charles-Gagnon — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@lewis-sanchez Make sure you're adding people as reviewers when submitting PRs, otherwise most people aren't going to see these

**Review by kburtram — APPROVED** [review]
LGTM

**Comment by Charles-Gagnon** [comment]
@lewis-sanchez You can merge this in whenever you want

**Comment by lewis-sanchez** [comment]
@Charles-Gagnon, merged.

**Pull request merged**
