### PR TITLE
fix the check

### PR DESCRIPTION
**Pull request by MaddyDev**
When checking for the explicit false, forgot to remove the ! and that's the possible culprit of the test failure

### CODE REVIEW

**Review by chlafreniere — APPROVED** [review]
If the tests all pass, then yikes (we need a bit better unit test coverage 😄 ), but we can unblock the builds if checks succeed here.

**Comment by corivera** [comment]
A more verbose change message would be nice here. The title is currently pretty vague.

**Review by corivera — APPROVED** [review]

**Comment by MaddyDev** [comment]
> If the tests all pass, then yikes (we need a bit better unit test coverage 😄 ), but we can unblock the builds if checks succeed here.

Agreed! Charles has been advocating the same, I'll start on it asap.

**Review by Charles-Gagnon — APPROVED** [review]
We can kick off the product build after this is in to see if it fixes the test issue

**Pull request merged**
