### PR TITLE
fix add database reference dialog test

### PR DESCRIPTION
**Pull request by kisantia**
This test started failing after Master was switched to be uppercase in https://github.com/microsoft/azuredatastudio/pull/22215 to match how DacFx.Projects is storing it.

### CODE REVIEW

**Review by Benjin — APPROVED** [review]

**Review by kburtram — APPROVED** [review]
Looks fine, but typically I see `master` as lower-case in tooling.  Is changing this casing in the related PR going to have problems on servers with case-sensitive collations?

**Comment by Benjin** [comment]
@kburtram

> Looks fine, but typically I see `master` as lower-case in tooling. Is changing this casing in the related PR going to have problems on servers with case-sensitive collations?

The .sqlproj file still contains `master` with lower-case, since the value in this PR gets passed down to STS via enum and it's lowercased there. 

@kisantia We probs should revert the string change (`constants.master` and `constants.msdb`) so that the UI is consistent across tooling; that shouldn't affect the enum casing (which I'd only changed that to match typescript convention).

**Comment by kisantia** [comment]
@Benjin I changed had updated `constants.master` and `constants.msdb` to be uppercase to match what DacFx.Projects was expecting as the name for delete (Master and MSDB). Think it makes more sense to update the `SystemDatabase` enum in DacFx to have the lowercase names or to convert the names to uppercase when the extension sends the name to STS?

**Comment by kisantia** [comment]
Discussed offline - we'll update DacFx to use the do a case-insensitive compare and I'll update the strings in ADS back to lowercase

**Pull request closed without merging**
