### PR TITLE
Insiders icons

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Changing all icons to be the insiders versions by default. Mixin process will be used to replace with stable icons for releases.

### CODE REVIEW

**Comment by anthonydresser** [comment]
@kburtram At this point it might be worth not doing this and just using mixin's since its all setup.

**Comment by Charles-Gagnon** [comment]
@anthonydresser  What's the process for getting that working?

**Comment by anthonydresser** [comment]
if @kburtram agrees. just do a straight replacement of the icons (so in master we have the icons we want in insiders) then I'll update the mixin repo to have the correct icons for release.

**Comment by anthonydresser** [comment]
and by do a straight replacement I mean don't do any of the code changes where you have branching behavior for stable vs insiders, so this pr should just be icon replacements.

**Comment by Charles-Gagnon** [comment]
What repo is this? Would we have to change our stable release builds to be from there instead then?

**Comment by anthonydresser** [comment]
I am handling integrating the mixin into our build process. The resources are ready, I just need to add an additional step in our build process but I'm waiting on confirmation from @kburtram before I do this.

**Comment by kevcunnane** [comment]
For what it's worth, I'd love to see us adopt mixins for more things. If we can go with that approach it's worth a small delay.

**Comment by kburtram** [comment]
@anthonydresser if this is simple to do in the mixins I'd recommend doing it there.  No concerns on from me with updating the insiders icon.

**Comment by Charles-Gagnon** [comment]
@anthonydresser Alright, I updated this PR to just switch all the icons over to their insiders versions. Once you get your changes done for the mixin stuff either let me know or just merge it in yourself.

**Comment by anthonydresser** [comment]
I think you can merge this in, I updated the resources in distro already, but had to stop my changes to the pipelines to do the mixin because of the hotfix. I'll get the mixin stuff in tomorrow or monday as my dri work. 

But since we don't plan on releasing a stable release before then, this shouldn't have any impact, except to change the icons for insiders (which is desired). As a side note, are we going to have separate icons for dev builds? Or which icon's do we want to show up for dev builds out of master?

**Comment by Charles-Gagnon** [comment]
There's no plans for separate icons for dev builds at this point. The insiders icons was mostly for external users to be able to easily tell the difference when running side by side (which is less likely to be something people using dev builds are doing)

**Pull request merged**
