### PR TITLE
Encode file paths used as owner uris for connection ids

### LINKED ISSUE #10259: Notebooks have strange behavior when path contains '%20'
Issue Type: <b>Bug</b>

On my machine, when I run a SQL statement it fails consistent.
- I have a brand new machine 

Rendering is failing for all SQL at various different points...
- If I re-open a SAVED NOTEBOOK mostly

I've installed the tool 5 or 6 times various versions.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

### PR DESCRIPTION
**Pull request by pensivebrian**
This PR fixes #10259 for notebooks.

The notebook issue is caused by not URL encoding file paths using as ownerUris before sending/receiving rpc message from the sqltoolsservice.

An example... suppose we have a file path `/ADS/Project%20Root`. Client-side in ADS in the connection id map, the ownerUri key is ` /ADS/Project%20Root`. However, before sending this uri to the sqltoolsservice, we call `URI.parse('/ADS/Project%20Root')` on the uri. This returns `/ADS/Project Root`, which results in the sqltoolsservice using `/ADS/Project Root` as the ownerUri key. Whenever the sqltoolsservice raises an event using that ownerUri, the ADS client can't find the key in the connection id map due to the %20 being remove  and `/ADS/Project Root != /ADS/Project%20Root`.

The fix is to url encode file paths before invoking URI.parse on any ownerUri.

This issue still exists for the query editor, which requires a different fix and tracked by #13684.

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
What about all the other places we're doing this kind of parsing/transforming? e.g. https://github.com/microsoft/azuredatastudio/blob/main/src%2Fsql%2Fworkbench%2Fcontrib%2Fquery%2Fbrowser%2FqueryResultsView.ts#L312

I did a quick test with this change myself and it does seem to work as I'd expect for these calls both to and from STS. But I'm also extremely wary that this kind of change will break a lot of stuff in various ways so I think we should definitely wait until at least after the December release to get this in.

**Comment by pensivebrian** [comment]
> What about all the other places we're doing this kind of parsing/transforming? e.g. https://github.com/microsoft/azuredatastudio/blob/main/src%2Fsql%2Fworkbench%2Fcontrib%2Fquery%2Fbrowser%2FqueryResultsView.ts#L312

Good point. I need to step through this code. I hope the owner uri is patched in as the response if received from the sqltoolsservice at a lower layer, so it should already set correctly but I'll confirm. The fact that there is an 'or' statement and that we're invoking a private method is cause for concern.
 
> I did a quick test with this change myself and it does seem to work as I'd expect for these calls both to and from STS. But I'm also extremely wary that this kind of change will break a lot of stuff in various ways so I think we should definitely wait until at least after the December release to get this in.

I agree with this going in after December until I have more comprehensive tests. Plus, this just fixes notebooks, and I'm currently stumped as to why the query editor is still broken - I obviously don't understand all of this quite yet.

**Comment by pensivebrian** [comment]
The query editor and notebook take different code paths in the sqltoolsservice, which why this fix works for notebooks but not the query editor. 

The notebook passes the query text as part of the request - no file resolution needed by the sqltoolsservice.

The query editor passes the file path which contains the query text. When file path has %20 in the path, the sqltoolsservice fails to resolve the file path. Looks like an issue Workspace.ResolveFilePath(). I'll investigate a fix for the query editor, but from the looks of it, this will be probably be a fix in the sqltoolsservice in a subsequent PR.

**Review by kburtram — APPROVED** [review]
I'm not sure whether this could introduce side-effects in query editor.  Also, paths are handled differently on webmode and remote scenarios where the frontend and backend could be running on different OSes.  We will need to validate this in those scenarios as well.  But at a high-level if no issues are discovered during testing then this looks fine to me.

**Comment by pensivebrian** [comment]
Running the full test suite including the webmode tests didn't introduce any test failures, and manually testing macOS and Windows looks good with this change.

**Comment by Charles-Gagnon** [comment]
Closing this as @alanrenmsft is working on this in https://github.com/microsoft/azuredatastudio/pull/14299

**Pull request closed without merging**
