### PR TITLE
Fixing server group styling

### PR DESCRIPTION
**Pull request by aasimkhan30**
New Server Group Styling:
- Adds server group color to connections
- Adds back guide which was removed in #7119 (@Charles-Gagnon I did not understand the issue due to which it was removed #7117)
- This is based off on a new design suggested by UX.
 Mockup:
 image

Now:
image
When something is searched:
image

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
TBH, I'm not really a fan of the beveled edges. What exactly is this "fixing"? It seemed fine to me beforehand - was there specific feedback you're addressing here?

**Comment by alanrenmsft** [comment]
is this recommended by the designer?

**Review by kburtram — COMMENTED** [review]
FWIW, I also like this style less than the current one.

**Comment by aasimkhan30** [comment]
@Charles-Gagnon , do you know why tree guides were removed in the first place.

**Review by Charles-Gagnon — APPROVED** [review]
I don't recall the specifics of that ask - although I think it was prompted by it just feeling like too much visual clutter. I don't have a problem with bringing it back now though - especially since there's a setting (Workbench -> Tree: Indent) that controls whether it's shown or not. Make sure you test that to verify it works here as well.

1. Did you verify that if you change the server group color that the colors of the nodes under it also change?
2. In your second screenshot the solid border is cut off on the left side in high contrast mode - was that just an issue with the screenshot cutting it off?

Make sure you schedule an a11y re-review of the tree once you're finished with your changes in this area as well so they can check it over for any issues we missed.

**Comment by aasimkhan30** [comment]
@Charles-Gagnon ,
1. Yes, I was able to change the behavior of indent guides using the settings.
2. Yes, it re-renders the child connections as well and changes the color for them. 
3. Yes, that's just the screenshot cutting it off.

**Comment by erinstellato-ms** [comment]
To confirm - we  are implementing to get some feedback from users, correct?  The contrast is better for highlighting, but it feels very busy.

**Review by alanrenmsft — APPROVED** [review]

**Comment by aasimkhan30** [comment]
@Charles-Gagnon and @erinstellato-ms 
Adding gif for the indent guides

azuredatastudio_SfWsSHcurk

**Pull request merged**
