### PR TITLE
Disable building web mode

### PR DESCRIPTION
**Pull request by alanrenmsft**
Fixes https://github.com/microsoft/azuredatastudio/issues/15541

image

### CODE REVIEW

**Comment by alanrenmsft** [comment]
queued a full build to see whether I missed something else.

**Comment by kburtram** [comment]
@alanrenmsft unless something is blocked on this, I'd rather fix a different way.

**Review by kburtram — CHANGES_REQUESTED** [review]
Ping me if this is blocking something.

**Comment by alanrenmsft** [comment]
https://github.com/microsoft/azuredatastudio/issues/15541 

this is the issue, it is not blocking anything at the moment, if folks need to release new version of extension, the workaround is to build the vsix locally.

feel free to close this PR and fix it in the appropriate way.

@kburtram

**Pull request closed without merging**
