### PR TITLE
Styling updates for HDFS Manage Access Dialog

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Look and feel is mostly completed with this change (barring review from @angdesign )

Delete icon is currently light-theme only, waiting to get actual dark theme one.

image

### CODE REVIEW

**Comment by angdesign** [comment]
Is there a way for us to use standard checkboxes seen in ADS? Those appear to be a different style.

**Comment by Charles-Gagnon** [comment]
What do you mean standard style? These are the normal checkboxes - just bigger as per the design spec

image

**Comment by alanrenmsft** [comment]
looks good to me.

**Comment by Charles-Gagnon** [comment]
@angdesign I'm merging in now - let me know when you have the dark mode icon and I'll add it. And any other comments you have (such as the checkboxes) just follow up with me offline.

**Comment by angdesign** [comment]
Here is the delete icon inverted for dark theme

[delete_inverse.svg.zip](https://github.com/microsoft/azuredatastudio/files/3704927/delete_inverse.svg.zip)

**Pull request merged**
