### PR TITLE
Add Slider component

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Planned initial usage is for Arc dashboards and deployment wizards.

I purposely started off pretty basic as far as features go - so there's no custom styling or anything like that. We can add it later as needed.

Example usage showing a couple different set of properties from the extension side.

Slider

image

### CODE REVIEW

**Comment by chlafreniere** [comment]
@Charles-Gagnon can you describe what you tested accessibility-wise?

**Comment by alanrenmsft** [comment]
@chlafreniere this is native html feature: https://www.w3schools.com/tags/att_input_type_range.asp, the only thing we need to make sure is we have aria-label set (I checked, we do have it)

**Review by alanrenmsft — APPROVED** [review]

**Review by kisantia — APPROVED** [review]

**Comment by Charles-Gagnon** [comment]
@chlafreniere I checked NVDA (screen reader) and different color themes and everything seems good. Thanks for checking on that!

**Comment by Charles-Gagnon** [comment]
Also for context here : 

1. I considered adding a label field (some of our other components have it) but currently with how I'm going to be using this I don't need it since the label will be created separately so I decided to keep this simpler and just not include that for now
2. The designs showed an option to list the values at each tick mark as well

image

Unfortunately currently Chrome doesn't support adding labels to the datalist items so doing this would require a more custom solution. I'm going to chat with the designers to see how important this feature is and if we decide it's needed then can work on that separately.

**Comment by chlafreniere** [comment]
Thanks for the clarification @Charles-Gagnon. Glad to hear that accessibility was top of mind 😃

**Pull request merged**
