### PR TITLE
Update row count as row updates are received

### LINKED ISSUE #5799: Update row count as results are available
Per #5795; we are currently hiding the status for row count when a query starts until the query finishes. Ideally we would instead just update the count as results come in.

### PR DESCRIPTION
**Pull request by devmattrick**
Fixes #5799 

This will update the row count while the query is still running.

In order to make this work when QueryModelService.getQueryRunner returns undefined, it was necessary to add an update event to QueryModelService.

### CODE REVIEW

**Comment by anthonydresser** [comment]
Let me get #6513 in, then a lot of this PR can be simplified

**Comment by devmattrick** [comment]
Done 👍

**Comment by anthonydresser** [comment]
Looks like you might need to do another merge, to perhaps rebase your inital commit onto master. Since Github is show that your PR will make more changes that intended

**Comment by devmattrick** [comment]
Closing in favor of #6642.

**Pull request closed without merging**
