### PR TITLE
Save grid selection/vertical scroll when switching tabs

### PR DESCRIPTION
**Pull request by MattIrv**
This is for #3673, where result grid selections and scroll positions are no longer getting saved when switching between tabs.

I'm still investigating an issue where the overall result's scroll position gets reset only when switching between a query editor tab and a non-query tab. Also the horizontal scroll position in the grid doesn't get saved but that's not a regression from November at least

Update: Solved the issue with the overall split view's scroll position getting reset

### CODE REVIEW

**Comment by MattIrv** [comment]
@anthonydresser can you take a quick look at this to make sure no problems jump out at you? I still don't understand why this broke yet but I think it was related to the result streaming changes

**Comment by anthonydresser** [comment]
The problem with the stating is that slickgrid doesn't handle setting scroll position and selection very well if the data is updated after they are set, and how the async data works, we can't reliably serialize the operations.

The simple solution is to add a setttimeout and do all the stating after some short delay, with the assumption that in most scenarios the rendering will be done and therefore everything will work as expected, but settimeouts are a pretty bad way of doing things.

The real solution is to modify slickgrid to handle setting selection and scroll position better similar to vscode's tree, but this could be a pretty significant amount of work.

**Comment by kburtram** [comment]
@MattIrv @anthonydresser this is last remaining planned fix for January release.  Do we think it's fine to take as-is for Jan?  We can work on a different fix for post-Jan if needed.

**Comment by MattIrv** [comment]
Just pushed a new commit to save the horizontal scroll position in addition to the vertical one.

There's still a small bug where sometimes with multiple result sets the overall scroll doesn't get saved correctly but in my testing things seem to be working well now. I think we should take it now for the release but it would be good to get a few more eyes on it for testing too

**Comment by kburtram** [comment]
@MattIrv sounds good.  I'll merge this change into the release branch now, and test a bit more.  In initial testing I didn't see any issues.

**Pull request merged**
