### PR TITLE
Add `$schema` to `cgmanifest.json`

### PR DESCRIPTION
**Pull request by JamieMagee**
This pull request adds the JSON schema for `cgmanifest.json`.

### Why?

A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.

### How can I validate my `cgmanifest.json` file?

Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.

### Why does it suggest camel case for the properties?

Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.

### Why is the diff so large?

To deserialize the `cgmanifest.json` file, we use [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse).
However, to serialize the JSON again we use [`prettier`](https://prettier.io/).
We found that, in general, it gave smaller diffs than the default [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) function.

### CODE REVIEW

**Review by kburtram — DISMISSED** [review]
This change is causing code hygiene errors regarding "bad whitespace".  These checks should run on "git commit" or can be run directly from gulp.

**Comment by JamieMagee** [comment]
Hi @kburtram this PR was created automatically using the GitHub API. I can manually fix it, but where can I find the guidelines I should follow?

**Comment by JamieMagee** [comment]
@kburtram I've manually updated all the `cgmanifest.json` in your repository, and also removed the custom `cgmanifest.schema.json` file.

**Comment by Charles-Gagnon** [comment]
@JamieMagee Can you give a little more context on this change? We inherited this file from VS Code and it appears to be a customized version of the schema that you're now linking to (https://json.schemastore.org/component-detection-manifest.json)

We inherited this from VS Code so I don't really have the exact context on why they're using this custom schema - but my suggestion would be to open up a PR in the VS Code repo (https://github.com/microsoft/vscode) first which may help determine if there's a reason they/us have it set up like it is currently.

**Comment by kburtram** [comment]
@JamieMagee overall the change looks fine to me and CI checks are passing.  As Charles mentions these files are all coming from upstream so it would be good to have a similar PR upstream in vscode and allow the code owners comment on this change.  I assume this is some type of clean-up effort across Microsoft repos?  Has this been done for vscode repo yet?

**Comment by JamieMagee** [comment]
Sure! `cgmanifest.json` is our fallback detector in Component Detection whenever we don't have a detector for your package manager. The format has always been a little opaque for our users. It's documented [here][1], but we wanted to create a JSON Schema so users don't have to leave their IDE, and can get instant feedback. Selfishly, we're hoping that this will decrease our support burden 😅 

I'm not sure about the custom properties that VSCode set. We don't use them, but maybe they're extending our format with some custom tooling? I'll reach out to someone on the VSCode team and find out more about their use case for `cgmanifest.json` beyond what we use it for.

The script we're running hasn't reached the `vscode` repo yet, it's only been run for a small subset of repositories in the `microsoft` GitHub organization. But the intention is to run it across all repositories in the `microsoft`, `Azure`, `dotnet`, etc. organizations.

[1]: https://docs.opensource.microsoft.com/tools/cg/features/cgmanifest/

**Comment by Charles-Gagnon** [comment]
@JamieMagee I see that https://github.com/microsoft/vscode/pull/159779/files was accepted, do you have time to undo the $schema changes and do the same as the other one here?

**Comment by JamieMagee** [comment]
@Charles-Gagnon I've ported over the change from the vscode repository.

**Review by Charles-Gagnon — APPROVED** [review]

**Pull request merged**
