### PR TITLE
Merge VS Code 1.30.1

### PR DESCRIPTION
**Pull request by MattIrv**

### CODE REVIEW

**Comment by MattIrv** [comment]
Here's a diff that doesn't include merge commits, just the changes I made after the merge to make things work correctly: https://github.com/Microsoft/azuredatastudio/pull/4092/files/94ae9b19efa889f5aa3dfb56a8416d1e8f4fe8a1..ff94b6567188f8f8c0dff3ef98b7d6ec99fb92e7

**Comment by anthonydresser** [comment]
We should probably make items for handling what vscode sees as debt (and for good reasons). https://github.com/Microsoft/vscode/issues/57196 https://github.com/Microsoft/vscode/issues/53526

**Comment by MattIrv** [comment]
Thanks for pulling those up. I filed two issues to track it:
Builder: 
https://github.com/Microsoft/azuredatastudio/issues/4095
Promise: 
https://github.com/Microsoft/azuredatastudio/issues/4096

**Comment by anthonydresser** [comment]
Whats the reason for change the new query task icon to undefined?
https://github.com/Microsoft/azuredatastudio/blob/merge130-nohistory-msft/src/sql/workbench/common/actions.ts#L55

**Comment by anthonydresser** [comment]
We should probably mark this is debt https://github.com/Microsoft/azuredatastudio/blob/merge130-nohistory-msft/src/sql/workbench/electron-browser/menus.ts
And move to vscode's new menu system (contribution based).

**Comment by MattIrv** [comment]
The task icon field is for icon file paths, which we've never used. With this VS Code merge it started throwing errors instead of just silently failing when it couldn't parse the icon path. The icons we use are set by the CSS class right below it.

I'll open a bug for the menu as well

**Comment by anthonydresser** [comment]
Are we planning on shifting to vscode's pipeline script? https://github.com/Microsoft/azuredatastudio/tree/merge130-nohistory-msft/build/azure-pipelines

**Pull request merged**
